name: harcapp
description: HarcAppka (Daniel Iwanicki)

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.2.8+73 # 3.1.9+72 #

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:

  aad_oauth: ^0.3.0
  after_layout: ^1.1.0
  animated_text_kit: ^4.2.1
  #assets_audio_player: ^3.0.4+1
  assets_audio_player:
    git:
      url: https://github.com/luis901101/Flutter-AssetsAudioPlayer.git
      ref: master
  auto_size_text: 3.0.0
  avatar_glow: ^2.0.2
  back_button_interceptor: ^6.0.0
  confetti: ^0.7.0
  date_picker_timeline: 1.2.3
  device_info_plus: ^3.2.3
  dio: ^4.0.6
  dropdown_button2: 1.5.1
  expandable_text: 2.3.0
  extended_nested_scroll_view: 6.0.0-dev.1
  flip_card: ^0.6.0
  flutter_email_sender: ^5.1.0
  flutter_keyboard_visibility: ^5.2.0
  flutter_lints: ^2.0.1
  flutter_map: ^0.14.0
  flutter_reorderable_list: ^1.2.0
  flutter_secure_storage: ^4.2.1
  flutter_slidable: ^1.2.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_animations: 1.0.0
  flutter_svg: ^1.0.3
  flutter_translate: ^4.0.2
  gallery_saver: ^2.3.2
  google_fonts: ^2.3.2
  html_unescape: ^2.0.0
  image: ^3.1.3
  latlong2: ^0.8.1
  lifecycle: ^0.5.0
  logger: ^1.1.0
  numberpicker: ^2.1.1
  oktoast: ^3.2.0
  open_file: ^3.2.1
  optional: 6.1.0+1
  package_info: ^2.0.2
  palette_generator: ^0.3.3
  path: ^1.8.1
  path_provider: ^2.0.10
  pdf: ^3.8.1
  percent_indicator: ^4.2.2
  permission_handler: ^9.2.0
  pretty_json: ^2.0.0
  printing: ^5.9.1
  pro_animated_blur: ^0.0.2+1
  pull_to_refresh: ^2.0.0
  #qr_flutter: ^4.0.0 #generator
  qr_flutter:
    git:
      url: https://github.com/lukef/qr.flutter
  qrscan: ^0.3.2
  semaphore: ^0.2.1
  sensors: ^2.0.3
  share: ^2.0.4
  shared_preferences: ^2.0.15
  simple_shadow: ^0.3.0
  smooth_page_indicator: ^1.0.0+2
  system_time_check: ^1.0.0
  tab_indicator_styler: ^2.0.0
  torch_light: ^0.4.0
  url_launcher: ^6.1.2
  wakelock: ^0.6.1+2
  webfeed: ^0.7.0
  youtube_player_flutter: ^8.0.0 # add dependencies to iOS # add dependencies to Android

  #qrcode_reader:
  #  git:
  #    url: https://github.com/bcko/flutter_qrcode_reader
      # ref: 88d1b58efbf9856d1220025f78d475e41ef4ba22

      #circular_check_box:
      #git:
      #url: git://github.com/mashnoon33/circular_check_box.git

  #webfeed:
  #  git:
  #    url: git://github.com/n3o2k7i8ch5/webfeed.git

  harcapp_core:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core

  harcapp_core_tags:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core_tags

  harcapp_core_song:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core_song

  harcapp_core_song_widget:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core_song_widget

  harcapp_core_own_song:
    git:
      url: https://github.com/n3o2k7i8ch5/harcapp_core_own_song


  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/
    - assets/account/
    - assets/apel_ewan/
    - assets/documents/
    - assets/forms/
    - assets/gawedy/
    - assets/images/
    - assets/images/bio/
    - assets/images/circle/cover_images/
    - assets/images/emo/
    - assets/images/games/
    - assets/images/gawedy/
    - assets/images/harcthought/
    - assets/images/hist/
    - assets/images/kuch/
    - assets/images/leaf/
    - assets/images/leaf_bg/
    - assets/images/leaf_kora/
    - assets/images/logo/
    - assets/images/meto/
    - assets/images/scout_org_logos/
    - assets/images/snowflake/
    - assets/images/start/
    - assets/images/stref_duch/
    - assets/images/symb/
    - assets/images/znaki_patro/
    - assets/song_words/
    - assets/songs/
    - assets/songs_confid/

    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/rozpalanie_ognia/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/orient_w_teren/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/samarytanka/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/musztra/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/lacznosc/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/biwakowanie/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/kwatermistrzostwo/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/obozownictwo/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/podchody_i_zwiady/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/bezpieczenstwo_obozowe/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/tropienie_zwierzat/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/zielarstwo/
    - assets/spraw/zhr_harc_c/ozdobnictwo_i_przyroda/puszczanstwo/

    - assets/spraw/zhr_harc_c/muzyka_i_ekspresja/gra_na_gitarze/
    - assets/spraw/zhr_harc_c/muzyka_i_ekspresja/gra_na_instrumentach/
    - assets/spraw/zhr_harc_c/muzyka_i_ekspresja/spiew/
    - assets/spraw/zhr_harc_c/muzyka_i_ekspresja/taniec/
    - assets/spraw/zhr_harc_c/muzyka_i_ekspresja/aktorstwo_i_teatr/

    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/krajoznawstwo_i_wedrowanie/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/jazda_na_rowerze/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/plywanie/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/kajakarstwo/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/zeglarstwo/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/sporty_zespolowe/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/bieganie/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/akrobatyka/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/wspinaczka/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/narty_i_snowboard/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/lyzwiarstwo/
    - assets/spraw/zhr_harc_c/sport_turystyka_i_krajoznawstwo/strzelectwo/

    - assets/spraw/zhr_harc_c/sztuka_i_technika/rzemioslo_techniczne/
    - assets/spraw/zhr_harc_c/sztuka_i_technika/elektrotechnika/
    - assets/spraw/zhr_harc_c/sztuka_i_technika/programowanie/
    - assets/spraw/zhr_harc_c/sztuka_i_technika/rzemioslo_plastyczne/
    - assets/spraw/zhr_harc_c/sztuka_i_technika/fotografia/
    - assets/spraw/zhr_harc_c/sztuka_i_technika/film_i_kino/
    - assets/spraw/zhr_harc_c/sztuka_i_technika/hodowla/
    - assets/spraw/zhr_harc_c/sztuka_i_technika/ogrodnictwo/
    - assets/spraw/zhr_harc_c/sztuka_i_technika/gotowanie/

    - assets/spraw/zhr_harc_c/nauka_i_kultura/nauka/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/obserwacja_nieba/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/badanie_swiata/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/kronikarstwo_i_historia/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/literatura/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/lingwistyka/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/komunikacja/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/obywatelstwo/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/kolekcjonerstwo/
    - assets/spraw/zhr_harc_c/nauka_i_kultura/gry/

    - assets/spraw/zhr_harc_c/duch_i_charakter/rozwaga/
    - assets/spraw/zhr_harc_c/duch_i_charakter/dzielnosc/
    - assets/spraw/zhr_harc_c/duch_i_charakter/sluzba_liturgiczna/
    - assets/spraw/zhr_harc_c/duch_i_charakter/slowo_boze/
    - assets/spraw/zhr_harc_c/duch_i_charakter/ogien_ducha/

    - assets/trumpet/
    - assets/locale/

  fonts:
    - family: Gentium
      fonts:
        - asset: fonts/GentiumBasic/GentiumBasic-Regular.ttf
          weight: 300
        - asset: fonts/GentiumBasic/GentiumBasic-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/GentiumBasic/GentiumBasic-Bold.ttf
          weight: 700
        - asset: fonts/GentiumBasic/GentiumBasic-BoldItalic.ttf
          weight: 700
          style: italic

    - family: PlayfairDisplay
      fonts:
        - asset: fonts/PlayfairDisplay/PlayfairDisplay-Regular.ttf
          weight: 300
        - asset: fonts/PlayfairDisplay/PlayfairDisplay-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/PlayfairDisplay/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: fonts/PlayfairDisplay/PlayfairDisplay-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Regular.ttf
          weight: 300
        - asset: fonts/Lato/Lato-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/Lato/Lato-Bold.ttf
          weight: 700
        - asset: fonts/Lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather/Merriweather-Regular.ttf
          weight: 300
        - asset: fonts/Merriweather/Merriweather-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/Merriweather/Merriweather-Bold.ttf
          weight: 700
        - asset: fonts/Merriweather/Merriweather-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-B.ttf
          weight: 900
        - asset: fonts/Ubuntu-BI.ttf
          weight: 900
          style: italic
        - asset: fonts/Ubuntu-M.ttf
          weight: 700
        - asset: fonts/Ubuntu-MI.ttf
          weight: 700
          style: italic
        - asset: fonts/Ubuntu-R.ttf
          weight: 500
        - asset: fonts/Ubuntu-RI.ttf
          weight: 500
          style: italic
        - asset: fonts/Ubuntu-L.ttf
          weight: 300
        - asset: fonts/Ubuntu-LI.ttf
          weight: 300
          style: italic
        - asset: fonts/Ubuntu-Th.ttf
          weight: 100

    - family: Museo
      fonts:
        - asset: fonts/museo300.ttf
          weight: 300
        - asset: fonts/museo700.ttf
          weight: 700
        - asset: fonts/museo900.ttf
          weight: 900

    - family: Amarante
      fonts:
        - asset: fonts/Amarante-Regular.ttf
          weight: 300

    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 300

    - family: Hand0
      fonts:
        - asset: fonts/hand_annie.ttf
          weight: 300

    - family: Hand1
      fonts:
        - asset: fonts/hand_dekko.ttf
          weight: 300

    - family: Hand2
      fonts:
        - asset: fonts/hand_caveat-R.ttf
          weight: 300
        - asset: fonts/hand_caveat-B.ttf
          weight: 700

    - family: Hand3
      fonts:
        - asset: fonts/hand_cedarville_cursive.ttf
          weight: 300

    - family: Hand4
      fonts:
        - asset: fonts/hand_architects_daughter.ttf
          weight: 300

    - family: Hand5
      fonts:
        - asset: fonts/hand_gloria_hallelujah.ttf
          weight: 300

    - family: Hand6
      fonts:
        - asset: fonts/hand_grand_hotel.ttf
          weight: 300

    - family: Hand7
      fonts:
        - asset: fonts/hand_havana.ttf
          weight: 300

    - family: Hand8
      fonts:
        - asset: fonts/hand_kalam-L.ttf
          weight: 100
        - asset: fonts/hand_kalam-R.ttf
          weight: 300
        - asset: fonts/hand_kalam-B.ttf
          weight: 700

    - family: Hand9
      fonts:
        - asset: fonts/hand_marck_script.ttf
          weight: 300

    - family: Hand10
      fonts:
        - asset: fonts/hand_montez.ttf
          weight: 300

    - family: Hand11
      fonts:
        - asset: fonts/hand_reenie_beanie.ttf
          weight: 300

    - family: Hand12
      fonts:
        - asset: fonts/hand_sacramento.ttf
          weight: 300

    - family: Hand13
      fonts:
        - asset: fonts/hand_scriptina_pro.otf
          weight: 300

    - family: Hand14
      fonts:
        - asset: fonts/hand_shadows_into_light.ttf
          weight: 300

    - family: Hand15
      fonts:
        - asset: fonts/hand_trypewriter.ttf
          weight: 300

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
