import 'package:tuple/tuple.dart';

const TAG_AK = '#AK';
const TAG_OJCOWIE_NIEPODLEGLOSCI = '#OjciecNiepodleglości';
const TAG_POWSTANIEC_WARSZAWY = '#PowstaniecWarszawy';
const TAG_SCOUT_HARC = '#SkautHarc';

const String BP_NAME = 'gen. Robert Baden-Powell';

const List<ItemData> DATA = [
  ItemData(
    name: BP_NAME,
    fullName: 'gen. Lord Robert Stephenson Smyth Baden-Powell',
    tag: [TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_baden_powell_1', ''),
      Tuple2('bio_baden_powell_2', '')
    ],
    dateBirth: '22 lutego <b>1857 r.</b>, Londyn (Anglia)',
    dateDeath: '8 stycznia <b>1941 r.</b>, Nyeri (Kenia)',
    shortDesc: 'Brytyjski wojskowy, generał, porucznik, pisarz i założyciel skautingu. Naczelny Skaut Świata.',
    longDesc: 'Baden-Powell urodził się w brytyjskim Londynie, w dzielnicy Paddington. Jego ojciec, wielebny Baden Powell, był księdzem anglikańskim oraz profesorem geometrii na Uniwersytecie Oxford, a matką wnuczka admirała Horacego Nelsona, Henrietta Grace Smyth.'
        '\n\nKarierę wojskową rozpoczął w 1876 roku jako zwykły żołnierz. Służył w Anglii, Indiach, Afganistanie i Afryce Południowej. Do jego głównych osiągnięć należy, trwająca 7 miesięcy, <b>obrona miasta Mafeking</b> w latach 1899-1900 podczas wojny przeciwko Burom. Podczas obrony stworzył on <b>oddział chłopców</b>, którzy uczestniczyli w służbie pomocniczej jako łącznicy czy wartownicy. Podczas tego eksperymentu zauważył on, że można powierzyć młodym osobom odpowiedzialne zadania pod warunkiem poważnego traktowania ich.'
        '\n\nW 1902 roku Bi-Pi wraca do Wielkiej Brytanii i obserwuje duże zainteresowanie swoją książką "Aids to scouting" (Wskazówki do wywiadów) wśród młodzieży. W 1903 roku zostaje generalnym inspektorem kawalerii brytyjskiej. W 1907 roku postanawia zorganizować <b>obóz dla chłopców na wyspie Brownsea</b>, gdzie sprawdza skuteczność swoich metod, m.in. systemu zastępów. Postanawia także na stałe zająć się pracą wychowawczą wśród młodych chłopców. W 1908 roku wydaje książkę <b>"Scouting for Boys"</b> ("Skauting dla chłopców"). W 1910 roku pod wpływem dużego zainteresowania tematyką książki wśród młodzieży Bi-Pi kończy swoją służbę wojskową w stopniu generała i poświęca się skautingowi. W ciągu roku do jego organizacji przystępuje 100 tysięcy członków. W 1909 roku rozpoczyna swą działalność ruch skautek - dziewcząt. W 1910 roku Robert Baden-Powell prosi o pomoc w prowadzeniu żeńskiej organizacji swoją siostrę, Agnes. W 1912 roku Baden-Powell bierze ślub z Olave St. Clair Soames.'
        '\n\nW 1920 roku skauci podczas pierwszego Jamboree obierają Roberta Baden-Powella Naczelnym Skautem Świata. Podczas emerytury Bi-Pi zajmuje się szkoleniem armii terytorialnej Wielkiej Brytanii. Za pracę ze skautami otrzymał wiele nagród i wyróżnień, m.in. tytuł lorda - barona Gilwell oraz Krzyż Komandorski z Gwiazdą Orderu "Polonia Restituta". W posiadłości Gilwell Park zorganizowano międzynarodowy ośrodek skautowy. Bi-Pi zmarł w Kenii, 8 stycznia 1941 roku, gdzie od 1939 roku poddawał się leczeniu.',
    source: 'pl.wikibooks.org/wiki/Poradnik_harcerski/Robert_Baden-Powell',
  ),
  ItemData(
    name: 'Olave Baden Powell',
    tag: [TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_olave_baden_powell_1', ''),
      Tuple2('bio_olave_baden_powell_2', '')
    ],
    dateBirth: '22 lutego <b>1889 r.</b>, Chesterfield (Anglia)',
    dateDeath: '19 czerwca <b>1977 r.</b>',
    shortDesc: 'Naczelna przewodniczka (skautka) świata, od 1916 naczelniczka brytyjskich przewodniczek (skautek), żona założyciela skautingu, Roberta Baden-Powella.',
    longDesc: 'Olave była trzecią i najmłodszą córką właściciela browaru i artysty Harolda Soamesa. Wychowywana była w domu przez ojca, matkę – Katharine (z domu Hill) oraz guwernantki. Uprawiała wiele dyscyplin sportowych, między innymi tenis, pływanie, piłkę nożną, jazdę na łyżwach i kajakarstwo. Grała także na skrzypcach. Rodzina Olave Soames wielokrotnie zmieniała miejsce zamieszkania (17 razy w ciągu pierwszych 23 lat życia Olave).'
        '\n\nW styczniu 1912, Olave spotkała bohatera drugiej wojny burskiej oraz założyciela skautingu, <b>Roberta Baden-Powella</b> na statku RMSP Arcadian, który był w drodze do Nowego Jorku żeby tam rozpocząć jeden z „Scouting World Tours”.'
        '\n\nW momencie poznania Roberta Baden-Powella miała 23 lata. Robert Baden-Powell miał 55 lat. Ciekawostką był fakt, że <b>obchodzili urodziny tego samego dnia</b>. Zaręczyli się we wrześniu tego samego roku, powodując medialną sensację. Aby uniknąć prasy, pobrali się w sekrecie 30 października 1912.'
        '\n\n„The Scouts and Guides of England” w prezencie ślubnym kupili młodej parze samochód (wbrew plotkom, nie był to Rolls-Royce prezentowany w 1929 roku). Zamieszkali w częściowo sfinansowanym przez ojca Olave domu „Pax Hill” niedaleko Bentley w hrabstwie Hampshire, gdzie żyli od 1918 do 1939 roku.'
        '\n\nW 1916 została <b>naczelniczką brytyjskich przewodniczek</b> (skautek). W 1930 wybrana <b>naczelną przewodniczką (skautką) świata</b>.'
        '\n\nBaden-Powellowie mieli trójkę dzieci, syna oraz dwie córki:'
        '\n- Arthur Robert Peter – drugi Baron Baden-Powell (1913–1962),'
        '\n- Heather Baden-Powell (1915–1986),'
        '\nBetty Baden-Powell (1917–2004)',
    source: 'pl.wikipedia.org/wiki/Olave_Baden-Powell',
  ),
  ItemData(
    name: 'Andrzej Małkowski',
    tag: [TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_malkowski', ''),
      Tuple2('bio_malkowscy', '')
    ],
    dateBirth: '31 października <b>1888 r.</b>, Tręby k. Kutna (Polska)',
    dateDeath: '15/16 stycznia <b>1919 r.</b>',
    shortDesc: 'Jeden z twórców, wybitny instruktor i teoretyk harcerstwa, działacz polskich organizacji młodzieżowych i niepodległościowych.',
    longDesc: 'Pochodził z rodziny patriotycznej. Nauki pobierał w Warszawie, Tarnowie, Krakowie oraz Lwowie. W 1906 roku zdaje maturę w lwowskiej VI Szkole Realnej. Zostaje <b>współzałożycielem abstynenckiej organizacji "Młodzież"</b> działającej wśród krakowskich uczniów. W 1908 rozpoczyna studia na Wydziale Budowy Maszyn Politechniki Lwowskiej. W kwietniu 1910 przeniósł się na Uniwersytet Jana Kazimierza, jednak nie udaje mu się uzyskać wyższego wykształcenia. Był członkiem zarządu głównego "Eleuterii" oraz członkiem zwykłym "Eleusis", "Zarzewia" i "Sokoła",'
        '\n\nW listopadzie 1909 roku <b>rozpoczyna, za karę, tłumaczenie książki Roberta Baden-Powella "Skauting dla chłopców" ("Scouting for Boys")</b>. Małkowski staje się entuzjastą skautingu.'
        '\n\nOd 20 marca do 21 maja 1911 roku odbywa się pierwszy kurs skautowy. Małkowski omawia na nim napisaną przez siebie książkę "Scouting jako system wychowania młodzieży" ukazującą się w formie arkuszy od kwietnia do lipca 1911 roku. Zostaje także członkiem składu Komendy Skautowej, a następnie Naczelnej Komendy Skautowej we Lwowie. Od 1911 roku wydaje <b>czasopismo "Skaut"</b>. W 1912 roku wyjechał do Londynu w celu zebrania materiałów do nowego wydania książki. Po powrocie odsunięto go od pracy w "Skaucie" i Naczelnej Komendzie Skautowej. W 1913 roku Małkowski organizuje wyjazd polskich skautów na III Wszechbrytyjski Zlot Skautów. Nad polskim obozem powiewa flaga z białym orłem. Powszechnie używa się nazwy kraju wymazanego z map politycznych świata. BiPi nagradza Małkowskiego medalem "Za zasługi".'
        '\n\nW 1913 roku przenosi się do Zakopanego, gdzie żeni się z <b>Olgą Drahonowską</b>. Tworzy tam niezależny ośrodek harcerski. Podczas wojny <b>wstępuje do Legionów Polskich</b>. Zniechęcony związkami Legionów z Austrią występuje z nich po dość krótkim okresie. Próbuje utworzyć niepodległą Rzeczpospolitą Podhalańską, w wyniku czego musi wyemigrować z Zakopanego. Najpierw wybiera Anglię, później USA, gdzie zakłada polskie drużyny skautowe. Od września 1915 roku przez rok pełni funkcję skautmistrza związkowego w Związku Sokołów Polskich w Ameryce. Próbuje zorganizować oddziały do walki z Niemcami. Władze związku są przeciwne pomysłowi, przez co Małkowski wyjeżdża do Kanady, gdzie w 1916 roku wstępuje do wojska. W styczniu kolejnego roku rozpoczyna trzymiesięczną naukę w Wojskowej Szkole Piechoty. Służy na froncie we Francji w armii kanadyjskiej. W listopadzie 1918 roku zostaje przeniesiony do armii gen. Hallera. Wysłany do Odessy ginie w wyniku zatonięcia statku, na którym płynął w nocy z 15 na 16 stycznia 1919 roku.',
    source: 'pl.wikibooks.org/wiki/Poradnik_harcerski/Andrzej_Juliusz_Małkowski',
  ),
  ItemData(
    name: 'Olga Drahonowska Małkowska',
    tag: [TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_olga_drahonowska_malkowska_1', ''),
      Tuple2('bio_olga_drahonowska_malkowska_2', ''),
      Tuple2('bio_malkowscy', '')
    ],
    dateBirth: '1 września <b>1888 r.</b>, Krzeszowice (Polska)',
    dateDeath: '15 stycznia <b>1979 r.</b>, Zakopane (Polska)',
    shortDesc: 'Jedna z twórczyń polskiego skautingu, instruktorka harcerska, współautorka hymnu harcerskiego, założycielka szkół instruktorskich.',
    longDesc: 'Urodzona w Krzeszowicach 1 września 1888 roku. Córka Zofii, czeskiej mieszczanki i Karola, zarządcy dóbr hrabiego Potockiego w Małopolsce. Szkołę kończyła zdając tylko kolejne egzaminy w Krakowie. Po maturze wstąpiła do Konserwatorium Muzycznego we Lwowie, gdzie odkryła swój talent poetycki i rzeźbiarski. Interesowała się sportem, była instruktorką w "Sokole", działała w "Eleusis", a później, za namową Małkowskiego w "Zarzewiu", gdzie zdobyła stopień porucznika.'
        '\n\nLatem 1911 roku we Lwowie <b>zakłada pierwszą żeńską drużynę harcerską</b> oraz zostaje komendantką w Naczelnej Komendzie Skautowej do 1912 roku. W marcu 1912 roku na I Zjeździe we Lwowie harcerstwo staje się organizacją abstynencką. Po tym wydarzeniu zostaje wybrana w skład Zarządu Oddziału lwowskiego Eleuterii-Wyzwolenia. Druhna Olga <b>współtworzyła także hymn ZHP</b>. We wrześniu 1912 roku w czasopiśmie "Skaut" ukazał się oparty na melodii "Na barykady ludu roboczy" wierz "Marsz skautów" autorstwa Ignacego Kozielewskiego. Za zgodą autora Małkowska dokonała drobnych zmian w utworze, który <b>stał się później hymnem</b>.'
        '\n\nW 1913 roku udała się na leczenie do Zakopanego, gdzie wzięła ślub z Andrzejem Małkowskim. Ceremonię poprowadził <b>ksiądz Kazimierz Lutosławski</b>, projektant krzyża harcerskiego. Po wyleczeniu nacieku w płucu <b>Małkowska rozpoczęła działalność harcerstwa żeńskiego we Lwowie</b>. Od momentu, gdy Andrzej Małkowski wyruszył na I wojnę światową prowadziła również drużynę męską. Podczas wojny zorganizowała także: skautową pocztę, pomoc żniwną dla góralek, ochronkę dla opuszczonych dzieci, tanią jadłodajnię dla ubogiej ludności i skautową straż porządkową pełniącą nocną służbę. Udało się jej stworzyć w Dolinie Kościeliskiej, na Hali Pysznej, w Dolinie Roztoki, w Murzasichlu i w grotach Nosala <b>tajne składy broni</b>, które jednak zostały wykryte przez policję austriacką w 1915 roku, po ogłoszeniu przez druha Małkowskiego niepodległości Republiki Podhalańskiej, która miała być początkiem państwa polskiego. Małkowscy musieli udać się na emigrację.'
        '\n\nWybierają Stany Zjednoczone, gdzie 30 października 1915 roku na świat przychodzi ich syn, Lutyk. Po roku Olga wraca z nim do Europy. W lutym 1917 roku, pod wpływem niepowodzenia planu utworzenia polskiego Legionu w Kanadzie przenosi się z Francji do Szwajcarii. Poczta neutralnego kraju odmawia dostarczania żołdu Małkowskiego, przez co Olga podejmuje pracę fizyczną w gospodarstwie ogrodniczym w Chexbres Village. Od końca 1917 roku <b>uczy muzyki</b> w Ecole Nouvelle, a od 1918 roku w londyńskiej szkole, którą złożyła na prośbę Polish Relief Found.'
        '\n\nPo pewnym czasie znajduje pracę jako kustosz zbiorów w Torquay, które były przeznaczone dla Polski, gdy ta odzyska niepodległość. Uczy muzyki i wychowania fizycznego, organizuje drużyny skautów i wilcząt. W listopadzie 1921 <b>wraca do Zakopanego</b>. W międzyczasie w wyniku zatonięcia statku ginie Andrzej Małkowski. Druhna Olga uczy angielskiego i gimnastyki w Szkole Gospodarstwa Domowego. <b>Prowadzi kursy języka, historii i kultury polskiej dla Ślązaczek</b>. W 1922 roku <b>początkuje działalność szkoły instruktorek ZHP</b> w Kuźnicach. W 1924 roku pełniła funkcję komendantki Zlotu Harcerek w Świdrze pod Warszawą, a później polskiej delegacji na III Światową konferencję skautek w Foxlease w Anglii. Rok później zakłada Szkołę Pracy Instruktorskiej i Pracy Harcerskiej w Sromowcach Wyżnych, którą kieruje do 1939 roku. W 1927 roku zostaje nadany jej stopień harcmistrzyni Rzeczpospolitej. Latem 1931 Olga Małkowska kierowała w Sromowcach pierwszym obozem żeńskim Studium W-F Uniwersytetu Jagiellońskiego. W 1932 r. prowadziła VII światową konferencję skautek na Buczu, gdzie wybrana została do Komitetu Światowego Skautek. Dwa lata później dostaje zadanie wizytacji skautek w Czechosłowacji, Austrii i Rumunii oraz zostaje delegatką w Komitecie Opieki nad Dziećmi i Młodzieżą w Lidze Narodów. W międzyczasie zdobywa odznaczenia państwowe: Krzyż Oficerski Orderu Polonia Restituta oraz Krzyż Niepodległości '
        '\n\n<b>W 1939 roku uchodzi z kraju do Wielkiej Brytanii</b> w obawie, przed prześladowaniami ze strony gestapo. Zakłada Dom Dziecka Polskiego, który zostaje później przeniesiony do Szkocji do posiadłości Castlemains koło Douglas w Lanarkshire. Powstaje tam szkoła, gimnazjum, harcerstwo oraz ośrodek urlopowy dla żołnierzy. W 1942 roku zostaje przewodniczącą Komitetu Naczelnego ZHP na czas wojny. Organizuje Guides International Service - skautową służbę pomagającą dzieciom na terenach wyzwalanych spod panowania hitlerowskiego.'
        '\n\nPo wojnie, w latach 1948-1960 prowadziła kolejny Dom Dziecka Polskiego w w Hawson Court, posiadłości w Buckfastleigh, w Devon. W 1959 roku zorganizowała wycieczkę do Polski, a w 1961 wraca na stałe do kraju. Do 1964 roku mieszka we Wrocławiu, a później, na stałe, w Zakopanem, przy ul. Małe Żywczańskie 17A. W 1966 roku dostaje państwową rentę dla zasłużonych oraz Honorową Odznakę Przyjaciela Dziecka. Uczestniczyła także w odprawianej przez Karola Wojtyłę mszy świętej w rocznicę śmierci Małkowskiego.'
        '\n\nOlga Małkowska zmarła 15 stycznia 1979 roku. Pochowana została na zakopiańskim cmentarzu przy ulicy Nowotarskiej. Nad grobem postawiono pomnik autorstwa Henryka Berzeca.',
    source: 'pl.wikibooks.org/wiki/Poradnik_harcerski/Olga_Drahonowska-Małkowska',
  ),
  ItemData(
    name: 'bł. ks. Stefan Wincenty Frelichowski',
    tag: [TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_bl_wicek_1', ''),
      Tuple2('bio_bl_wicek_2', '')
    ],
    dateBirth: '22 stycznia <b>1913 r.</b>, Chełmża (Polska)',
    dateDeath: '23 lutego <b>1945 r.</b>, Dachau (Niemcy)',
    shortDesc: 'Ksiądz, podharcmistrz, harcerz Związku Harcerstwa Polskiego, błogosławiony katolicki, jeden z patronów diecezji toruńskiej oraz patron harcerzy polskich.',
    longDesc: 'Stefan urodził się 22 stycznia 1913 r. w Chełmży. Był dzieckiem wesołym, żywym, ciekawym świata i ludzi. Mając 11 lat pełnił służbę przy ołtarzu jako ministrant. W Chełmży ukończył szkołę podstawową i gimnazjum.'
        '\n\nBył czynnym harcerzem i członkiem Sodalicji Mariańskiej. 11 marca 1927 r. został przyjęty do 2. Pomorskiej Drużyny Harcerskiej im. Zawiszy Czarnego. 26 czerwca 1927 r. złożył Przyrzeczenie Harcerskie. W następnym roku został już drużynowym. Funkcję pełnił do sierpnia 1931 r. Doświadczenie jakie zdobył w harcerstwie, pomogło mu ukształtować własny światopogląd oraz umiejętność radzenia sobie w trudnych sytuacjach. Jesienią 1931 r. wstąpił do Wyższego Seminarium Duchownego w Pelplinie. Był to dla niego trudny czas formacji, jednak nie poddał się i wytrwał w dążeniu do celu, jakim było kapłaństwo. W swoim pamiętniku pisze: <i>"Boże, chcę być naprawdę kapłanem"</i>. W latach 1933-1936 pełnił funkcję drużynowego Starszoharcerskiego Zrzeszenia Kleryków w Pelplinie. W marcu 1937 r. przyjmuje święcenia kapłańskie. Rok później został wysłany jako wikariusz do parafii pw. Wniebowzięcia Najświętszej Maryi Panny w Toruniu. Tam odnalazł się jako duszpasterz młodzieży oraz pełnił funkcję kapelana Pomorskiej Chorągwi Harcerzy.'
        '\n\nW przededniu wybuchu II wojny światowej uczestniczył w Pogotowiu Harcerek i Harcerzy. Tuż po wkroczeniu armii hitlerowskiej do Polski zostaje aresztowany, lecz po kilku dniach go zwolniono. 18 października był ponownie aresztowany i osadzony w więzieniu gestapo tzw. Forcie VII w Toruniu. W więzieniu mimo zakazu celebrował Msze św., słuchał spowiedzi oraz organizował dyskusje patriotyczne. W styczniu 1940 r. został przeniesiony do obozu pracy w Gdańskim Nowym Porcie. Następnie wywieziono go do obozu koncentracyjnego w Stutthofie. W święta wielkanocne roku 1940 potajemnie zdobył hostię i wino mszalne, by zorganizować liturgię Wielkiego Czwartku. W IV tego samego roku przeniesiono go do obozu koncentracyjnego Sachsenhausen-Oranienburg pod Berlinem. Po ośmiu miesiącach ostatecznie przewieziono go do obozu w Dachau, gdzie otrzymał numer obozowy 22492. Podczas całej obecności w obozie pełnił służbę duszpasterską, organizował pomoc żywnościową, a gdy w 1944 r. wybuchła epidemia tyfusu plamistego, mimo najsurowszych zakazów śpieszył z pomocą chorym. Na początku 1945 r. sam zaraził się chorobą i zmarł w opinii świętości 23 lutego 1945 r.'
        '\n\nJego śmierć była niesamowitym zdarzeniem w obozie. Władze Dachau pozwoliły na wystawienie zwłok. Cześć oddawali im nie tylko Polacy i nie tylko katolicy. Naoczny świadek wspomina: <i>"W milczeniu i w nabożnym, modlitewnym skupieniu przesuwał się przez kostnicę tłum więźniów. Szli młodzi i starzy. Szli Polacy i cudzoziemcy. Znali go wszyscy. Odszedł kochany, święty kapłan. Odszedł człowiek, który życie swe złożył na ołtarzu miłości i miłosierdzia względem bliźniego i jego nieśmiertelnej duszy”</i>.'
        '\n\nPrzed kremacją Stanisław Bieńka zdjął z twarzy pośmiertną maskę, w której zagipsował jeden z palców prawej ręki. Drugi palec, zagipsowany, zachował ks. Bernard Czapliński.'
        '\n\nJego historia jednak nie kończy się na śmierci. Po wojnie rozpoczęto starania o proces beatyfikacyjny. Oficjalnie został on otwarty w 1964 r. w Pelplinie. 7 czerwca 1999 r. w Toruniu papież Jan Paweł II beatyfikował ks. Stefana Wincentego Frelichowskiego, a w dwa lata później na wniosek środowisk harcerskich został ogłoszony przez Kongregację ds. Kultu Bożego i Dyscypliny Sakramentów patronem harcerstwa.',
    source: 'Propozycja programowa dla gromad i drużyn ZHP pod redakcją Piotra Dziewulskiego “Święci Skauci”',
  ),
  ItemData(
    name: 'ks. Kazimierz Lutosławski',
    tag: [TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_lutoslawski_1', ''),
      Tuple2('bio_lutoslawski_2', '')
    ],
    dateBirth: '4 marca <b>1880 r.</b>, Drozdów (Polska)',
    dateDeath: '5 styczeń <b>1924 r.</b>, Drozdów (Polska)',
    shortDesc: 'Ksiądz katolicki, działacz endecki, poseł na sejm, główny projektant krzyża harcerskiego.',
    longDesc: 'Pochodził z rodziny ziemiańskiej. Początkowo uczył się w domu, lecz szkołę średnią szkończył w Rydze. Medycynę studiował w Zurychu, gdzie był także komendantem gniazda towarzystwa "Sokół". Po studiach wyjechał do Wielkiej Brytanii, gdzie podjął naukę w zawodzie, a także kontynuował naukę, tym razem w Szkole Nauk Politycznych oraz fizykę.'
        '\n\nLondyn to także jego pierwszy kontakt ze skautingiem. W 1905 roku zachorował na gruźlicę. Podczas leczenia się w zakładzie dr Tarnowskiego w Kosowie <b>zakłada wakacyjną drużynę “Dzieci Kosowskich"</b> na wzór drużyn skautowych, a w 1907 roku <b>tworzy czteroletnie Ognisko Wychowawcze Wiejskie w Starej Wsi</b>, w programie którego dużo było elementów metodyki skautowej.'
        '\n\nW 1909 roku Lutosławski podejmuje <b>decyzję o zostaniu księdzem</b>, święcenia otrzymuje 23 czerwca 1912 roku. Później podejmuję stałą służbę harcerską, jako instruktor i kapelan skautowy. Kończy trzyletnie studia filozoficzne i teologiczne. W 1911 roku w czasie wakacji zakłada w Drozdowie dwa zastępy: "Kruki" i "Czajki" zrzeszające dzici rodziny Lutosławskich i ich przyjaciół. Pod koniec 1911 roku dają one początek zastępom tworzonym przez Lutosławskiego warszawskim drużynom skautowym przy szkole E. Konopczyńskiego. W tym samym roku, 15 października zostaje ogłoszony konkurs na polską odznakę skautową. W 1912 Małkowski projektuje Krzyż Harcerski, który w konkursie zajmuje 3 miejsce. Żadna z prac nie zostaje wprowadzona w życie, a pod koniec 1912 roku Naczelna Komisja Skautowa <b>wyznacza do dalszych prac nad odznaką właśnie Lutosławskiego</b>. Krzyż Harcerski wchodzi do użytku w 1912 roku. Ostateczny kształ odznaki zostaje zatwierdzony podczas konferencji ZHP 1-2 listopada 1918 roku.'
        '\n\nW 1913 roku w Zakopanem <b>udziela ślubu Andrzejowi Małkowskiemu i Oldze Drahonowskiej</b>. W 1914 roku we Frymburgu broni doktoratu z teologii. Do tego roku był także członkiem Naczelnej Komendy Skautowej w Królestwie Polskim. Ustępuje z niej na skutek rozłamu w warszawskim skautingu. Przyczyną rozłamu jest krytyka powstań narodowych oraz czynu zbrojnego Legionów Polskcih Piłsudskiego przez Lutosławskiego. Ksiądz opowiada się ponadto za współpracą z Rosją. Krytykujący go drużynowi zostają zdegradowani, przez co dochodzi do rozłamu. 13 drużyn zbuntowanych przeciwko NKS zakłada Wydział Rady Drużynowych. Rozłam został zażegnany po ugodzie w 1915 roku i ustąpieniu Lutosławskiego z NKS.'
        '\n\nPonowny konflikt nastąpił po zajęciu Warszawy przez Niemców. Ponownie wznowiły się dyskusje nad prorosyjskim nastawieniem NKS. Ostatecznie rozłam udało się zażegnać 2 maja 1916 roku. Lutosławski był także politykiem ruchu narodowo-demokratycznego i współpracownikiem R. Dmowskiego. Podczas I Wojny Światowej przebywa w Rosji, gdzie organizuje szkołę średnią oraz zostaje kapelanem Brygady Strzelców Polskich. Współpracuje z prawicowymi mediami: "Gazetą Polską", "Sprawą Polską", "Wygnańcem", gazetą "Polak-katolik". Po wojnie zostaje członkiem Głównego Zjednoczenia Ludowo-Narodowego. Bierze udział w Konferencji Zjednoczeniowej ZHP. Pracował nad projektem statutu ZHP oraz <b>projektem Prawa i Przyrzeczenia Harcerskiego</b>. Później wydał książki pt.: "Czuj Duch, Jak prowadzić pracę skautów" oraz "Śpiewnik polskiego skauta". Swoje prace podpisywał jako x. Jan Zawada lub "Szary". Współpracuje z "Gazetą Warszawską", "Myślą Narodową", "Harcerzem". '
        '\n\n<b>Podczas wojny polsko-bolszewickiej zostaje kapelanem</b>. W 1922 roku zostaje odznaczony Krzyżem Walecznych. W latach 1919-1922 <b>poseł na Sejm Ustawodawczy</b>, podczas którego był przewodniczącym Sejmowej Komisji Konstytucyjnej. Później poseł na Sejm I i II kadencji. Przeciwnik Piłsudskiego oraz Gabriela Narutowicza. Po morderstwie tego ostatniego oskarżany o namawianie do zbrodni. Przez lewicę i zwolenników Piłsudskiego krytykowany był za szerzenie antysemityzmu. Zmarł 5 stycznia 1924 roku w wyniku szkarlatyny. Pochowany w rodzinnym Drozdowie. <b>Pośmiernie uhonorowany stopniem Harcerza Rzeczypospolitej</b> przez Naczelnictwo ZHP, za zasługi dla harcerstwa.'
        '\n\nW 1994 roku w jego płytę grobową wmurowano kopię krzyża harcerskiego. Od 1995 roku odbywają się coroczne Zloty dh. Kazimierza Lutosławskiego "Szarego" w pierwszych dniach marca, dla uczczenia jego rocznicy urodzin.',
    source: 'pl.wikibooks.org/wiki/Poradnik_harcerski/Kazimierz_Lutosławski',
  ),
  ItemData(
    name:'Jan Bytnar "Rudy"',
    tag: [TAG_AK, TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_jan_bytnar_rudy_1', ''),
      Tuple2('bio_jan_bytnar_rudy_2', ''),
      Tuple2('bio_jan_bytnar_rudy_3', ''),
      Tuple2('bio_jan_bytnar_rudy_4', 'Zdjęcie z kenkarty – jedna z ostatnich fotografii Bytnara')
    ],
    dateBirth: '6 maja <b>1921 r.</b>, Kolbuszowa (Polska)',
    dateDeath: '30 marca <b>1943 r.</b>, Warszawa (Polska)',
    shortDesc: 'Pseudonim "Rudy", "Czarny", "Janek", "Krokodyl". Instruktor w stopniu harcmistrza, podporucznik AK.',
    longDesc: 'Był synem Zdzisławy i Stanisława, byłego żołnierza Legionów Polskich. W 1925 roku wraz z rodzicami przeprowadził się do Warszawy. Uczył się w Państwowym Gimnazjum im. Stefana Batorego. W wieku 12 lat wstąpił do 23 WDH "Pomarańczarnia" im. Bolesława Chrobrego. W 1936 roku został przybocznym. W 1938 roku zdobywa stopień HR.'
        '\n\nOd jesieni 1939 roku wraz ze swoją drużyną włącza się w działania organizacji PLAN. Od połowy 1940 roku pracuje jako łącznik PLAN z osadzonymi w więzieniu przy Alei Szucha oraz przy ul. Daniłowiczowskiej w Warszawie. Podczas wojny otrzymuje stopień podharcmistrza oraz kończy Szkołę Podchorążych Piechoty Rezerwy "Agricola". Od wiosny 1941 roku dowodzi hufcem "Ochota" w Warszawie, który działa w ramach organizacji małego sabotażu "Wawer". Podczas działań Bytnar zerwał hitlerowską flagę z budynku Zachęty oraz namalował kotwicę PW" na Pomniku Lotnika w Warszawie. W listopadzie 1942 roku obejmuje dowództwo nad hufcem SAD Grup Szturmowych. Uczestniczy w akcjach GS, m.in. w noc sylwestrową z 1942 na 1943 rok w akcji Wieniec II, której celem było wysadzenie pociągu z transportami broni dla Niemców. 2 lutego 1943 roku został ranny podczas starć z niemiecką policją. 17 marca uciekł po linie z mieszkania położonego na II piętrze, by uchronić się przed mającym nastąpić aresztowaniem.'
        '\n\n23 marca 1943 roku Gestapo znajduje w piwnicy budynku, w którym mieszkał przy al. Niepodległości 159, wiele materiałów polskiego podziemia, które nie zostały usunięte z niego na czas po aresztowaniach w dzielnicy Praga innego dowódcy Grup Szturmowych. 26 marca zostaje odbity przez GS podczas <b>Akcji pod Arsenałem</b>. Umiera 4 dni później, przez obrażenie odniesione podczas przesłuchań. Podczas śledztwa nie zdradza żadnej tajemnicy podziemia. Jako bezpośrednich sprawców śmierci wywiad AK zidentyfikował Huberta Schulza i Ewalda Lange. Obaj zostają straceni w wyniku wyroku sądu podziemnego.'
        '\n\nPo śmierci zostaje odznaczony Krzyżem Walcznych. Otrzymuje również stopień harcmistrza i podporucznika. Grób Bytnara znajduje się na Powązkach Wojskowych w Warszawie.',
    source: 'pl.wikibooks.org/wiki/Poradnik_harcerski/Jan_Bytnar',
  ),
  ItemData(
    name: 'Maciej Aleksy Dawidowski "Alek"',
    tag: [TAG_AK, TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_aleksander_dawidowski_alek_1', ''),
      Tuple2('bio_aleksander_dawidowski_alek_2', ''),
      Tuple2('bio_aleksander_dawidowski_alek_3', 'W czasie zajęć w Państwowej Szkole Budowy Maszyn')
    ],
    dateBirth: '3 listopada <b>1920 r.</b>, Drohobycz (Polska)',
    dateDeath: '30 marca <b>1943 r.</b>, Warszawa (Polska)',
    shortDesc: 'Pseudonim "Alek", "Glizda", "Kopernicki", "Koziorożec". Instruktor harcerski w stopniu podharcmistrza, podporucznik Armii Krajowej.',
    longDesc: 'Syn Aleksego, inżyniera technologa i Janiny z Sagatowskich, inżyniera chemika. Podczas nauki w warszawskim Gimnazjum im. Stefana Batorego zostaje członkiem 23 WDH "Pomarańczarnia" im. Bolesława Chrobrego. W 1939 roku kończy szkołę. Podczas nauki uzyskuje stopień Harcerza Orlego.'
        '\n\n8 września 1939 roku, po wybuchu II Wojny Światowej, wyrusza wraz ze swoją drużyną z Warszawy na wschód. Wyprawą dowodzi komendant "Pomarańczarni" harcmistrz Lechosław Domański "Zeus". Harcerze na początku października wracają do stolicy. Od tego momentu do grudnia Alek zostaje członkiem organizacji PLAN i bierze udział w jej akcjach <b>Małego Sabotażu</b>.'
        '\n\nOd początku 1940 roku działa jako łącznik w komórce więziennej ZWZ. Utrzymuje łączność między konspiracją a więzieniami: Pawiakiem i Daniłowiczowską, centralnym aresztem śledczym. W września 1940 rozpoczyna naukę w Państwowej Szkole Budowy Maszyn. Wiosną 1941 roku wstępuje do Szarych Szeregów. Obejmuje dowodzenie drużyną w hufcu "Mokotów Górny", kierowanym przez "Zośkę". Uczestniczy w działaniach Organizacji Małego Sabotażu "Wawer". Wykonuje wiele odważnych akcji. 11 lutego 1942 <b>zdejmuje niemiecką tablicę "Dem Grossen Deutschen Astronomen", przykrywającą polski napis "Mikołajowi Kopernikowi – Rodacy"</b>, z pomnika astronoma. W odwecie Niemcy nakazali demontaż pomnika płk Jana Kilińskiego, stojącego przy pl. Krasińskich. Dawidowski znalazł później miejsce ukrycia pomnika. Okazało się, że znalazł się on na terenie Muzeum Narodowego. Już następnego dnia przechodnie mogli przeczytać na jego musze napis "Jam tu Ludu W-wy. Kiliński Jan" autorstwa "Alka". W nagrodę nadany zostaje mu honorowy pseudonim "Kopernicki".'
        '\n\nOd kwietnia do września 1942 roku ukrywa się w Olesinku koło Góry Kalwarii. Po utworzeniu Grup Szturmowych dowodzi 1. drużyną hufca GS "Południe", którym kierował "Rudy". W 1942 roku przechodzi kursu podharcmistrzowski "Szkoły za lasem" i zostaje mianowany podharcmistrzem. Otrzymuje ps. Instruktorski "Koziorożec". W 1943 roku uczestniczy w Zastępczym Kursie Szkoły Podchorążych Rezerwy Piechoty zorganizowanym przez AK. Bierze udział w akcjach rozbrojeniowych oraz akcji "Bracka", podczas której ewakuje mieszkanie przy ul. Brackiej 23. 23 marca 1943, po aresztowaniu "Rudego" pełni funkcję komendanta Hufca "Mokotów Górny" GS.'
        '\n\n26 marca 1943 roku, podczas <b>Akcji pod Arsenałem</b> dowodzi sekcją "Granaty" w grupie "Atak". Podczas akcji postrzelił idącego z północy oficera SS. Ciężko ranny w brzuch zostaje ewakuowany zarekwirowanym samochodem. Podczas pościgu rzuca granat w kierunku niemieckiej, wojskowej ciężarówki. Później nie pojawiają się już inne problemy. Stan "Alka" staje się bardzo ciężki. Trafia do szpitala Dzieciątka Jezus, gdzie przechodzi operację. Tam 30 marca 1943 roku umiera.'
        '\n\nPośmiertnie odznaczony zostaje Srebrnym Krzyżem Orderu Virtuti Militari V klasy oraz awansowany do stopnia sierżanta podchorążego.',
    source: 'pl.wikibooks.org/wiki/Poradnik_harcerski/Maciej_Aleksy_Dawidowski',
  ),
  ItemData(
    name: 'Tadeusz Zawadzki "Zośka"',
    tag: [TAG_AK, TAG_SCOUT_HARC],
    imgSrc: [
      Tuple2('bio_tadeusz_zawadzki_zoska_1', ''),
      Tuple2('bio_tadeusz_zawadzki_zoska_2', '')
    ],
    dateBirth: '24 stycznia <b>1921 r.</b>, Warszawa (Polska)',
    dateDeath: '20 sierpnia <b>1943 r.</b>, Sieczyny (Polska)',
    shortDesc: 'Pseudonim "Kajman", "Kotwicki", "Lech Pomarańczowy", "Tadeusz", "Zośka". Instruktor harcerski w stopniu harcmistrza, podporucznik Armii Krajowej.',
    longDesc: 'Syn Józefa Zawadzkiego (profesora Politechniki Warszawskiej) i Leony (nauczycielki). Naukę rozpoczął w Szkole Ziemi Mazowieckiej. Później, we wrześniu 1933 roku przenosi się do Gimnazjum im. Stefana Batorego w Warszawie. Do klasy uczęszcza razem z <b>“Rudym”</b>, <b>“Alkiem”</b> i <b>Krzysztofem Kamilem Baczyńskim</b>. Od jesieni tego samego roku uczęszcza do 23 WDH “Pomarańczarnia” im. Bolesława Chrobrego. Maturę zdał w maju 1939 roku.'
        '\n\nPo wybuchu wojny wyrusza 6 września na wschód razem z harcerskim batalonem marszowym Chorągwi Warszawskiej. <b>Od 1939 roku działa w konspiracji</b>. Na przełomie 1939 i 1940 roku uczestniczy w akcjach małego sabotażu organizowanych przez Polską Ludową Akcję Niepodległościową. Od stycznia do lipca 1940 roku pełni funkcję łącznika w komórca więziennej Związku Walki Zbrojnej. W 1941 roku staje na czele “Wojennej Pomarańczarni” założonej przez środowisko 23 WDH. Razem ze swoją drużyną <b>wchodzi do “Szarych Szeregów”</b>, gdzie pełni komendę nad Hufcem “Mokotów Górny”. Hufiec włącza się w działania organizacji “Wawer”, w której Zawadzki pełni funkcję komendanta Obwodu „Mokotów Górny”. Zośka bierze udział w wielu akcjach <b>Małego Sabotażu</b>. W nagrodę za narysowanie największej liczby “kotwic” w swojej dzielnicy otrzymuje od Kamińskiego pseudonim “Kotwicki”. Uczestniczył również w akcji “N”, skierowanej do Niemców akcji propagandowej.'
        '\n\nNa przełomie maja i czerwca 1942 roku kończy kurs podharmistrzowski w “Szkole za Lasem”. 15 sierpnia 1942 roku otrzymuje stopień i pseudonim instruktorski “Kajman”. 13 września 1942 roku Zośka zarządza dla swojego hufca manewry w Lasach Chojnowskich pod Warszawą. W listopadzie 1942 roku zostaje hufcowym w hufcu “Centrum”, dowódcą Grup Szturmowych Chorągwi Warszawskiej i zastępcą zastępcą por. “Jerzego” - wojskowego dowódcy GS-ów, czyli Oddziału Specjalnego "Jerzy”, jednego z oddziałów Kedywu KG AK. W sylwestra 1942 roku dowodzi patrolem, który wysadził przepust kolejowy pod Kraśnikiem podczas akcji “Wieniec II”. W styczniu 1943 roku zostaje mianowany kapralem podchorążym. W tym samym czasie, przeciążony innymi obowiązkami przerywa naukę na tajnej Politechnice Warszawskiej. 16 stycznia 1943 roku dowodził wykonaniem wyroku śmierci na Ludwiku Herbercie. 2 lutego bierze udział w akcji ewakuacji materiałów konspiracyjnych z mieszkania Jana Błońskiego. Od tego czasu pełni również obowiązki OS “Jerzy”.'
        '\n\n26 marca bierze udział w <b>Akcji pod Arsenałem</b> („Meksyk II”), podczas której dowodzi grupą “Atak”. 6 maja 1943 roku uczestniczy jako obserwator w próbie porwania Herberta Schultza (prowadził on śledztwo w sprawie Grup Szturmowych). Akcja kończy się zabójstwem Schultza. W nocy z 20/21 maja dowodzi akcją odbicia więźniów pod Celestynowym, który jest dla niego egzaminem oficerskim.'
        '\n\nZ 5 na 6 czerwca dowodzi akcją wysadzenia mostu kolejowego pod Czarnocinem. Na przełomie czerwca i lipca aresztowany przypadkowo spędza około tygodnia w obozie pracy przy ul. Gęsiej. W międzyczasie uczestniczy również w próbach odbicia z rąk niemieckich Floriana Marciniaka (akcje „Meksyk IV”, „Chicago”, „Biała Róża”). 15 sierpnia 1943 roku otrzymuje stopień harcmistrza, wcześniej mianowany zostaje podporucznikiem rezerwy piechoty.'
        '\n\nUmarł 20 sierpnia 1943 roku w czasie rozbicia strażnicy granicznej w miejscowości Sieczychy (Akcja „Taśma”), w której uczestniczył jako obserwator.',
    source: 'pl.wikibooks.org/wiki/Poradnik_harcerski/Tadeusz_Zawadzki',
  ),

  ItemData(
    name: 'Józef Piłsudski',
    tag: [TAG_OJCOWIE_NIEPODLEGLOSCI],
    imgSrc: [
      Tuple2('bio_jozef_pilsudski_1', ''),
      Tuple2('bio_jozef_pilsudski_2', 'Józef Piłsudski z córkami. Na kolanach marszałka siedzi Jadwiga, obok stoi Wanda. Wilno, 1923 rok. Autor: Jan Bułhak'),
      Tuple2('bio_jozef_pilsudski_3', ''),
      Tuple2('bio_jozef_pilsudski_4', '')
    ],
    dateBirth: '5 grudnia <b>1867 r.</b>, Zułów (Litwa)',
    dateDeath: '12 maja <b>1935 r.</b>, Warszawa (Polska)',
    shortDesc: 'Polski działacz społeczny i niepodległościowy, żołnierz, polityk, mąż stanu. Naczelnik państwa, pierwszy marszałek Polski. Wywarł decydujący wpływ na kształt polityki wewnętrznej i zagranicznej II RP.',
    longDesc: '<b>Dzieciństwo i młodość Józefa Piłsudskiego</b>'
        '\nJózef Klemens Piłsudski przyszedł na świat 5 grudnia 1867 roku jako czwarte dziecko Józefa i Marii i z Bilewiczów. Wychowany w duchu patriotycznym dzieciństwo spędził w majątku Zułowie na Wileńszczyźnie, a następnie, po pogorszeniu się sytuacji majątkowej rodziców, w samym Wilnie. Już jako uczeń Piłsudski założył (miedzy innymi wspólnie ze swoim bratem) kółko samokształcenia, które miało wspierać polską młodzież szkolną poddaną procesowi rusyfikacji, w działania opozycyjne wobec caratu zaangażował się jednak po ukończeniu szkoły i wyjeździe na studia medyczne do Charkowa.'
        '\n\nW czasie trwania studiów Józef Piłsudski nie unikał kontaktów z przedstawicielami organizacji głoszących hasła i cytaty niepodległościowe, kojarzono go przy tym miedzy innymi z rosyjską organizacją Narodnaja Wola działającą w opozycji do caratu i odwołującą się do dość radykalnych metod walki z władzą. Sam Piłsudski nigdy nie był ani członkiem, ani jawnym sympatykiem rewolucyjnego ugrupowania, to jednak związki z nim (Piłsudski stał się nieświadomym współuczestnikiem przygotowań do zamachu na cara) przyczyniły się do aresztowania przyszłego marszałka w 1897, a następnie jego zesłania na Syberię, z którego powrócił w roku 1892.'
        '\n\nOkres od 1892 do 1914 roku to czas aktywnej działalności w ruchu niepodległościowym. Piłsudski był aktywnym członkiem Polskiej Partii Socjalistycznej, nie oznaczało to jednak, że akceptował jej wszystkie założenia programowe. Początkowo angażował się niemal wyłącznie w działalność wydawniczą, potem również w zakrojone na szeroką skalę przygotowania do walki zbrojnej, dał się przy tym poznać nie tylko jako sprawny organizator, ale również jako osoba, która mając do wyboru radykalne działania i ugodowość zawsze opowie się za pierwszą z wymienionych tu opcji. W tym czasie Józef Piłsudski ożenił się po raz pierwszy, jego małżeństwo z działaczka PPS Marią Juszkiewiczową nie było jednak szczęśliwe, o czym może świadczyć choćby trwający w tym samym czasie wieloletni nieformalny związek późniejszego marszałka z Aleksandrą Szczerbińską.'
        '\n\n<b>Czasy Wielkiej Wojny Światowej</b>'
        '\nZamach w Sarajewie, a następnie wybuch wojny austriacko-serbskiej oznaczał spełnienie marzeń późniejszego naczelnika. Zaborcy w końcu byli ze sobą skonfliktowani, a to mogło oznaczać realną szansę na powstanie niepodległego państwa polskiego. Pierwsze działania Piłsudskiego i utworzonego przez niego oddziału wojskowego – I Kompanii Kadrowej nie wróżyły sukcesu, choć bowiem komendant i dowodzony przez niego oddział przekroczyli granice zaboru rosyjskiego, wzniecenie na jego ziemiach kolejnego powstania narodowego okazało się znacznie trudniejsze niż można byłoby się tego spodziewać. Ludność polska nie miała siły na kolejny wielki zryw, a i sam Józef Piłsudski, kojarzony przede wszystkim z ugrupowaniami lewicowymi, nie jawił się jako polityk, któremu chciano powierzać swoje życie. Nawet osoby znajdujące się w opozycji do późniejszego marszałka nie mogły jednak odmówić mu dużych sukcesów. Piłsudski przez cały czas trwania działań wojennych dawał się poznać nie tylko jako sprawny dowódca, ale i wytrawny polityk nieustannie to zbliżający się do Austrii i Niemiec, to oddalający się od nich. Lata Wielkiej Wojny to również okres, w którym budowała się jego późniejsza legenda. Komendant był kochany przez swoich żołnierzy i podziwiany przez cywilów, którym jawił się nie tylko jako bojownik o wolność, ale i jako ofiara prześladowań (między innymi poprzez uwięzienie w Magdeburgu).'
        '\n\nŻycie prywatne Piłsudskiego zdominowały narodziny pierwszej córki – Wandy, a także powrót do katolicyzmu (późniejszy marszałek przeszedł na protestantyzm, aby poślubić pierwszą żonę)'
        '\n\n<b>Lata 1918-1926</b>'
        '\nPo odzyskaniu niepodległości przez Polskę Józef Piłsudski jako Naczelnik Państwa zajmował jedną z najważniejszych funkcji w odrodzonym kraju, nie miał jednak możliwości beztroskiego cieszenia się odzyskaną wolnością. Jego pozycja nie była najsilniejsza, kochany przez żołnierzy Komendant był bowiem uważany za wroga przez duże grupy polityków. Co więcej, Naczelnik Państwa musiał koncentrować się nie tylko na walce politycznej, ale i zbrojnej – konflikt z Rosją Radziecką mógł bowiem prowadzić do upadku młodego państwa. Najgorszy scenariusz nie sprawdził się, a <b>Bitwa Warszawska</b> znana też jako „<b>Cud nad Wisłą</b>” do dziś uważana jest za jedno z największych zwycięstw polskiego wojska, nie wszystkie koncepcje polityczne i militarne, które przygotowywał późniejszy marszałek doczekały się jednak realizacji. Po wyborach parlamentarnych Piłsudski zaczął więc wycofywać się najpierw z życia politycznego, potem zaś również z obowiązków względem armii. Jako Naczelnik Państwa nie mógł rządzić w nieskończoność, zdawał sobie zaś sprawę i z tego, że jako prezydent pełniłby wyłącznie funkcje reprezentacyjne. Jego ambicje polityczne nie zostały zaspokojone, ustabilizowało się jednak życie prywatne komendanta. W 1920 na świat przyszła jego druga córka – Jadwiga, a rok później, po śmierci pierwszej żony, mógł w końcu poślubić wieloletnia partnerkę – Aleksandrę.'
        '\n\n<b>Lata 1926-1935</b>'
        '\nChoć o tym, że marszałek może powrócić do czynnego udziału w życiu politycznym mówiono już kilka miesięcy po jego wycofaniu się, doszło do tego pod koniec 1925 roku. W maju 1926 roku obawy polityków znajdujących się w opozycji wobec niego stały się faktem – Piłsudski wkroczył do Warszawy na czele podległych mu wojsk i przejął władzę, choć ponownie nie był zainteresowany stanowiskiem prezydenta. Kolejne lata jego życia to przede wszystkim walka z oponentami politycznymi (nie zawsze odbywająca się z poszanowaniem zasad demokratycznych), wzmacnianie swojej pozycji politycznej (marszałek sprawował władzę autorytarną), a także nieustanne zmagania z pogarszającym się stanem zdrowia. Ta ostatnia batalia została przegrana 12 maja 1935 roku, gdy marszałek zmarł pokonany przez chorobę nowotworową (rak wątroby, a według niektórych danych – rak żołądka z przerzutami do wątroby). Ciało marszałka spoczywa dziś na Wawelu, serce zaś – w grobie jego matki na wileńskim cmentarzu Na Rossie.',
    source: 'www.komendant.cal.pl'
  ),

  ItemData(
      name: 'Roman Dmowski',
      tag: [TAG_OJCOWIE_NIEPODLEGLOSCI],
      imgSrc: [
        Tuple2('bio_roman_dmowski_1', ''),
        Tuple2('bio_roman_dmowski_2', '')
      ],
      dateBirth: '9 sierpnia <b>1864 r.</b>, Warszawa (Litwa)',
      dateDeath: '2 stycznia <b>1939 r.</b>, Drozdowo (Polska)',
      shortDesc: 'Polski działacz społeczny i niepodległościowy, żołnierz, polityk, mąż stanu. Naczelnik państwa, pierwszy marszałek Polski. Wywarł decydujący wpływ na kształt polityki wewnętrznej i zagranicznej II RP.',
      longDesc: 'Roman Dmowski urodził się 9 sierpnia 1864 r. na podwarszawskim Kamionku w  ubogiej rzemieślniczej rodzinie brukarskiej. Dzieciństwo spędził, bawiąc się po całych dniach z dziećmi w piaskach nad łachą wiślaną. W piątym roku życia nauczył się sam czytać, a rok później rozpoczął naukę w szkółce elementarnej na Pradze (gdzie mimo zaboru rosyjskiego uczono jeszcze po polsku). W 1886 r. ukończył gimnazjum i wstąpił na wydział przyrodniczy Uniwersytetu Warszawskiego.'
          '\n\nWłaśnie podczas studiów rozpoczął swoja pracę społeczno-polityczną kierując Związkiem Młodzieży Polskiej "Zet". W grudniu 1889 r. został przyjęty do Ligi Polskiej, skupiającej działaczy narodowych zarówno na ziemiach polskich jak i na emigracji. Po kilku latach Dmowski nie zgadzając się do końca z programem Ligi Polskiej wraz ze starszymi działaczami Janem Ludwikiem Popławskim i Zygmuntem Balickim założył w 1893 r. Ligę Narodową, która zainicjowała nowy etap w walce o niepodległość Polski poprzez zjednoczenie do tych działań Polaków we wszystkich zaborach. W lutym 1895 r. sytuacja polityczna zmusiła Dmowskiego do wyjazdu do Lwowa gdzie zaczął on wydawać "Przegląd Wszechpolski" na którego łamach ukazywały się kolejne części "Myśli nowoczesnego Polaka" (wydanej całością w 1903 r.). "Myśli" stały się "wyznaniem wiary narodowej" a swoją aktualnością, prostotą i dojrzałością zachwycają także czytelników obecnej doby.'
          '\n\nDmowski po latach obserwacji sytuacji geopolitycznej doszedł do wniosku, że walkę o niepodległość należy prowadzić u boku Rosji i państw alianckich, a za głównego wroga uznał Niemcy. Poglądy te zawarł w pracy "Niemcy, Rosja i kwestia polska" wydanej w 1907 r. Zgodnie z oczywistą prawdą, ze nieobecni nie maja racji został również posłem do rosyjskiej Dumy i tam walczył wytrwale o polskie interesy stając na czele Koła Polskiego.Przez okres I wojny światowej Dmowski przebywał głównie na Zachodzie, najpierw w Londynie potem w Paryżu gdzie stanął na czele Komitetu Narodowego Polskiego uznanego przez aliantów za oficjalnego reprezentanta Polski na arenie międzynarodowej. 11 sierpnia 1916 roku otrzymał doktorat honoris causa na Uniwersytecie w Cambridge, a 23 lutego 1918 r. utworzył Armię Polską we Francji, pod dowództwem gen. Hallera.'
          '\n\nOd początku 1919 r. Dmowski uczestniczył jako przewodniczący polskiej delegacji na konferencji pokojowej w Wersalu. To głównie dzięki jego staraniom i wybitnym, politycznym zdolnościom Polska uzyskała szerokie cesje terytorialne, maksymalne jakie mogła w tamtych warunkach otrzymać, co potwierdzone zostało Traktatem Wersalskim, podpisanym właśnie przez Dmowskiego 28 czerwca 1919 r. Polska po 124 niemalże latach niewoli oficjalnie powróciła na mapę Europy jako jeden ze zwycięzców wojny.'
          '\n\nPo zakończeniu wojny Dmowski usunął się nieco w cień, zajął się pisarstwem i publikowaniem artykułów na łamach "Gazety Warszawskiej" i "Polityki Narodowej". Jedyną funkcją jaką dane mu było sprawować w II Rzeczpospolitej był urząd Ministra Spraw Zagranicznych w 1923 r. W tym samym roku otrzymał także doktorat honoris causa Uniwersytetu Poznańskiego. W 1925 r. wydał arcydzieło literatury politycznej - książkę "Polityka polska i odbudowanie państwa", w której opisał swoje życiowe zmagania o odbudowanie państwa polskiego.'
          '\n\nPo dokonanym przez Józefa Piłsudskiego zamachu majowym, 4 grudnia 1926 Dmowski powołał w Poznaniu Obóz Wielkiej Polski, organizację narodową, która w czasie rozwiązania jej przez sanację na początku 1933 r. liczyła ok. 250 tys. członków.  Od czerwca do października 1928 tworzył Stronnictwo Narodowe. Do końca życia wytrwale służył radą młodszemu pokoleniu działaczy narodowych (prezes honorowy Młodzieży Wszechpolskiej) i był wyrocznią w sprawach politycznych, społecznych i gospodarczych.'
          '\n\nRoman Dmowski zmarł 2 stycznia 1939 r. w Drozdowie pod Łomżą. Pochowany został w grobie rodzinnym cmentarza na Bródnie. Jego pogrzeb (zbojkotowany przez piłsudczyków) zgromadził tłumy i stał się największą manifestacją II RP (ponad 100 tys. Ludzi).'
          '\n\nWielki mąż stanu pozostawił po sobie ogromny dorobek pisarski, do którego oprócz ww. należą "Kościół, Naród, Państwo", "Upadek myśli konserwatywnej w Polsce" czy "Dziedzictwo". Nie był on rasowym politykiem w dzisiejszym tego słowa znaczeniu. W swojej działalności polityczno-społecznej nie posługiwał się krasomówczą mową, spektakularnym gestem lub czczą obietnicą. Jego główna bronią była twórczość pisarska. Z jej pomocą tłoczył nieustannie narodową myśl we własne szeregi i nie tylko. <i>"(...)poglądy młodego pokolenia niemal w całości, poglądy inteligencji polskiej chyba w lwiej części, poglądy wszystkich innych warstw polskich w całych dziedzinach, są tak czy owak zaczerpnięte z Dmowskiego" (Ksawery Pruszyński)</i>. O jego wielkości wielkim charakterze może świadczyć cytat z przedwojennego "Zielonego Sztandaru": <i>"Można się było godzić lub nie z jego ideologią lub polityką w rozmaitych okresach długiego życia, ale niepodobna nie uznać, że kierował się najszczerszymi intencjami służenia narodowi i służenia bezinteresownie"</i>. ',
      source: 'romandmowski.edu.pl'
  ),

  ItemData(
      name: 'Danuta Siedzikowna (Inka)',
      tag: [],
      imgSrc: [
        Tuple2('bio_inka_1', ''),
        Tuple2('bio_inka_2', 'Rodzina Siedzików. Od lewej: stoją Eugenia z Danutą, siedzą Jadwiga z matką Anielą, przed nimi Wacław z córkami – z lewej Irena (z kokardą), z prawej Wiesława, leśniczówka w Olchówce koło Narewki, lato 1939 r.'),
        Tuple2('bio_inka_3', 'Siostry Siedzikówny z babcią Anielą i kuzynostwem, Danuta Siedzikówna pierwsza z lewej, Olchówka koło Narewki, wczesne lata trzydzieste XX w.'),
        Tuple2('bio_inka_4', 'Danuta Siedzikówna z przyjaciółmi, Narewka, 1944 lub 1945 r.'),
        Tuple2('bio_inka_5', 'Danuta Siedzikówna z siostrą Wiesławą, Podlasie, zima 1942 r.'),
        Tuple2('bio_inka_6', 'Danuta Siedzikówna ze szkolną przyjaciółką, Podlasie, lata trzydzieste XX w.'),
        Tuple2('bio_inka_7', 'Danuta Siedzikówna z przyjaciółką, Narewka, kwiecień 1945 r.'),
        Tuple2('bio_inka_8', 'Żołnierze 4. szwadronu 5. Wileńskiej Brygady AK. Białostocczyzna, lato 1945 r.Żołnierze 4. szwadronu 5. Wileńskiej Brygady AK. Białostocczyzna, lato 1945 r.'),
        Tuple2('bio_inka_9', 'Danuta Siedzikówna „Inka” z koleżanką, Podlasie, zima 1945 r.'),
        Tuple2('bio_inka_10', 'Koncentracja 5. Wileńskiej Brygady AK w gajówce Stoczek. wrzesień 1945 r.'),
        Tuple2('bio_inka_11', 'Marek Odyn-Jankowski „Marek”, Danuta Siedzikówna „Inka”, Bogdan Obuchowski „Zbyszek”, Pomorze, wiosna 1946 r.'),
      ],
      dateBirth: '3 września <b>1928 r.</b>, Guszczewina (Polska)',
      dateDeath: '28 sierpnia <b>1946 r.</b>, Gdańsk (Polska)',
      shortDesc: 'Sanitariuszka 4. szwadronu odtworzonej na Białostocczyźnie 5 Wileńskiej Brygady AK, w 1946 w 1 szwadronie Brygady działającym na Pomorzu, pośmiertnie mianowana podporucznikiem Wojska Polskiego.',
      longDesc: 'Danuta Siedzikówna, córka Wacława i Eugenii z Tymińskich, należała do pokolenia ludzi ukształtowanych w atmosferze afirmacji niepodległości i dumy z własnego państwa.'
          '\n\nUrodziła się 3 września 1928 r. we wsi Guszczewina w powiecie bielskim na Podlasiu. Jej ojciec, leśniczy, podczas studiów na politechnice w Petersburgu prowadził działalność antycarską, za co trafił na zesłanie. Do wolnej już Polski wrócił dopiero w 1926 r. Wkrótce po powrocie wziął ślub z Eugenią Tymińską. Po roku przyszła na świat ich pierwsza córka Wiesława, rok później Danuta, a w 1931 r. Irena. Dziewczynki uczyły się w szkole powszechnej w Narewce.'
          '\n\nDzięki rodzicom i dziadkom ważną rolę w domu zawsze odgrywały tradycje patriotyczne.'
          '\n\nOlchówka po 17 września 1939 r. znalazła się pod okupacją sowiecką i 10 lutego 1940 r. aresztowano ojca rodziny, Wacława Siedzika. Po gehennie śledztwa został zesłany do katorżniczej pracy w kopalni złota w rejonie Nowosybirska. Kiedy premier Władysław Sikorski zawarł 30 lipca 1941 r. układ sojuszniczy z rządem sowieckim, dziesiątki tysięcy polskich obywateli zwolniono z obozów i więzień i ojciec Danuty Siedzikówny trafił do Persji. Został komendantem obozu dla uchodźców z Syberii, niestety choroba poczyniła takie spustoszenia, że zmarł tam 6 czerwca 1943 r. O jego losach rodzina dowiedziała się dopiero po wojnie.'
          '\n\nPo aresztowaniu męża Eugenia Siedzikowa z córkami zostały zmuszone do opuszczenia leśniczówki. W kwietniu 1940 r. osiedliła się w Narewce, gdzie zastała je inwazja niemiecka na Związek Sowiecki. Mama Danuty, Eugenia zaangażowała się we współpracę z Armią Krajową, za co została aresztowana w listopadzie 1942 r.. Przeszła ciężkie śledztwo i tortury. Danuta wówczas dwukrotnie miała okazję w tajemnicy przed Niemcami porozmawiać z mamą. Eugenia Siedzikowa w jednym z grypsów z więzienia pisała do córek: <i>„Dziewczynki, zemstę zostawcie Bogu”</i>.'
          '\n\nWe wrześniu 1943 r. Eugenia Siedzikowa została rozstrzelana w nieznanym miejscu w lesie koło Białegostoku. Po jej zamordowaniu opiekę nad siostrami roztoczyła rodzina.'
          '\n\nWiesława i Danuta wstąpiły w grudniu 1943 r. do Armii Krajowej i kilka miesięcy później skierowano je na kurs dla sanitariuszek.'
          '\n\nJeszcze w październiku 1944 r., po przejściu frontu, zaledwie szesnastoletnia Danuta Siedzikówna zatrudniła się jako kancelistka w nadleśnictwie w Narewce; godziła później pracę z konspiracją.'
          '\n\nWyparcie wojsk niemieckich z Polski nie oznaczało odzyskania niepodległości. Sowieci przystąpili do unicestwiania osób i środowisk niezgadzających się z ustrojem komunistycznym. Skala i natężenie terroru wymierzonego w środowiska antysowieckie i niepodległościowe zadziałały dwojako. Większość społeczeństwa po hekatombie II wojny światowej przyjęła strategię przetrwania w nowych warunkach ustrojowych. Z drugiej strony kilkadziesiąt tysięcy żołnierzy podziemia pozostało w konspiracji, zachowując gotowość bojową, nie chcąc pogodzić się z samowolą i bezkarnością sił sowieckich stacjonujących w Polsce.'
          '\n\nDo podziemnej armii należała 5. Wileńska Brygada Armii Krajowej (nazywana też niekiedy Brygadą Śmierci) dowodzona przez zawodowego oficera przedwojennego <b>mjr. Zygmunta Szendzielarza „Łupaszkę”</b>. Jej trzon stanowili żołnierze pierwszego oddziału partyzanckiego na Wileńszczyźnie, dowodzonego przez Antoniego Burzyńskiego „Kmicica”.'
          '\n\nDanuta Siedzikówna dołączyła do Brygady w czerwcu 1945 r. w dramatycznych okolicznościach. Wówczas NKWD i Wojewódzki Urząd Bezpieczeństwa aresztowały wszystkich pracowników nadleśnictwa w Narewce pod zarzutem współpracy z podziemiem niepodległościowym. Gdy przewożono ich do Białegostoku, w pobliżu Hajnówki konwój zaatakowali żołnierze z patrolu podległego Stanisławowi Wołaciejowi „Konusowi”. Świadkiem tego wydarzenia była najmłodsza z sióstr Siedzikówien – Irena.'
          '\n\nNie mając nic do stracenia, Danuta po uwolnieniu z konwoju dołączyła do oddziału 5. Wileńskiej Brygady AK. Została sanitariuszką w oddziale „Konusa”, a potem w szwadronach por. Jana Mazura „Piasta” i por. Mariana Plucińskiego „Mścisława” w plutonie Zdzisława Badochy „Żelaznego”. W konspiracji Danuta Siedzikówna używała pseudonimu „Inka”, który nawiązywał do <b>imienia jej przyjaciółki</b>.'
          '\n\nPo kilku miesiącach mjr Szendzielarz wydał rozkaz rozformowania zgrupowania. Ostatnia koncentracja wszystkich sił miała miejsce 7 września 1945 r. w gajówce Stoczek, leżącej na terenie gminy Poświątne. Tylko nieliczni żołnierze pozostali w lesie.'
          '\n\n„Inka” należała do tych członków Brygady, którzy we wrześniu 1945 r. wrócili do legalnego życia. Podjęła naukę w gimnazjum w Nierośnie w gminie Dąbrowa Białostocka. Później w jej dokumentach znalazł się zapis, iż ukończyła dwie klasy tej szkoły. Nie zdecydowała się na ujawnienie swoich związków z konspiracją przed organami władz komunistycznych po amnestii ogłoszonej przez Tymczasowy Rząd Jedności Narodowej w sierpniu 1945 r.'
          '\n\nObawiała się zdemaskowania przez UB i dlatego skorzystała z pomocy ojca chrzestnego, z zawodu leśniczego, Stefana Obuchowicza, który znalazł jej od stycznia 1946 r. pracę w nadleśnictwie Miłomłyn koło Ostródy. „Inka” legitymowała się podrobionym zaświadczeniem, gdzie zapisano, że jego właścicielka w końcowym okresie wojny przebywała na robotach przymusowych w Prusach, skąd wróciła do Polski po zajęciu tych terenów przez Armię Czerwoną.'
          '\n\nPraca „Inki” w Miłomłynie nie trwała długo, już pod koniec lutego 1946 r. odnowiła ona kontakt z oddziałem, który tymczasem zaczął przerzucać swoje siły do województwa olsztyńskiego. Pojawił się też plan, aby zainicjować działania partyzanckie w województwie gdańskim, co było niezwykle śmiałym zamierzeniem, ponieważ członkowie oddziału nie znali tych terenów ani ludzi tam mieszkających. Oparcie dla konspiratorów mieli tworzyć repatrianci z Kresów Wschodnich, przybywający do północnej Polski od wiosny 1945 r. Liczono również na wykorzystanie portów morskich jako kanałów komunikacji z polskim wychodźstwem niepodległościowym.'
          '\n\nDo walki z Sowietami i reżimem komunistycznym popychało ludzi na Pomorzu postępowanie żołnierzy Armii Czerwonej, NKWD i przedstawicieli rządu warszawskiego, w tym przede wszystkim funkcjonariuszy Urzędu Bezpieczeństwa Publicznego i działaczy PPR. Czerwonoarmiści zachowywali się jak zdobywcy na podbitym terenie. Zarówno w okresie walk frontowym, jak i przez wiele następnych miesięcy dopuszczali się przestępstw na ludności cywilnej, nie tylko mniejszości niemieckiej, lecz także dominujących liczebnie miejscowych Polakach. Gwałty, rabunki, a nawet zabójstwa były na porządku dziennym.'
          '\n\n„Inka” dołączyła ponownie do oddziału na początku marca 1946 r. Dostała przydział do szwadronu dowodzonego przez Zdzisława Badochę „Żelaznego”. Powierzono jej obowiązki sanitariuszki. Niekiedy wykonywała zadania łączniczki, a czasem także wywiadowcy. Olgierd Christa „Leszek” tak ją wspominał: <i>„Była bardzo lubiana za skromność, a jednocześnie hart i pogodę ducha. Znosiła trudy z równą chłopcom wytrwałością, zwłaszcza psychiczną. Raz tylko w czasie powrotu znad Wisły prosiła, by ktoś przejął jedną z jej ciężkich toreb. Maszerowaliśmy wtedy prawie półbiegiem ze względu na odległe miejsce postoju, a ją właśnie gnębił brak formy”</i>.'
          '\n\nSzwadrony mjr. „Łupaszki” prowadziły niezwykle śmiałą działalność w województwie gdańskim. Od lutego 1946 r., wykorzystując rekwirowane samochody wojskowe, przemieszczały się między miejscowościami i powiatami, przeprowadzając akcje wymierzone w UB i NKWD. Podkomendni Zygmunta Szendzielarza rozbrajali posterunki Milicji Obywatelskiej, karząc tych funkcjonariuszy, o których wiedziano, że wysługując się reżimowi, działali na szkodę lokalnej ludności. Innym milicjantom nie czyniono krzywdy. Karano chłostą nadgorliwych członków PPR i donosicieli. Ludność informowano o prawdziwych celach obecności Sowietów w Polsce i charakterze reżimu komunistycznego.'
          '\n\nW szeregach szwadronu „Żelaznego” Siedzikówna uczestniczyła m.in. w tzw. akcji pociągowej – przeprowadzonej na stacji Tlen w powiecie świeckim 4 maja 1946 r. Następnie oddział przeszedł na teren powiatu tucholskiego. Najbardziej spektakularna akcja miała miejsce 19 maja, kiedy szwadron jednego dnia rozbroił załogi siedmiu posterunków MO i jednej placówki UB w powiatach kościerskim i starogardzkim. 23 maja pod wsią Podjazdy w powiecie kościerskim doszło do starcia szwadronu z oddziałem MO. Zginął wtedy jeden milicjant i jeden ubowiec, trzech milicjantów zostało rannych.'
          '\n\n10 czerwca wraz ze szwadronem brała udział w potyczce koło wsi Tulice w powiecie sztumskim. W trakcie walki został ranny „Żelazny”. Po złamaniu oporu milicjantów i UB, na rozkaz por. Olgierda Christy „Leszka”, partyzanci rozstrzelali dwóch funkcjonariuszy UB. Jedną z ostatnich akcji z jej udziałem jako sanitariuszki szwadronu „Żelaznego” była zasadzka na stacji kolejowej Bąk w powiecie czerskim 24 czerwca. Partyzanci zatrzymali tam pociąg relacji Gdynia–Katowice, w którym szukali Sowietów. Zatrzymali pięciu i zastrzelili ich. „Inka” dostała rozkaz pilnowania obsługi stacji, aby nie próbowała wysłać sygnału ostrzegawczego do milicji lub UB.'
          '\n\nNiezwykle ważną funkcję pełniły w oddziale łączniczki przenoszące rozkazy, dzięki którym koordynowano działania poszczególnych szwadronów. Było to trudne zadanie dla osób nieznających wcześniej Pomorza Nadwiślańskiego. Kaszubi mówiący własnym językiem i Kociewiacy mający własny dialekt, z którymi kontaktowały się łączniczki z innych obszarów Polski, bez trudu orientowali się, że mają do czynienia z osobami przybyłymi z innych regionów Polski. „Inka” radziła sobie z tymi problemami, na rozkaz przełożonych docierała zawsze do wskazanych miejsc i ludzi.'
          '\n\nOstatnią misją „Inki” była podróż do Malborka, Gdańska i Olsztyna. Sanitariuszka miała zdobyć lekarstwa potrzebne oddziałowi i dowiedzieć się, dlaczego „Żelazny” tak długo nie wracał (jak się później okazało, już nie żył). Wyruszyła 13 lipca ze wsi Zwierzyniec z domu zaprzyjaźnionych z partyzantami Łytkowskich w towarzystwie Henryka Kazimierczaka „Czajki”. Po wykonaniu zadania miała stawić się 20 lipca w Lipowej Tucholskiej. Pierwszym celem podróży był Malbork.'
          '\n\nChoć w Gdańsku mieszkali jej bliscy krewni: siostra Irena i wujek Bruno Tymiński, studiujący na Politechnice Gdańskiej, „Inka” zatrzymała się w jednym z lokali konspiracyjnych u pochodzących z Wilna sióstr Mikołajewskich, w Gdańsku-Wrzeszczu przy ul. Wróblewskiego 7. Wieczór i noc z 19 na 20 lipca przebiegły w radosnej atmosferze, wypełnionej rozmowami i śpiewaniem piosenek.'
          '\n\nDom obserwowali funkcjonariusze UB, którzy nad ranem wkroczyli do mieszkania i aresztowali „Inkę”. Adres zdradziła im łączniczka „Łupaszki” Regina Żylińska-Modras, którą zatrzymano 20 kwietnia 1946 r. i skłoniono do współpracy z bezpieką.'
          '\n\nŚledczy z Wojewódzkiego Urzędu Bezpieczeństwa Publicznego w Gdańsku chcieli od Siedzikówny uzyskać wszystkie informacje na temat działalności oddziału mjr. „Łupaszki” i osób, które im pomagały. By zmusić ją do zeznań, zastraszano ją, poniżano i torturowano, czego świadkami były osoby, które zetknęły się z nią w gdańskim więzieniu.'
          '\n\nJedestego dnia po aresztowaniu Andrzej Stawicki, oficer śledczy WUBP w Gdańsku, sporządził akt oskarżenia. 31 lipca wnioskował o skazanie „Inki” na karę śmierci.'
          '\n\nNa pierwszej i – jak się okazało – jedynej rozprawie sędzia odczytał akt oskarżenia. „Inka” nie przyznała się do zarzucanych jej czynów – strzelania do milicjanta i podżegania do zabicia funkcjonariuszy UB.'
          '\n\nWszystkie czynności procesowe trwały zaledwie dwie godziny.'
          '\n\nDo krewnych dotarł gryps, w którym Danuta napisała: „Jest mi smutno, że muszę umierać. Powiedzcie mojej babci, że zachowałam się jak trzeba”.'
          '\n\nOstatnie chwile jej życia wspominał ks. Marian Prusak, który został wezwany, aby udzielić jej ostatniego namaszczenia. Siedzikówna nie zginęła sama. Wraz z nią został rozstrzelany Feliks Selmanowicz „Zagończyk”, przedwojenny żołnierz zawodowy, uczestnik kampanii wrześniowej, który całą okupację służył w oddziałach polskiej konspiracji niepodległościowej.'
          '\n\nNa moment przed śmiercią Siedzikówna i Selmanowicz krzyknęli: „Niech żyje Polska!”.'
          '\n\nŻołnierze mjr. „Łupaszki” walczyli na Pomorzu do końca listopada 1946 r. Następnie rozproszyli się po Polsce. Część z nich, w tym sam ich dowódca, wpadła w ręce UB.'
          '\n\nWydział IV Karny Sądu Wojewódzkiego w Gdańsku postanowieniem z 10 czerwca 1991 r. uznał za nieważny wyrok wydany w sprawie „Inki” pół wieku wcześniej przez gdański WSR, ponieważ – jak stwierdzono w sentencji wyroku – Danuta Siedzikówna działała na rzecz niepodległego bytu państwa polskiego.',
      source: 'biogramy.ipn.gov.pl'
  ),

  ItemData(
      name: 'ppor. Jan Piwnik (Ponury)',
      tag: [],
      imgSrc: [
        Tuple2('bio_ponury_1', ''),
        Tuple2('bio_ponury_2', 'Ppor. Waldemar Szwiec „Robot” melduje por. Janowi Piwnikowi „Ponuremu” przybycie II Zgrupowania na koncentrację.'),
        Tuple2('bio_ponury_3', 'Komendant Zgrupowań Partyzanckich Armii Krajowej „Ponury” por. Jan Piwnik wita księdza Mariana Majewskiego ps. „Robak”, który przybył do obozu partyzantów AK na Wykusie odprawić mszę św. 12 września 1943 roku. W środku por. Eugeniusz G. Kaszyński ps. „Nurt”, dowódca Zgrupowania nr 1. Za „Ponurym” w skórzanym płaszczu por. „Habdank” Jerzy Stefanowski, dowódca oddziału w Zgrupowaniu nr 1. Zdjęcie: Tadeusz Rylski.'),
        Tuple2('bio_ponury_4', ''),
        Tuple2('bio_ponury_5', 'Przysięga żołnierzy 2 kompanii 7 batalionu 77 Pułku Piechoty (Okręg Nowogródek Armii Krajowej). Na fotografii widoczni są oficerowie i stół z krucyfiksem. Stoją od lewej: drugi (w głębi) ppor. Bojomir Tworzyański ps. „Ostoja”, trzeci ppłk Jan Szulc vel Janusz Szlaski ps. „Prawdzic”, piąty (z mapnikiem) por. Jan Piwnik ps. „Ponury”.'),
        Tuple2('bio_ponury_6', 'Część dowództwa Zgrupowań – Osieczno, sierpień 1943 r. – stoją od lewej: plut. Jan Dąbrowski „Listek” – ordynans „Ponurego”, por. cc. „Nurt” – zastępca „Ponurego”, ppor. cc. Rafał Andrzej Niedzielski „Rafał Mocny” – d-ca plutonu 1. w zgrupowaniu nr 2, komendant – por. cc. „Ponury”, ppor. St. Pałac „Mariański” – d-ca Zgrupowania nr 3, ppor. Władysław Czerwonka „Czerwony Jurek” – d-ca oddziału w Zgrupowaniu nr 3, ppor. Euzebiusz Domoradzki „Grot”, ppor. J. Wojnowski „Motor” – d-ca plutonu saperskiego. W dolnym rzędzie siedzą od lewej: por. Witold Waligórski „Witek” – oficer wywiadowczy, por. cc. Jan Rogowski „Czarka”, Albin Hop „Stefanowski” – d-ca plutonu ochronnego, ppor. Leszek Popiel de Choszczak „Antoniewicz” – adiutant Zgrupowań (fot. Feliks Konderko „Jerzy” – ze zbiorów Mariusza Barana – Barańskiego) '),
        Tuple2('bio_ponury_7', 'Oficerowie "Ponurego". Od lewej: ppor. Rafał Niedzielski, ppor. Władysław Czerwonka, ppor. Wincenty Waligórski, ppor. Stanisław Pałac, ppor. Waldemar Szwiec, leży por. Jan Rogowski.'),
      ],
      dateBirth: '31 sierpnia <b>1912 r.</b>, Janowice (Polska)',
      dateDeath: '16 czerwca <b>1944 r.</b>, ok. Jewłasze (Polska)',
      shortDesc: 'Kapitan Wojska Polskiego i aspirant Policji Państwowej, cichociemny, pośmiertnie awansowany do stopnia majora, a następnie do stopnia pułkownika (2012), dowódca partyzancki Armii Krajowej w Górach Świętokrzyskich i na Nowogródczyźnie.',
      longDesc: 'Jan Piwnik urodził się 31 sierpnia 1912 w Królestwie Polskim. W 1932 roku zdał maturę.'
          '\n\nPo wybuchu agresji niemieckiej na Polskę przez pierwszy tydzień września 1939 r. Jan Piwnik razem z Grupą Rezerwy Policyjnej ochraniał mosty na Pilicy.'
          '\n\n23 września wycofując się przekroczył granicę z Węgrami, gdzie został internowany. Za wszelką cenę starał się nie dopuścić do rozkładu moralnego podkomendnych.'
          '\n\nBędąc internowanym wszedł w skład dowództwa siatki konspiracyjnej, która przerzucała ochotników do formujących się we Francji Polskich Sił Zbrojnych (PSZ). Kiedy proceder został ujawniony Piwnikowi zagrożono cytadelą oraz obozem karnym. Piwnik symulując chorobę, zdołał zbiec ze szpitala i przez Jugosławię i Włochy <b>przedostał się do Francji</b>.'
          '\n\nW czerwcu 1940 r. Francja skapitulowała. Piwnik <b>przedostał się do Wielkiej Brytanii</b> na czele oddziału skupiającego rozbitków z różnych polskich jednostek, na jednym z ostatnich statków. Tam został wcielony do <b>dywizjonu artylerii w 4 Brygadzie Kadrowej Strzelców</b>. Następnie przeniósł się do 1 Samodzielnej Brygady Spadochronowej. Szybko zgłosił się do służby w Kraju i w 1941 przeszedł szkolenie dla cichociemnych pod Londynem.'
          '\n\n10 października 1941 r. złożył przysięgę na rotę Związku Walki Zbrojnej AK pod pseudonimem „Ponury”. Niecały miesiąc później, w nocy <b>z 7 na 8 listopada 1941 roku <b>został zrzucony do Polski.</b>'
          '\n\nPiwnik rozpoczął walkę partyzancką. 18 stycznia 1943 r. pod pseudonimem <b>„Donat”</b> przeprowadził akcję odbicia 3 więźniów z więzienia w Pińsku. Akcja ta została uznana za wzorcową i na jej podstawie prowadzono szkolenia z dywersji. Za jej przeprowadzenie w odwecie Niemcy rozstrzelali 30 zakładników.'
          '\n\nW marcu 1943 roku za zgodą KG AK "Ponury" sformował leśny oddział partyzancki w Górach Świętokrzyskich, zaś niedługo potem w połowie maja 1943 został dowódcą Zgrupowań Partyzanckich AK “Ponury”. Bazą wypadową zgrupowania stało się <b>wzgórze 326</b> pod nazwą <b>Wykus</b> i Puszczy Świętokrzyskiej.'
          '\n\nLatem 1943 roku zgrupowanie przeprowadziło szereg akcji dywersyjnych na obiekty niemieckie. Likwidowały też konfidentów, rozprawiały się z bandami rabunkowymi. Zgrupowanie prowadziło także szkolenie rekruckie z naciskiem na dywersję, minerstwo, znajomość broni.'
          '\n\nObok partyzanckiej walki zbrojnej "Ponury" wspierał też cywilną ludność zamieszkującą rejony świętokrzyskie. 11 lipca 1943 roku ludność Kielecczyzny symbolicznie wręczyła mu orzełki - uznawała go za przedstawiciela władz. Cieszył się <b>dużym zaufaniem ludności</b>, rozwiązywał m.in. spory sąsiedzkie mieszkańców.'
          '\n\n19 lipca 1943 roku jego zgrupowaniu na Wykusie udało się ujść przed pierwszą niemiecką obławą. Dwa miesiące później, 16 września 1943 roku Niemcy zaplanowali drugą obławę na zgrupowanie. Dowiedziawszy się o tym kilka dni wcześniej "Ponury" przygotował na Niemców zasadzkę, w rezultacie czego Niemcy odnieśli duże straty.'
          '\n\n28 października 1943 roku wyznaczył ostatnią przez rozłączeniem oddziałów koncentrację zgrupowań na Wykusie. Tym razem Niemcy ponownie przeprowadzili obławę zadając duże straty partyzantom.'
          '\n\nNa przełomie lutego i marca 1944 przybył na teren Okręg Nowogródek. gdzie przygotował i przeprowadził ataki na niemieckie posterunki i garnizony.'
          '\n\n27 maja przybył ostatecznie na Kielecczyznę, natomiast 4 czerwca <b>objął dowództwo okręgowego Kedywu</b>.'
          '\n\nW czerwcu 1944 roku przyszedł rozkaz realizacji planu <b>“Burza”</b>. Bataliony polskie miały uderzyć na umocnienia niemieckie na granicy.'
          '\n\nOd 8 czerwca kierował atakami na niemieckie umocnienia ze spektakularnymi sukcesami. Niemcy odnieśli ogromne straty.'
          '\n\nZginął 16 czerwca podczas ataku na niemiecki punkt pod wsią Jewłasze. Pochowano go na cmentarzu w <b>Wawiórce</b>.'
          '\n\nZwykł często mawiać: <i>„Zginąć, czy splunąć. To wszystko jedno”</i>.'
          '\n\nOstatnie słowa jakie miał ranny wypowiedzieć przed śmiercią, to: <i>„Powiedz żonie i rodzicom, że ich bardzo kochałem, i że umieram jako Polak. I pozdrówcie Góry Świętokrzyskie.”</i>'
          '\n\nTak śmierć kpt. Jana Piwnika „Ponurego” opisał jego podkomendny, Stanisław Szyszko „Jeleń”, żołnierz 2 kompanii VII batalionu 77 pułku piechoty Armii Krajowej:'
          '\n\n<i>„Zza rogu budynku wyskoczył z granatem w ręku komendant Ponury i okrzykiem: Chłopcy, naprzód! poderwał do ataku pozostałych żołnierzy. Komendant po skoku przez bramę wjazdową do wnętrza umocnień został trafiony kilkoma pociskami w brzuch z karabinu maszynowego z odległości ok. 30 metrów z przeciwległego bunkra"</i>.',

      source: 'www.radio.kielce.pl/post-57354'
  ),

];

class ItemData{

  final String name;
  final String? fullName;
  final List<String> tag;
  final List<Tuple2<String, String>> imgSrc;
  final String dateBirth;
  final String dateDeath;
  final String shortDesc;
  final String longDesc;
  final String source;

  const ItemData({
    required this.name,
    this.fullName,
    this.tag: const [],
    required this.imgSrc,
    required this.dateBirth,
    required this.dateDeath,
    required this.shortDesc,
    required this.longDesc,
    required this.source});

}