
import 'package:flutter/material.dart';
import 'package:material_design_icons_flutter/material_design_icons_flutter.dart';

import 'lang.dart';

/*
Propozycje nowych słów:
- warta
- brama
- stołówka
- ognisko obrzędowe
- wartownik
- wyprawa
- płomień
- kompas
 */

const List<TransData> allWordsData = [
  TransData(MdiIcons.medicalBag,
    TransLangData(TransWordData('apteczka')),
    mug: TransLangData(TransWordData('podręczny zestaw medyczny do udzielania pierwszej pomocy')),
    eng: TransLangData(TransWordData('first-aid kit')),
    ger: TransLangData(TransWordData('Verbandskasten', prefix: 'der')),
    esp: TransLangData(TransWordData('botiquín')),
    ita: TransLangData(TransWordData('cassetta di pronto soccorso')),
    cze: TransLangData(TransWordData('lékárnička')),
    nor: TransLangData(TransWordData('førstehjelpsskrin', prefix: 'en')),
    ned: TransLangData(TransWordData('EHBO-doos')),
  ),
  TransData(MdiIcons.tent,
    TransLangData(TransWordData('biwak')),
    mug: TransLangData(TransWordData('krótki, ok. 2-3 dniowy wyjazd harcerski')),
    eng: TransLangData(TransWordData('weekend camp')),
    ger: TransLangData(TransWordData('Biwak', prefix: 'das')),
    esp: TransLangData(TransWordData('camping de fin de semana')),
    ita: TransLangData(TransWordData('bivacco')),
    cze: TransLangData(TransWordData('výprava')),
    nor: TransLangData(TransWordData('leir', prefix: 'en')),
    ned: TransLangData(TransWordData('weekend kamp')),
  ),
  TransData(MdiIcons.gasCylinder,
    TransLangData(TransWordData('butla gazowa')),
    mug: TransLangData(TransWordData('butla napełniona gazem przeznaczona do wykorzystania z palnikiem gazowym, zywkle w celu przyrządzania jedzenia.')),
    eng: TransLangData(TransWordData('gas bottle')),
    ger: TransLangData(TransWordData('Gasflasche', prefix: 'die'), alt: [TransWordData('Gaskartusche', prefix: 'die')]),
    esp: TransLangData(TransWordData('botella de gas')),
    ita: TransLangData(TransWordData('bomboletta di gas')),
    cze: TransLangData(TransWordData('plynová bomba')),
    nor: TransLangData(TransWordData('gassflaske'), alt: [TransWordData('gassboks')]),
    ned: TransLangData(TransWordData('gasfles')),
  ),
  TransData(MdiIcons.flag,
    TransLangData(TransWordData('chorągiew')),
    mug: TransLangData(TransWordData('jednostka zrzeszająca harcerzy z terenu porównywalnego do województwa (wyjątkiem jest Chorągiew Stołeczna działająca na terenie Warszawy)')),
    eng: TransLangData(TransWordData('scout region', literalTrans: 'region skautowy')),
    ger: TransLangData(TransWordData('Landesverband', prefix: 'der')),
    esp: null,
    ita: TransLangData(TransWordData('regionale')),
    cze: TransLangData(TransWordData('kraj')),
    nor: TransLangData(TransWordData('krets', prefix: 'en')),
    ned: TransLangData(TransWordData('(scout) gebied')),
  ),
  TransData(MdiIcons.campfire,
    TransLangData(TransWordData('chrust')),
    mug: TransLangData(TransWordData('cienkie drewno na opał')),
    eng: TransLangData(TransWordData('kindling')),
    ger: TransLangData(TransWordData('Reisig', prefix: 'das')),
    esp: TransLangData(TransWordData('astillas')),
    ita: TransLangData(TransWordData('sterpaglie da bruciare')),
    cze: TransLangData(TransWordData('chrastí')),
    nor: TransLangData(TransWordData('tørrpinne')),
    ned: TransLangData(TransWordData('aanmaakhout')),
  ),
  TransData(MdiIcons.triangle,
    TransLangData(TransWordData('chusta harcerska')),
    mug: TransLangData(TransWordData('trójkątny kawałek materiału noszony przez harcerzy pod kołnierzem munduru świadczący o przynależności do jednostki harcerskiej')),
    eng: TransLangData(TransWordData('scout scarf')),
    ger: TransLangData(TransWordData('Scoutschal', prefix: 'der')),
    esp: TransLangData(TransWordData('pañuelo')),
    ita: TransLangData(TransWordData('fazzolettone')),
    cze: TransLangData(TransWordData('šátek')),
    nor: TransLangData(TransWordData('speiderskjerf', prefix: 'et')),
    ned: TransLangData(TransWordData('scoutingdas')),
  ),
  TransData(MdiIcons.weatherNight,
    TransLangData(TransWordData('cisza nocna')),
    mug: TransLangData(TransWordData('godziny nocne, w których należy bezwzględnie zachować ciszę')),
    eng: TransLangData(TransWordData('lights-out period')),
    ger: TransLangData(TransWordData('Nachtruhe', prefix: 'die')),
    esp: TransLangData(TransWordData('silencio de noche')),
    ita: TransLangData(TransWordData('silenzio notturno')),
    cze: TransLangData(TransWordData('noční kud')),
    nor: TransLangData(TransWordData('natt stillheten'), alt: [TransWordData('nattero')]),
    ned: TransLangData(TransWordData('avondklok')),
  ),
  TransData(MdiIcons.whiteBalanceSunny,
    TransLangData(TransWordData('cisza poobiednia')),
    mug: TransLangData(TransWordData('czas po obiedzie, wolny od zajęć, przeznaczony na odpoczynek')),
    eng: TransLangData(TransWordData('rest hours')),
    ger: TransLangData(TransWordData('Nachmittagsruhe', prefix: 'die')),
    esp: TransLangData(TransWordData('horas de descanso')),
    ita: TransLangData(TransWordData('attività tempo libero')),
    cze: TransLangData(TransWordData('poledňak')),
    nor: TransLangData(TransWordData('stillhet etter middagen')),
    ned: TransLangData(TransWordData('rusttijd')),
  ),
  TransData(MdiIcons.pickaxe,
    TransLangData(TransWordData('czekan')),
    mug: TransLangData(TransWordData('rodzaj laski ze stalową głowicą i kolcem, używanej przez alpinistów do rąbania stopni w śniegu i lodzie')),
    eng: TransLangData(TransWordData('ice axe')),
    ger: TransLangData(TransWordData('Eispickel', prefix: 'der')),
    esp: TransLangData(TransWordData('hacha de hielo')),
    ita: TransLangData(TransWordData('picozza')),
    cze: TransLangData(TransWordData('čakan')),
    nor: TransLangData(TransWordData('isøks', prefix: 'en')),
    ned: TransLangData(TransWordData('ijsbijl')),
  ),
  TransData(MdiIcons.televisionAmbientLight,
    TransLangData(TransWordData('czołówka')),
    mug: TransLangData(TransWordData('latarka zakładana na głowę')),
    eng: TransLangData(TransWordData('head torch')),
    ger: TransLangData(TransWordData('Stirnlampe', prefix: 'die')),
    esp: TransLangData(TransWordData('antorcha'), alt: [TransWordData('linterna', literalTrans: 'latarka')]),
    ita: TransLangData(TransWordData('torcia frontale')),
    cze: TransLangData(TransWordData('čelovka')),
    nor: TransLangData(TransWordData('hodelykt', prefix: 'en')),
    ned: TransLangData(TransWordData('koplamp')),
  ),
  TransData(MdiIcons.accountHardHat,
    TransLangData(TransWordData('depionierka'), alt: [TransWordData('repionierka')]),
    mug: TransLangData(TransWordData('proces składania sprzętu obozowego i rozmontowywania uprzednio zbudownych konstrukcji obozowych (kuchnia, prycze, latryny, prysznice, etc.) przed wyjazdem z obozu')),
    eng: TransLangData(TransWordData('camp dismantling')),
    ger: TransLangData(TransWordData('Lagerabbau', prefix: 'der')),
    esp: TransLangData(TransWordData('desmontar el campamento')),
    ita: TransLangData(TransWordData('smontaggio')),
    cze: TransLangData(TransWordData('bourání')),
    nor: TransLangData(TransWordData('demontere', prefix: 'å')),
    ned: TransLangData(TransWordData('kamp opruimen')),
  ),
  TransData(MdiIcons.accountGroup,
    TransLangData(TransWordData('drużyna')),
    mug: TransLangData(TransWordData('podstawowa jednostka harcerska, na czele z jej przełożonym, drużynowym')),
    eng: TransLangData(TransWordData('scout team')),
    ger: TransLangData(TransWordData('Pfadfindergruppe', prefix: 'die')),
    esp: TransLangData(TransWordData('patrulla scout')),
    ita: TransLangData(TransWordData('branco')),
    cze: TransLangData(TransWordData('oddíl')),
    nor: TransLangData(TransWordData('gruppe', prefix: 'en'), alt: [TransWordData('enhet', prefix: 'en')]),
    ned: TransLangData(TransWordData('scout groep')),
  ),
  TransData(MdiIcons.accountCowboyHat,
    TransLangData(TransWordData('drużynowy')),
    mug: TransLangData(TransWordData('osoba stojąca na czele drużyny, najczęściej instruktor harcerski')),
    eng: TransLangData(TransWordData('scout leader')),
    ger: TransLangData(TransWordData('Pfadfindergruppenleiter', prefix: 'der')),
    esp: TransLangData(TransWordData('guía de patrulla')),
    ita: TransLangData(TransWordData('capo branco')),
    cze: TransLangData(TransWordData('vůdce')),
    nor: TransLangData(TransWordData('gruppeleder', prefix: 'en')),
    ned: TransLangData(TransWordData('hopvrouw'), alt: [TransWordData('hopman')]),
  ),
  TransData(MdiIcons.cashCheck,
    TransLangData(TransWordData('faktura')),
    mug: TransLangData(TransWordData('pisemny dowód transakcji kupna i sprzedaży lub wykonania jakiejś usługi, będący podstawą rozliczenia')),
    eng: TransLangData(TransWordData('invoice')),
    ger: TransLangData(TransWordData('Rechnung', prefix: 'die')),
    esp: TransLangData(TransWordData('factura')),
    ita: TransLangData(TransWordData('fattura')),
    cze: TransLangData(TransWordData('faktura')),
    nor: TransLangData(TransWordData('faktura', prefix: 'en')),
    ned: TransLangData(TransWordData('rekening'), alt: [TransWordData('factuur')]),
  ),
  TransData(MdiIcons.fireExtinguisher,
    TransLangData(TransWordData('gaśnica')),
    mug: TransLangData(TransWordData('przenośny przyrząd do gaszenia pożaru')),
    eng: TransLangData(TransWordData('fire extinguisher')),
    ger: TransLangData(TransWordData('der Feuerlöscher', prefix: 'der')),
    esp: TransLangData(TransWordData('extintor')),
    ita: TransLangData(TransWordData('estintore')),
    cze: TransLangData(TransWordData('hasicí přístoj')),
    nor: TransLangData(TransWordData('brannslokkingsapparat', prefix: 'et')),
    ned: TransLangData(TransWordData('brandblusser')),
  ),
  TransData(MdiIcons.starCircle,
    TransLangData(TransWordData('Główna Kwatera')),
    mug: TransLangData(TransWordData('Najwyżej znajdująca się w strukturze harcerstwa jednostka, koordynująca działania Związku Harcerstwa Polskiego')),
    eng: TransLangData(TransWordData('Headquarters')),
    ger: TransLangData(TransWordData('Hauptquartier', prefix: 'das')),
    esp: TransLangData(TransWordData('Sede')),
    ita: TransLangData(TransWordData('Nazionale')),
    cze: TransLangData(TransWordData('Statní organizace')),
    nor: TransLangData(TransWordData('Speiderstyret')),
    ned: TransLangData(TransWordData('hoofdkwartier')),
  ),
  TransData(MdiIcons.accountTieOutline,
    TransLangData(TransWordData('harcerz')),
    mug: TransLangData(TransWordData('członek organizacji harcerskiej')),
    eng: TransLangData(TransWordData('scout', literalTrans: 'skaut')),
    ger: TransLangData(TransWordData('pfadfinder', prefix: 'der', literalTrans: 'skaut')),
    esp: TransLangData(TransWordData('scout', literalTrans: 'skaut')),
    ita: TransLangData(TransWordData('scout')),
    cze: TransLangData(TransWordData('skaut'), alt: [TransWordData('junák')]),
    nor: TransLangData(TransWordData('speider', prefix: 'en')),
    ned: TransLangData(TransWordData('scout'), alt: [TransWordData('padvinder')]),
  ),
  TransData(MdiIcons.home,
    TransLangData(TransWordData('harcówka')),
    mug: TransLangData(TransWordData('pomieszczenie przeznaczone na miejsce spotkań harcerskich')),
    eng: TransLangData(TransWordData('scout room'), alt: [TransWordData('scout place')]),
    ger: TransLangData(TransWordData('Versammlungsraum', prefix: 'der')),
    esp: TransLangData(TransWordData('casa scout')),
    ita: TransLangData(TransWordData('sede')),
    cze: TransLangData(TransWordData('klubovna')),
    nor: TransLangData(TransWordData('speiders rom', prefix: 'et')),
    ned: TransLangData(TransWordData('scout kamer')),
  ),
  TransData(MdiIcons.accountSwitch,
    TransLangData(TransWordData('hufiec')),
    mug: TransLangData(TransWordData('jednostka harcerska zrzeszająca drużyny i szczepy działające na tym samym terenie (dzielnicy, mieście etc.)')),
    eng: TransLangData(TransWordData('scout district', literalTrans: 'dystrykt skautowy')),
    ger: TransLangData(TransWordData('Bezirksverband', prefix: 'der')),
    esp: TransLangData(TransWordData('distrito')),
    ita: TransLangData(TransWordData('zona')),
    cze: TransLangData(TransWordData('středisko')),
    nor: TransLangData(TransWordData('instruktør', prefix: 'en')),
    ned: TransLangData(TransWordData('(scout) buurt')),
  ),
  TransData(MdiIcons.waterOff,
    TransLangData(TransWordData('impregnować')),
    mug: TransLangData(TransWordData('uwodoodparniać')),
    eng: TransLangData(TransWordData('waterproof', suff: 'sth', prefix: 'to')),
    ger: TransLangData(TransWordData('imprägnieren')),
    esp: TransLangData(TransWordData('impregnar')),
    ita: TransLangData(TransWordData('impregnare')),
    cze: TransLangData(TransWordData('impregnovat')),
    nor: TransLangData(TransWordData('impregnere', prefix: 'å')),
    ned: TransLangData(TransWordData('impregneren')),
  ),
  TransData(MdiIcons.bed,
    TransLangData(TransWordData('kanadyjka'), alt: [TransWordData('polówka')]),
    mug: TransLangData(TransWordData('przenośne, najczęściej drewniane łóżko polowe')),
    eng: TransLangData(TransWordData('camp bed')),
    ger: TransLangData(TransWordData('Feldbett', prefix: 'das')),
    esp: TransLangData(TransWordData('cama de dormir')),
    ita: TransLangData(TransWordData('brandina smontabile')),
    cze: TransLangData(TransWordData('kempinkové lehátko')),
    nor: TransLangData(TransWordData('feltseng', prefix: 'en')),
    ned: TransLangData(TransWordData('legerbed'), alt: [TransWordData('veldbed')]),
  ),
  TransData(MdiIcons.cross,
    TransLangData(TransWordData('kapelan')),
    mug: TransLangData(TransWordData('ksiądz harcerski')),
    eng: TransLangData(TransWordData('chaplain')),
    ger: TransLangData(TransWordData('Kaplan', prefix: 'der')),
    esp: TransLangData(TransWordData('cadellán')),
    ita: TransLangData(TransWordData('cappellano')),
    cze: TransLangData(TransWordData('kaplan')),
    nor: TransLangData(TransWordData('feltprest', prefix: 'en'), alt: [TransWordData('kapellan', prefix: 'en')]),
    ned: TransLangData(TransWordData('kapelaan')),
  ),
  TransData(MdiIcons.squareOutline,
    TransLangData(TransWordData('karimata')),
    mug: TransLangData(TransWordData('zwijana lub składana mata przeznaczona do snu izolująca od podłoża')),
    eng: TransLangData(TransWordData('mat'), alt: [TransWordData('sleeping pad')]),
    ger: TransLangData(TransWordData('Isomatte', prefix: 'die')),
    esp: TransLangData(TransWordData('esterilla')),
    ita: TransLangData(TransWordData('materassino')),
    cze: TransLangData(TransWordData('karimatka')),
    nor: TransLangData(TransWordData('et skumunderlag', prefix: 'et'), alt: [TransWordData('liggeunderlag', prefix: 'et')]),
    ned: TransLangData(TransWordData('slaapmat')),
  ),
  TransData(MdiIcons.pot,
    TransLangData(TransWordData('kociołek')),
    mug: TransLangData(TransWordData('duży garnek służący do przyrządzania jedzenia, zwykle mogący być postawiony na ogniu')),
    eng: TransLangData(TransWordData('pot')),
    ger: TransLangData(TransWordData('Kessel', prefix: 'der')),
    esp: TransLangData(TransWordData('bote')),
    ita: TransLangData(TransWordData('calderone')),
    cze: TransLangData(TransWordData('kotlík')),
    nor: TransLangData(TransWordData('kjele', prefix: 'et')),
    ned: TransLangData(TransWordData('ketel')),
  ),
  TransData(MdiIcons.accountMultiplePlus,
    TransLangData(TransWordData('komenda', example: 'hufca, chorągwi')),
    mug: TransLangData(TransWordData('instruktorzy harcerscy koordynujący działaniem powierzonej im jednostki harcerskiej')),
    eng: TransLangData(TransWordData('executive committee')),
    ger: TransLangData(TransWordData('Vorstand', prefix: 'der')),
    esp: TransLangData(TransWordData('comendancia')),
    ita: TransLangData(TransWordData('comitato')),
    cze: TransLangData(TransWordData('rada')),
    nor: TransLangData(TransWordData('kommando', prefix: 'en')),
    ned: TransLangData(TransWordData('bestuur')),
  ),
  TransData(MdiIcons.accountStar,
    TransLangData(TransWordData('komendant')),
    mug: TransLangData(TransWordData('osoba koordynująca działania powierzonej mu jednostki')),
    eng: TransLangData(TransWordData('commissioner')),
    ger: TransLangData(TransWordData('Kommandant', prefix: 'der')),
    esp: TransLangData(TransWordData('jefe')),
    ita: TransLangData(TransWordData('incaricato')),
    cze: TransLangData(TransWordData('vůdce')),
    nor: TransLangData(TransWordData('kommandant', prefix: 'en'), alt: [TransWordData('leder', prefix: 'en')]),
    ned: TransLangData(TransWordData('commandant')),
  ),
  TransData(MdiIcons.accountStar,
    TransLangData(TransWordData('komendant obozu')),
    mug: TransLangData(TransWordData('osoba koordynująca organizację i przebieg obozu harcerskiego')),
    eng: TransLangData(TransWordData('camp leader')),
    ger: TransLangData(TransWordData('Pfadfinderlagerkommandant', prefix: 'der')),
    esp: TransLangData(TransWordData('comandante del campo')),
    ita: TransLangData(TransWordData('comandante del campo')),
    cze: TransLangData(TransWordData('velitel tábora')),
    nor: TransLangData(TransWordData('leirkommandant', prefix: 'en')),
    ned: TransLangData(TransWordData('kamp Leider')),
  ),
  TransData(MdiIcons.accountKey,
    TransLangData(TransWordData('komendant chorągwi')),
    mug: TransLangData(TransWordData('osoba koordynująca działaniem chorągwi')),
    eng: TransLangData(TransWordData('region commissioner')),
    ger: TransLangData(TransWordData('Landesvorsitzende', prefix: 'der')),
    esp: TransLangData(TransWordData('jefe de la región')),
    ita: TransLangData(TransWordData('incaricato regionale')),
    cze: TransLangData(TransWordData('krajský předseda')),
    nor: TransLangData(TransWordData('kretsleder', prefix: 'en'), alt: [TransWordData('krets ledelse', prefix: 'en')]),
    ned: TransLangData(TransWordData('gebied commandant')),
  ),
  TransData(MdiIcons.accountKeyOutline,
    TransLangData(TransWordData('komendant hufca')),
    mug: TransLangData(TransWordData('osoba koordynująca działaniem hufca')),
    eng: TransLangData(TransWordData('district commissioner')),
    ger: TransLangData(TransWordData('Bezirksvorsitzende', prefix: 'der')),
    esp: TransLangData(TransWordData('jefe de distrito')),
    ita: TransLangData(TransWordData('incaricato zona')),
    cze: TransLangData(TransWordData('vůdce střediska')),
    nor: null,
    ned: TransLangData(TransWordData('buurt commandant')),
  ),
  TransData(MdiIcons.accountMusic,
    TransLangData(TransWordData('komendant szczepu')),
    mug: TransLangData(TransWordData('osoba koordynująca działaniem szczepu')),
    eng: TransLangData(TransWordData('scout-teams group leader')),
    ger: TransLangData(TransWordData('Stammesvorsitzende', prefix: 'der')),
    esp: TransLangData(TransWordData('jefe del batallón')),
    ita: TransLangData(TransWordData('capo gruppo')),
    cze: TransLangData(TransWordData('vůdce spolka')),
    nor: null,
    ned: TransLangData(TransWordData('groep leider')),
  ),
  TransData(MdiIcons.accountMultiple,
    TransLangData(TransWordData('komisja')),
    mug: TransLangData(TransWordData('zespół osób powołanych do wykonania określonych zadań')),
    eng: TransLangData(TransWordData('committee')),
    ger: TransLangData(TransWordData('Kommission', prefix: 'die')),
    esp: TransLangData(TransWordData('comité')),
    ita: TransLangData(TransWordData('commissione')),
    cze: TransLangData(TransWordData('komise')),
    nor: TransLangData(TransWordData('kommisjon', prefix: 'en')),
    ned: TransLangData(TransWordData('commissie')),
  ),
  TransData(MdiIcons.chevronDoubleUp,
    TransLangData(TransWordData('komisja stopni')),
    mug: TransLangData(TransWordData('komisja zajmująca się otwieraniem, zamykaniem i niekiedy przyznawaniem stopni harcerskich lub/i instruktorskich')),
    eng: TransLangData(TransWordData('ranks committee')),
    ger: TransLangData(TransWordData('Stufenkommission', prefix: 'die')),
    esp: TransLangData(TransWordData('comité rangos')),
    ita: TransLangData(TransWordData('commissione dei gradi')),
    cze: TransLangData(TransWordData('urovňová komise')),
    nor: TransLangData(TransWordData('gradkommisjon', prefix: 'en')),
    ned: TransLangData(TransWordData('rang commisie')),
  ),
  TransData(MdiIcons.bagPersonal,
    TransLangData(TransWordData('komora plecaka')),
    mug: TransLangData(TransWordData('wydzielona przestrzeń pakunkowa plecaka')),
    eng: TransLangData(TransWordData('compartment')),
    ger: TransLangData(TransWordData('Rucksackkammer', prefix: 'die')),
    esp: TransLangData(TransWordData('compartimento')),
    ita: TransLangData(TransWordData('compartimento')),
    cze: TransLangData(TransWordData('vnitřek bathou')),
    nor: TransLangData(TransWordData('ryggsekkrom', prefix: 'en')),
    ned: TransLangData(TransWordData('compartiment')),
  ),
  TransData(MdiIcons.accountSupervisorCircle,
    TransLangData(TransWordData('krąg')),
    mug: TransLangData(TransWordData('lokalna jednostka zrzeszająca harcerzy o tym samym profilu (np. studentów, instruktorów)')),
    eng: TransLangData(TransWordData('scout club')),
    ger: TransLangData(TransWordData('Kreis', prefix: 'der')),
    esp: TransLangData(TransWordData('scouts')),
    ita: TransLangData(TransWordData('cerchio')),
    cze: TransLangData(TransWordData('kruh')),
    nor: TransLangData(TransWordData('krets', prefix: 'en')),
    ned: TransLangData(TransWordData('scout club')),
  ),
  TransData(MdiIcons.accountSupervisorCircle,
    TransLangData(TransWordData('krąg instruktorski')),
    mug: TransLangData(TransWordData('lokalna jednostka zrzeszająca instruktorów harcerskich')),
    eng: TransLangData(TransWordData("scouters and guiders' club")),
    ger: TransLangData(TransWordData('Leiterkreis', prefix: 'der')),
    esp: TransLangData(TransWordData('scouters')),
    ita: TransLangData(TransWordData('comunità capi')),
    cze: TransLangData(TransWordData('středisková rada')),
    nor: TransLangData(TransWordData('instruktørkrets', prefix: 'en')),
    ned: TransLangData(TransWordData('scouting')),
  ),
  TransData(MdiIcons.gasCylinder,
    TransLangData(TransWordData('kuchenka turystyczna')),
    mug: TransLangData(TransWordData('element ekwipunku turystycznego służący do gotowania')),
    eng: TransLangData(TransWordData('stove'), alt: [TransWordData('gas stove')]),
    ger: TransLangData(TransWordData('Gasbrenner', prefix: 'der')),
    esp: TransLangData(TransWordData('cocina turística')),
    ita: TransLangData(TransWordData('fornello da campeggio')),
    cze: TransLangData(TransWordData('polní vařič')),
    nor: TransLangData(TransWordData('stormkjøkken', prefix: 'et'), alt: [TransWordData('turkjøkken', prefix: 'et')]),
    ned: TransLangData(TransWordData('kampeerkooktoestellen')),
  ),
  TransData(MdiIcons.tree,
    TransLangData(TransWordData('Las')),
    mug: TransLangData(TransWordData('teren charakteryzujący się zwartą roślinnością z przewagą drzew')),
    eng: TransLangData(TransWordData('forest')),
    ger: TransLangData(TransWordData('Wald', prefix: 'der')),
    esp: TransLangData(TransWordData('bosque')),
    ita: TransLangData(TransWordData('bosco')),
    cze: TransLangData(TransWordData('les')),
    nor: TransLangData(TransWordData('skog', prefix: 'en')),
    ned: TransLangData(TransWordData('bos')),
  ),
  TransData(MdiIcons.flashlight,
    TransLangData(TransWordData('latarka')),
    mug: TransLangData(TransWordData('nieduże, przenośne urządzenie na baterie, dające światło')),
    eng: TransLangData(TransWordData('torch')),
    ger: TransLangData(TransWordData('Taschenlampe', prefix: 'die')),
    esp: TransLangData(TransWordData('linterna')),
    ita: TransLangData(TransWordData('torcia elettrica')),
    cze: TransLangData(TransWordData('baterku')),
    nor: TransLangData(TransWordData('lommelykt', prefix: 'en')),
    ned: TransLangData(TransWordData('zaklamp')),
  ),
  TransData(MdiIcons.toilet,
    TransLangData(TransWordData('latryna')),
    mug: TransLangData(TransWordData('toaleta leśna w postaci zabudowanej dziury wykopanej w ziemi')),
    eng: TransLangData(TransWordData('latrine')),
    ger: TransLangData(TransWordData('Plumpsklo', prefix: 'das'), alt: [TransWordData('Latrine', prefix: 'die')]),
    esp: TransLangData(TransWordData('letrina')),
    ita: TransLangData(TransWordData('latrina')),
    cze: TransLangData(TransWordData('latrína')),
    nor: TransLangData(TransWordData('latrine', prefix: 'en')),
    ned: TransLangData(TransWordData('latrine'), alt: [TransWordData('hudo')]),
  ),
  TransData(MdiIcons.binoculars,
    TransLangData(TransWordData('lornetka')),
    mug: TransLangData(TransWordData('przyrząd optyczny ułatwiający oglądanie obojgiem oczu oddalonych przedmiotów poprzez ich optyczne powiększenie')),
    eng: TransLangData(TransWordData('binoculars')),
    ger: TransLangData(TransWordData('Fernglas', prefix: 'das')),
    esp: TransLangData(TransWordData('prismáticos')),
    ita: TransLangData(TransWordData('binocolo')),
    cze: TransLangData(TransWordData('dalekohled')),
    nor: TransLangData(TransWordData('kikkert', prefix: 'en')),
    ned: TransLangData(TransWordData('verrekijker')),
  ),
  TransData(MdiIcons.store,
    TransLangData(TransWordData('magazyn')),
    mug: TransLangData(TransWordData('miejsce przeznaczone do przechowywania sprzętu harcerskiego, np. namiotów, materaców, palników, siekier, łopat, etc.')),
    eng: TransLangData(TransWordData('store')),
    ger: TransLangData(TransWordData('Abstellraum', prefix: 'der'), alt: [TransWordData('Lagerkammer', prefix: 'die')]),
    esp: TransLangData(TransWordData('almacén')),
    ita: TransLangData(TransWordData('magazzino')),
    cze: TransLangData(TransWordData('sklad')),
    nor: TransLangData(TransWordData('lager', prefix: 'et')),
    ned: TransLangData(TransWordData('magazijn')),
  ),
  TransData(MdiIcons.map,
    TransLangData(TransWordData('mapa')),
    mug: TransLangData(TransWordData('uproszczony obraz powierzchni jakiegoś obszaru przedstawiony na płaszczyźnie za pomocą umownych znaków i kolorów')),
    eng: TransLangData(TransWordData('map')),
    ger: TransLangData(TransWordData('Landkarte', prefix: 'die')),
    esp: TransLangData(TransWordData('mapa')),
    ita: TransLangData(TransWordData('carta geografica')),
    cze: TransLangData(TransWordData('mapa')),
    nor: TransLangData(TransWordData('kart', prefix: 'et')),
    ned: TransLangData(TransWordData('kaart')),
  ),
  TransData(MdiIcons.mapLegend,
    TransLangData(TransWordData('mapnik')),
    mug: TransLangData(TransWordData('woodoodporne opakowanie na mapę chroniące ją od deszczu')),
    eng: TransLangData(TransWordData('map case')),
    ger: TransLangData(TransWordData('Landkartentasche', prefix: 'die')),
    esp: null,
    ita: TransLangData(TransWordData('custodia impermeabile per mappe')),
    cze: TransLangData(TransWordData('vodotěsné pouzdro na mapu')),
    nor: TransLangData(TransWordData('kortholder', prefix: 'en')),
    ned: TransLangData(TransWordData('kaartentas')),
  ),
  TransData(MdiIcons.tree,
    TransLangData(TransWordData('maskować')),
    mug: TransLangData(TransWordData('utrudniać widoczność')),
    eng: TransLangData(TransWordData('screen', prefix: 'to', suff: 'sth')),
    ger: TransLangData(TransWordData('tarnen'), alt: [TransWordData('maskieren')]),
    esp: TransLangData(TransWordData('enmascarar')),
    ita: TransLangData(TransWordData('mascherare')),
    cze: TransLangData(TransWordData('maskovat')),
    nor: TransLangData(TransWordData('maskere', prefix: 'å')),
    ned: TransLangData(TransWordData('camoufleren')),
  ),
  TransData(MdiIcons.flag,
    TransLangData(TransWordData('maszt do flagi')),
    mug: TransLangData(TransWordData('wysoki słup, na którym może wisieć flaga')),
    eng: TransLangData(TransWordData('flag pole')),
    ger: TransLangData(TransWordData('Fahnenmast', prefix: 'der')),
    esp: TransLangData(TransWordData('asta de banderas')),
    ita: TransLangData(TransWordData('asta di bandiera')),
    cze: TransLangData(TransWordData('stožár')),
    nor: TransLangData(TransWordData('flaggstang', prefix: 'en')),
    ned: TransLangData(TransWordData('vlaggenmast')),
  ),
  TransData(MdiIcons.tent,
    TransLangData(TransWordData('maszt do namiotu')),
    mug: TransLangData(TransWordData('słup, który stojąc pionowo podtrzymuje namiot')),
    eng: TransLangData(TransWordData('tent pole')),
    ger: TransLangData(TransWordData('Zeltmast', prefix: 'der')),
    esp: TransLangData(TransWordData('mástil de tienda de campaña')),
    ita: TransLangData(TransWordData('paletto')),
    cze: TransLangData(TransWordData('stanová tyčka')),
    nor: TransLangData(TransWordData('teltmast', prefix: 'en')),
    ned: TransLangData(TransWordData('tentpaal')),
  ),
  TransData(MdiIcons.pot,
    TransLangData(TransWordData('menażka')),
    mug: TransLangData(TransWordData('polowe naczynie służące do jedzenia, najczęściej z metalu lub tworzywa sztucznego')),
    eng: TransLangData(TransWordData('mess tin'), alt: [TransWordData('mess kit')]),
    ger: TransLangData(TransWordData('Essgeschirr', prefix: 'das')),
    esp: TransLangData(TransWordData('fiamberera')),
    ita: TransLangData(TransWordData('gavetta')),
    cze: TransLangData(TransWordData('ešus')),
    nor: TransLangData(TransWordData('tallerkensett', prefix: 'et')),
    ned: TransLangData(TransWordData('gamel')),
  ),
  TransData(MdiIcons.tshirtCrew,
    TransLangData(TransWordData('mundur harcerski')),
    mug: TransLangData(TransWordData('oficjalny, reprezentacyjny strój harcerski')),
    eng: TransLangData(TransWordData('scout uniform')),
    ger: TransLangData(TransWordData('Pfadfinderuniform', prefix: 'die'), alt: [TransWordData('Pfadfinderkluft', prefix: 'die')]),
    esp: TransLangData(TransWordData('uniforme scout')),
    ita: TransLangData(TransWordData('uniforme scout')),
    cze: TransLangData(TransWordData('skautský kroj')),
    nor: TransLangData(TransWordData('speiderdrakt', prefix: 'en')),
    ned: TransLangData(TransWordData('scout uniform')),
  ),
  TransData(MdiIcons.tent,
    TransLangData(TransWordData('namiot')),
    mug: TransLangData(TransWordData('przenośne schronienie z impregnowanej tkaniny, rozpinanej na specjalnym rusztowaniu, mające kształt małego domku lub stożka')),
    eng: TransLangData(TransWordData('tent')),
    ger: TransLangData(TransWordData('Zelt', prefix: 'das')),
    esp: TransLangData(TransWordData('tienda de campaña')),
    ita: TransLangData(TransWordData('tenda')),
    cze: TransLangData(TransWordData('stan')),
    nor: TransLangData(TransWordData('telt', prefix: 'en')),
    ned: TransLangData(TransWordData('tent')),
  ),
  TransData(MdiIcons.silverwareForkKnife,
    TransLangData(TransWordData('niezbędnik', explain: 'sztućće')),
    mug: TransLangData(TransWordData('zestaw sztućców polowych lub jeden sztuciec łączący w sobie funkcję kilku')),
    eng: TransLangData(TransWordData('cutlery set')),
    ger: TransLangData(TransWordData('Besteck', prefix: 'das')),
    esp: TransLangData(TransWordData('cubiertos')),
    ita: TransLangData(TransWordData('posate da campeggio')),
    cze: TransLangData(TransWordData('příbory')),
    nor: TransLangData(TransWordData('turbestikk', prefix: 'en')),
    ned: TransLangData(TransWordData('bestek set')),
  ),
  TransData(MdiIcons.weatherNight,
    TransLangData(TransWordData('nocleg pod gołym niebem')),
    mug: TransLangData(TransWordData('nocleg pod gołym niebem to nocleg pod gołym niebem')),
    eng: TransLangData(TransWordData('bivouac')),
    ger: TransLangData(TransWordData('Übernachtung unter freiem Himmel', prefix: 'die')),
    esp: TransLangData(TransWordData('vivaque')),
    ita: TransLangData(TransWordData('dormire sotto le stelle')),
    cze: TransLangData(TransWordData('spaní pod širákem')),
    nor: TransLangData(TransWordData('overnatting i friluft')),
    ned: TransLangData(TransWordData('bivak')),
  ),
  TransData(MdiIcons.tent,
    TransLangData(TransWordData('obóz harcerski')),
    mug: TransLangData(TransWordData('forma zorganizowanego wypoczynku harcerzy, zwykle w lesie, pod namiotami')),
    eng: TransLangData(TransWordData('scout camp')),
    ger: TransLangData(TransWordData('Pfadfinderlager', prefix: 'das')),
    esp: TransLangData(TransWordData('campamento de exploración')),
    ita: TransLangData(TransWordData('campo scout')),
    cze: TransLangData(TransWordData('skautský tábor')),
    nor: TransLangData(TransWordData('speiderleir', prefix: 'en')),
    ned: TransLangData(TransWordData('scouting kamp')),
  ),
  TransData(MdiIcons.tent,
    TransLangData(TransWordData('obóz letni')),
    mug: TransLangData(TransWordData('dłuższy, letni wyjazd harcerski (zwykle od ok. 1 do 3 tygodni)')),
    eng: TransLangData(TransWordData('summer camp')),
    ger: TransLangData(TransWordData('Pfadfindersommerlager', prefix: 'das')),
    esp: TransLangData(TransWordData('campamento de verano')),
    ita: TransLangData(TransWordData('campo estivo')),
    cze: TransLangData(TransWordData('letní tábor')),
    nor: TransLangData(TransWordData('sommerleir', prefix: 'en')),
    ned: TransLangData(TransWordData('zomerkamp')),
  ),
  TransData(MdiIcons.accountMultipleCheck,
    TransLangData(TransWordData('odprawa')),
    mug: TransLangData(TransWordData('spotkanie służące przekazaniu informacji szefom podległych jednostek lub komendzie')),
    eng: TransLangData(TransWordData('brief')),
    ger: TransLangData(TransWordData('Befehlsausgabe', prefix: 'die'), alt: [TransWordData('Besprechung', prefix: 'die')]),
    esp: TransLangData(TransWordData('despacho')),
    ita: TransLangData(TransWordData('riunione')),
    cze: TransLangData(TransWordData('rada')),
    nor: TransLangData(TransWordData('møte', prefix: 'en')),
    ned: TransLangData(TransWordData('briefing')),
  ),
  TransData(MdiIcons.fire,
    TransLangData(TransWordData('ogień')),
    mug: TransLangData(TransWordData('płomienie i żar powstające podczas palenia')),
    eng: TransLangData(TransWordData('fire')),
    ger: TransLangData(TransWordData('Feuer', prefix: 'das')),
    esp: TransLangData(TransWordData('fuego')),
    ita: TransLangData(TransWordData('fuoco')),
    cze: TransLangData(TransWordData('oheň')),
    nor: TransLangData(TransWordData('ild', prefix: 'en')),
    ned: TransLangData(TransWordData('vuur')),
  ),
  TransData(MdiIcons.campfire,
    TransLangData(TransWordData('ognisko')),
    mug: TransLangData(TransWordData('stos drewna, chrustu itp. zapalony pod gołym niebem')),
    eng: TransLangData(TransWordData('campfire')),
    ger: TransLangData(TransWordData('Lagerfeuer', prefix: 'das')),
    esp: TransLangData(TransWordData('fuego de campamento')),
    ita: TransLangData(TransWordData('falò')),
    cze: TransLangData(TransWordData('ohnisko')),
    nor: TransLangData(TransWordData('bål', prefix: 'en')),
    ned: TransLangData(TransWordData('kampvuur')),
  ),
  TransData(MdiIcons.scanner,
    TransLangData(TransWordData('otwieracz do konserw')),
    mug: TransLangData(TransWordData('przyrząd do otwierania konserw zapakowanych w puszki')),
    eng: TransLangData(TransWordData('can-opener')),
    ger: TransLangData(TransWordData('Dosenöffner', prefix: 'der')),
    esp: TransLangData(TransWordData('abrelatas')),
    ita: TransLangData(TransWordData('apriscatole')),
    cze: TransLangData(TransWordData('otvírák na konzervy')),
    nor: TransLangData(TransWordData('boksåpner', prefix: 'en')),
    ned: TransLangData(TransWordData('blikopener')),
  ),
  TransData(MdiIcons.minus,
    TransLangData(TransWordData('palik')),
    mug: TransLangData(TransWordData('drewniany słupek')),
    eng: TransLangData(TransWordData('stake')),
    ger: TransLangData(TransWordData('Pfahl', prefix: 'der')),
    esp: TransLangData(TransWordData('pilar')),
    ita: TransLangData(TransWordData('palo')),
    cze: TransLangData(TransWordData('kůl')),
    nor: TransLangData(TransWordData('pæl', prefix: 'en')),
    ned: TransLangData(TransWordData('paal')),
  ),
  TransData(MdiIcons.fire,
    TransLangData(TransWordData('palnik')),
    mug: TransLangData(TransWordData('element ekwipunku turystycznego służący do spalania paliwa (gazu, denaturatu, benzyny, etc.) celem wytworzenia ciepła np. do gotowania')),
    eng: TransLangData(TransWordData('burner')),
    ger: TransLangData(TransWordData('Brenner', prefix: 'der')),
    esp: TransLangData(TransWordData('quemador')),
    ita: TransLangData(TransWordData('bruciatore')),
    cze: TransLangData(TransWordData('vařič')),
    nor: TransLangData(TransWordData('gassbrenner')),
    ned: TransLangData(TransWordData('brander')),
  ),
  TransData(MdiIcons.tableOfContents,
    TransLangData(TransWordData('paragon')),
    mug: TransLangData(TransWordData('kwit z bloczka kasowego, stanowiący dowód zapłaty za kupiony towar')),
    eng: TransLangData(TransWordData('receipt')),
    ger: TransLangData(TransWordData('Kassenzettel', prefix: 'der')),
    esp: TransLangData(TransWordData('tickquet'), alt: [TransWordData('Factura'), TransWordData('Recibo')]),
    ita: TransLangData(TransWordData('scontrino')),
    cze: TransLangData(TransWordData('paragon')),
    nor: TransLangData(TransWordData('kvittering', prefix: 'en')),
    ned: TransLangData(TransWordData('kassabon')),
  ),
  TransData(MdiIcons.octagram,
    TransLangData(TransWordData('plakietka')),
    mug: TransLangData(TransWordData('mała tabliczka lub naszywka pełniąca funkcję identyfikacyjną lub pamiątkową')),
    eng: TransLangData(TransWordData('badge')),
    ger: TransLangData(TransWordData('Abzeichen', prefix: 'das')),
    esp: TransLangData(TransWordData('insignia')),
    ita: TransLangData(TransWordData('distintivo')),
    cze: TransLangData(TransWordData('odznak')),
    nor: TransLangData(TransWordData('speidermerke', prefix: 'et')),
    ned: TransLangData(TransWordData('badge')),
  ),
  TransData(MdiIcons.square,
    TransLangData(TransWordData('plandeka')),
    mug: TransLangData(TransWordData('zwykle duży, wodoodporny materiał')),
    eng: TransLangData(TransWordData('tarpaulin')),
    ger: TransLangData(TransWordData('Plane', prefix: 'die')),
    esp: TransLangData(TransWordData('lona')),
    ita: TransLangData(TransWordData('telone')),
    cze: TransLangData(TransWordData('plachta')),
    nor: TransLangData(TransWordData('tarp', prefix: 'en')),
    ned: TransLangData(TransWordData('zeil')),
  ),
  TransData(MdiIcons.bagPersonal,
    TransLangData(TransWordData('plecak')),
    mug: TransLangData(TransWordData('torba noszona na plecach')),
    eng: TransLangData(TransWordData('backpack')),
    ger: TransLangData(TransWordData('Rucksack', prefix: 'die')),
    esp: TransLangData(TransWordData('mochila')),
    ita: TransLangData(TransWordData('zaino')),
    cze: TransLangData(TransWordData('batoh')),
    nor: TransLangData(TransWordData('ryggsekk', prefix: 'en'), alt: [TransWordData('speidersekken', prefix: 'en')]),
    ned: TransLangData(TransWordData('rugzak')),
  ),
  TransData(MdiIcons.tent,
    TransLangData(TransWordData('podobóz')),
    mug: TransLangData(TransWordData('obóz konkretnej jednostki harcerskiej uczestniczący w zgrupowaniu wielu jednostek')),
    eng: TransLangData(TransWordData("unit's camp")),
    ger: TransLangData(TransWordData('Nebenlager', prefix: 'der')),
    esp: TransLangData(TransWordData('subcampamento')),
    ita: TransLangData(TransWordData('sottocampo')),
    cze: TransLangData(TransWordData('tábořiště')),
    nor: TransLangData(TransWordData('underleir', prefix: 'en')),
    ned: TransLangData(TransWordData('subkamp')),
  ),
  TransData(MdiIcons.tent,
    TransLangData(TransWordData('poła')),
    mug: TransLangData(TransWordData('płachta zasłaniająca wejście namiotu')),
    eng: TransLangData(TransWordData('flap')),
    ger: TransLangData(TransWordData('Zeltklappe', prefix: 'die')),
    esp: TransLangData(TransWordData('solapa')),
    ita: TransLangData(TransWordData('apside')),
    cze: TransLangData(TransWordData('půl')),
    nor: TransLangData(TransWordData('teltduk', prefix: 'et')),
    ned: null,
  ),
  TransData(MdiIcons.fireExtinguisher,
    TransLangData(TransWordData('PPOŻ')),
    mug: TransLangData(TransWordData('ekwipunek przeciwpożaroway, zwykle gaśnica, koc, piasek, wiadło, łopata itp.')),
    eng: TransLangData(TransWordData('fire equipment rack')),
    ger: TransLangData(TransWordData('brandbekämpfungsausrüstung', prefix: 'die')),
    esp: TransLangData(TransWordData('equipamiento antiincendios')),
    ita: TransLangData(TransWordData('protezione antincendio')),
    cze: TransLangData(TransWordData('hasiči')),
    nor: TransLangData(TransWordData('brannslukningsutstyr', prefix: 'et')),
    ned: TransLangData(TransWordData('brandblusapparatuur rek')),
  ),
  TransData(MdiIcons.formatListBulletedSquare,
    TransLangData(TransWordData('Prawo Harcerskie')),
    mug: TransLangData(TransWordData('lista zasad i norm, do których przestrzegania zobowiązani są harcerze')),
    eng: TransLangData(TransWordData('Scout Law')),
    ger: TransLangData(TransWordData('Pfadfindergesetz', prefix: 'das')),
    esp: TransLangData(TransWordData('Ley de Exploración')),
    ita: TransLangData(TransWordData('Legge Scout')),
    cze: TransLangData(TransWordData('Zákon o Skautech')),
    nor: TransLangData(TransWordData('Speiderloven')),
    ned: TransLangData(TransWordData('padvinderswet'), alt: [TransWordData('scoutingwet')]),
  ),
  TransData(MdiIcons.formatListNumbered,
    TransLangData(TransWordData('program dnia', explain: 'plan dnia')),
    mug: TransLangData(TransWordData('harmonogram aktywności zaplanowanych na dany dzień')),
    eng: TransLangData(TransWordData('timetable')),
    ger: TransLangData(TransWordData('tagesprogramm', prefix: 'das')),
    esp: TransLangData(TransWordData('horario')),
    ita: TransLangData(TransWordData('programma del giorno')),
    cze: TransLangData(TransWordData('denní program')),
    nor: TransLangData(TransWordData('dagsplan', prefix: 'en')),
    ned: TransLangData(TransWordData('agenda')),
  ),
  TransData(MdiIcons.nail,
    TransLangData(TransWordData('przybić', suff: 'coś')),
    mug: TransLangData(TransWordData('umocować, coś, przytwierdzić w twardym materiale')),
    eng: TransLangData(TransWordData('nail')),
    ger: TransLangData(TransWordData('festnageln')),
    esp: TransLangData(TransWordData('clavar algo')),
    ita: TransLangData(TransWordData('martellare')),
    cze: TransLangData(TransWordData('přibít')),
    nor: TransLangData(TransWordData('spikre noe fast')),
    ned: TransLangData(TransWordData('spijker')),
  ),
  TransData(MdiIcons.messageReplyText ,
    TransLangData(TransWordData('przyrzeczenie')),
    mug: TransLangData(TransWordData('słowo, zobowiązanie, którego wykonanie nie może zostać odmówione')),
    eng: TransLangData(TransWordData('scout pledge')),
    ger: TransLangData(TransWordData('pfadfinderversprechen', prefix: 'das')),
    esp: TransLangData(TransWordData('promesa de exploración')),
    ita: TransLangData(TransWordData('promessa dello scout')),
    cze: TransLangData(TransWordData('skautský slib')),
    nor: TransLangData(TransWordData('speiderløfte')),
    ned: TransLangData(TransWordData('scout belofte')),
  ),
  TransData(MdiIcons.accountOutline,
    TransLangData(TransWordData('przyboczny')),
    mug: TransLangData(TransWordData('pomocnik, potencjalny przyszły następca drużynowego')),
    eng: TransLangData(TransWordData('assistant scout leader')),
    ger: TransLangData(TransWordData('hilfsleiter', prefix: 'der')),
    esp: TransLangData(TransWordData('subguía')),
    ita: TransLangData(TransWordData('vice capo branco')),
    cze: TransLangData(TransWordData('zástupce vedoucího')),
    nor: null,
    ned: TransLangData(TransWordData('hopman assistent')),
  ),
  TransData(MdiIcons.axe,
    TransLangData(TransWordData('rąbać drewno')),
    mug: TransLangData(TransWordData('proces poddawania dużych lub długich kawałków drewna procesowi rąbania w celu uzyskania kawałków drewna mniejszych rozmiarów')),
    eng: TransLangData(TransWordData('chop wood', prefix: 'to')),
    ger: TransLangData(TransWordData('holz hacken', prefix: 'das')),
    esp: TransLangData(TransWordData('cortar madera'), alt: [TransWordData('Cortar leña')]),
    ita: TransLangData(TransWordData('spaccare')),
    cze: TransLangData(TransWordData('sekání dřeva')),
    nor: TransLangData(TransWordData('hogge ved', prefix: 'å')),
    ned: TransLangData(TransWordData('hout kappen')),
  ),
  TransData(MdiIcons.humanMaleFemale,
    TransLangData(TransWordData('rodzice')),
    mug: TransLangData(TransWordData('ojciec i matka')),
    eng: TransLangData(TransWordData('parents')),
    ger: TransLangData(TransWordData('Eltern', prefix: 'die')),
    esp: TransLangData(TransWordData('paders')),
    ita: TransLangData(TransWordData('genitori')),
    cze: TransLangData(TransWordData('rodiče')),
    nor: TransLangData(TransWordData('foreldre')),
    ned: TransLangData(TransWordData('ouders')),
  ),
  TransData(MdiIcons.knifeMilitary,
    TransLangData(TransWordData('scyzoryk')),
    mug: TransLangData(TransWordData('mały, składany nóż')),
    eng: TransLangData(TransWordData('pocket knife')),
    ger: TransLangData(TransWordData('Taschenmesser', prefix: 'das')),
    esp: TransLangData(TransWordData('cuchillo de bolsillo')),
    ita: TransLangData(TransWordData('coltello tascabile')),
    cze: TransLangData(TransWordData('kapesní nůž')),
    nor: TransLangData(TransWordData('lommekniv', prefix: 'en')),
    ned: TransLangData(TransWordData('zakmes')),
  ),
  TransData(MdiIcons.axe,
    TransLangData(TransWordData('siekiera')),
    mug: TransLangData(TransWordData('ręczne narzędzie składające się ze stalowego ostrza osadzonego na trzonku (zazwyczaj drewnianym), służące głównie do rąbania drewna')),
    eng: TransLangData(TransWordData('axe')),
    ger: TransLangData(TransWordData('Axt', prefix: 'die')),
    esp: TransLangData(TransWordData('hacha')),
    ita: TransLangData(TransWordData('ascia')),
    cze: TransLangData(TransWordData('sekera')),
    nor: TransLangData(TransWordData('øks', prefix: 'en')),
    ned: TransLangData(TransWordData('hakbijl')),
  ),
  TransData(MdiIcons.accountCash,
    TransLangData(TransWordData('składka członkowska')),
    mug: TransLangData(TransWordData('suma pieniężna przeznaczana przez członków organizacji na jej funkcjonowanie')),
    eng: TransLangData(TransWordData('membership fee')),
    ger: TransLangData(TransWordData('Mitgliedsbeitrag', prefix: 'der')),
    esp: TransLangData(TransWordData('cotizacion de socio')),
    ita: TransLangData(TransWordData('quota censimento')),
    cze: TransLangData(TransWordData('členský příspěvěk')),
    nor: TransLangData(TransWordData('medlemskapsavgift', prefix: 'en')),
    ned: TransLangData(TransWordData('contributie')),
  ),
  TransData(MdiIcons.handshake,
    TransLangData(TransWordData('służba')),
    mug: TransLangData(TransWordData('dobrowolna praca na rzecz lokalnej społeczności, wynikająca z jej potrzeb')),
    eng: TransLangData(TransWordData('duty')),
    ger: TransLangData(TransWordData('Dienst', prefix: 'der')),
    esp: TransLangData(TransWordData('servicio')),
    ita: TransLangData(TransWordData('servizio')),
    cze: TransLangData(TransWordData('služba')),
    nor: TransLangData(TransWordData('tjeneste', prefix: 'en')),
    ned: TransLangData(TransWordData('dienst')),
  ),
  TransData(MdiIcons.tent,
    TransLangData(TransWordData('stanica')),
    mug: TransLangData(TransWordData('teren przygotowany pod obozy harcerskie')),
    eng: TransLangData(TransWordData('campsite')),
    ger: TransLangData(TransWordData('Pfadfinderzeltplatz', prefix: 'der')),
    esp: TransLangData(TransWordData('alberque scout')),
    ita: TransLangData(TransWordData('base scout')),
    cze: TransLangData(TransWordData('základna')),
    nor: TransLangData(TransWordData('base', prefix: 'en')),
    ned: TransLangData(TransWordData('(scouting) kampeerterrein')),
  ),
  TransData(MdiIcons.shoePrint,
    TransLangData(TransWordData('stuptut')),
    mug: TransLangData(TransWordData('nogawka zakładana na but, sięgająca poniżej kolana, chroniąca przed dostawaniem się śniegu lub błota do buta')),
    eng: TransLangData(TransWordData('snow gaiter', literalTrans: 'stuptut śnieżny')),
    ger: TransLangData(TransWordData('Stulpen', prefix: 'die')),
    esp: TransLangData(TransWordData('polainas')),
    ita: TransLangData(TransWordData('ghetta')),
    cze: TransLangData(TransWordData('návlek')),
    nor: TransLangData(TransWordData('gamasjer')),
    ned: TransLangData(TransWordData('slobkous')),
  ),
  TransData(MdiIcons.accountMultiple,
    TransLangData(TransWordData('szczep')),
    mug: TransLangData(TransWordData('jednostka harcerska zrzeszająca drużyny działające w tym samym terenie (np. szkole, części dzielnicy), zapewniająca ciągłość wychowawczą między drużynami (możliwość przechodzenia do kolejnych drużyn wraz z osiągnięciem odpowiedniego wieku)')),
    eng: TransLangData(TransWordData('scout-teams group')),
    ger: TransLangData(TransWordData('pfadfinderstamm', prefix: 'der')),
    esp: TransLangData(TransWordData('batallón')),
    ita: TransLangData(TransWordData('gruppo')),
    cze: TransLangData(TransWordData('spolek')),
    nor: null,
    ned: TransLangData(TransWordData('(scout) groep')),
  ),
  TransData(MdiIcons.nail,
    TransLangData(TransWordData('szpilka namiotowa')),
    mug: TransLangData(TransWordData('metalowy, ostry element namiotu służący do przybicia jego podłoża do ziemi')),
    eng: TransLangData(TransWordData('peg')),
    ger: TransLangData(TransWordData('zelthering', prefix: 'der')),
    esp: TransLangData(TransWordData('estaca')),
    ita: TransLangData(TransWordData('pichetto')),
    cze: TransLangData(TransWordData('kolík')),
    nor: TransLangData(TransWordData('teltplugg', prefix: 'en')),
    ned: TransLangData(TransWordData('tentharingen')),
  ),
  TransData(MdiIcons.bookMusic,
    TransLangData(TransWordData('śpiewnik')),
    mug: TransLangData(TransWordData('książka z piosenkami')),
    eng: TransLangData(TransWordData('songbook')),
    ger: TransLangData(TransWordData('Liederbuch', prefix: 'das')),
    esp: TransLangData(TransWordData('cancionero')),
    ita: TransLangData(TransWordData('canzionere')),
    cze: TransLangData(TransWordData('zpěvník')),
    nor: TransLangData(TransWordData('sangbok', example: 'en')),
    ned: TransLangData(TransWordData('liederenbundel')),
  ),
  TransData(MdiIcons.bed,
    TransLangData(TransWordData('śpiwór')),
    mug: TransLangData(TransWordData('ocieplany, rozpinany worek służący do spania')),
    eng: TransLangData(TransWordData('sleeping bag')),
    ger: TransLangData(TransWordData('Schlafsack', prefix: 'der')),
    esp: TransLangData(TransWordData('saco de dormir')),
    ita: TransLangData(TransWordData('sacco a pelo')),
    cze: TransLangData(TransWordData('spacák')),
    nor: TransLangData(TransWordData('sovepose', prefix: 'en')),
    ned: TransLangData(TransWordData('slaapzak')),
  ),
  TransData(MdiIcons.shoePrint,
    TransLangData(TransWordData('trapery')),
    mug: TransLangData(TransWordData('wysokie, sięgające za kostkę wytrzymałe buty, zwykle o podwyższonej wodoodporności')),
    eng: TransLangData(TransWordData('boots')),
    ger: TransLangData(TransWordData('Bergschuhe', prefix: 'die', literalTrans: 'buty górskie')),
    esp: null,
    ita: TransLangData(TransWordData('scarpe da trekking')),
    cze: TransLangData(TransWordData('pohory')),
    nor: TransLangData(TransWordData('fjellsko')),
    ned: TransLangData(TransWordData('wandelschoenen')),
  ),
  TransData(MdiIcons.accountArrowRight,
    TransLangData(TransWordData('wędrownik')),
    mug: TransLangData(TransWordData('harcerz w wieku ponadpodstawowym należący do drużyny wędrowniczej')),
    eng: TransLangData(TransWordData('rover')),
    ger: TransLangData(TransWordData('Rover', prefix: 'der')),
    esp: TransLangData(TransWordData('caminante')),
    ita: TransLangData(TransWordData('rover')),
    cze: TransLangData(TransWordData('rover')),
    nor: TransLangData(TransWordData('rovere')),
    ned: TransLangData(TransWordData('rover')),
  ),
  TransData(MdiIcons.hiking,
    TransLangData(TransWordData('wędrówka')),
    mug: TransLangData(TransWordData('przebywanie długiej drogi, zwykle pieszo, często połączone z odwiedzaniem różnych miejsc')),
    eng: TransLangData(TransWordData('hike')),
    ger: TransLangData(TransWordData('Wanderung', prefix: 'die')),
    esp: TransLangData(TransWordData('caminta'), alt: [TransWordData('recorrido')]),
    ita: TransLangData(TransWordData('cammino')),
    cze: TransLangData(TransWordData('puťák')),
    nor: TransLangData(TransWordData('vandring', prefix: 'en')),
    ned: TransLangData(TransWordData('wandeling'), alt: [TransWordData('hike')]),
  ),
  TransData(MdiIcons.accountMultipleCheck,
    TransLangData(TransWordData('wizytacja')),
    mug: TransLangData(TransWordData('Kontrola działania jednostki przez jednostkę kontrolującą')),
    eng: TransLangData(TransWordData('inspection')),
    ger: TransLangData(TransWordData('Visitation', prefix: 'die')),
    esp: TransLangData(TransWordData('inspección')),
    ita: TransLangData(TransWordData('ispezione')),
    cze: TransLangData(TransWordData('vizitace')),
    nor: TransLangData(TransWordData('besøk', prefix: 'en')),
    ned: TransLangData(TransWordData('inspectie')),
  ),
  TransData(MdiIcons.home,
    TransLangData(TransWordData('zakwaterowanie')),
    mug: TransLangData(TransWordData('pomieszczenie lub przestrzeń zajmowana na pobyt czasowy')),
    eng: TransLangData(TransWordData('accommodation')),
    ger: TransLangData(TransWordData('Unterkunft', prefix: 'die')),
    esp: TransLangData(TransWordData('alojamiento')),
    ita: TransLangData(TransWordData('alloggiamento')),
    cze: TransLangData(TransWordData('zbyt ování')),
    nor: TransLangData(TransWordData('innkvartering', prefix: 'en')),
    ned: TransLangData(TransWordData('onderbrenging'), alt: [TransWordData('accomodatie')]),
  ),
  TransData(MdiIcons.dominoMask,
    TransLangData(TransWordData('zamaskowany')),
    mug: TransLangData(TransWordData('z utrudnioną widocznością')),
    eng: TransLangData(TransWordData('screened')),
    ger: TransLangData(TransWordData('Getarnt'), alt: [TransWordData('Maskiert')]),
    esp: TransLangData(TransWordData('camuflado')),
    ita: TransLangData(TransWordData('mascherato')),
    cze: TransLangData(TransWordData('zamaskowaný')),
    nor: TransLangData(TransWordData('maskert')),
    ned: TransLangData(TransWordData('gemaskerd')),
  ),
  TransData(MdiIcons.minus,
    TransLangData(TransWordData('zapałka')),
    mug: TransLangData(TransWordData('służący do rozpalania ognia, specjalnie w tym celu przygotowany patyczek z drewna')),
    eng: TransLangData(TransWordData('match')),
    ger: TransLangData(TransWordData('Streichholz', prefix: 'das')),
    esp: TransLangData(TransWordData('cerilla')),
    ita: TransLangData(TransWordData('fiammifero')),
    cze: TransLangData(TransWordData('sirka')),
    nor: TransLangData(TransWordData('fyrstikk', prefix: 'en')),
    ned: TransLangData(TransWordData('lucifer')),
  ),
  TransData(MdiIcons.accountMultiple,
    TransLangData(TransWordData('zastęp')),
    mug: TransLangData(TransWordData('część drużyny, najniżej w strukturze umiejscowiona jednostka harcerska licząca ok. 6 osób, na czele z zastępowym')),
    eng: TransLangData(TransWordData('patrol')),
    ger: TransLangData(TransWordData('Sippe', prefix: 'die')),
    esp: TransLangData(TransWordData('agrupación')),
    ita: TransLangData(TransWordData('squadriglia')),
    cze: TransLangData(TransWordData('družina')),
    nor: TransLangData(TransWordData('patrulje', prefix: 'en')),
    ned: TransLangData(TransWordData('patrouille'), alt: [TransWordData('ronde'), TransWordData('bak')]),
  ),
  TransData(MdiIcons.accountGroup,
    TransLangData(TransWordData('zbiórka')),
    mug: TransLangData(TransWordData('spotkanie harcerskie')),
    eng: TransLangData(TransWordData('scout meeting')),
    ger: TransLangData(TransWordData('Versammlung', prefix: 'die')),
    esp: TransLangData(TransWordData('reunión')),
    ita: TransLangData(TransWordData('attività settimanale')),
    cze: TransLangData(TransWordData('skautský sraz')),
    nor: TransLangData(TransWordData('samling', prefix: 'en')),
    ned: TransLangData(TransWordData('bijeenkomsten')),
  ),
  TransData(MdiIcons.snowflake,
    TransLangData(TransWordData('zimowisko')),
    mug: TransLangData(TransWordData('dłuższy, zimowy, zwykle 1-2 tygodniowy wyjazd harcerski, najczęściej w ferie')),
    eng: TransLangData(TransWordData('winter camp')),
    ger: TransLangData(TransWordData('Winterlager', prefix: 'das')),
    esp: TransLangData(TransWordData('campamento de invierno')),
    ita: TransLangData(TransWordData('campo invernale')),
    cze: TransLangData(TransWordData('zimní tábor')),
    nor: TransLangData(TransWordData('vinterleir', prefix: 'en')),
    ned: TransLangData(TransWordData('winterkamp')),
  ),
  TransData(MdiIcons.humanMale,
    TransLangData(TransWordData('zuch (chłopiec)')),
    mug: TransLangData(TransWordData('członek ZHP uczęszczający do 1-3 klasy szkoły podstawowej, należący do gromady zuchowej')),
    eng: TransLangData(TransWordData('cub (scout)')),
    ger: TransLangData(TransWordData('Wölfling', prefix: 'der')),
    esp: TransLangData(TransWordData('novato (scout)')),
    ita: TransLangData(TransWordData('castorino')),
    cze: TransLangData(TransWordData('vlče')),
    nor: TransLangData(TransWordData('bevere')),
    ned: TransLangData(TransWordData('welp')),
  ),
  TransData(MdiIcons.humanFemale,
    TransLangData(TransWordData('zuchenka (dziewczynka)')),
    mug: TransLangData(TransWordData('członkini ZHP uczęszczająca do 1-3 klasy szkoły podstawowej, należąca do gromady zuchowej')),
    eng: TransLangData(TransWordData('brownie (scout)')),
    ger: TransLangData(TransWordData('Wölfin', prefix: 'die')),
    esp: TransLangData(TransWordData('novata (scout)')),
    ita: TransLangData(TransWordData('castorina')),
    cze: TransLangData(TransWordData('světlušky')),
    nor: TransLangData(TransWordData('bevere')),
    ned: TransLangData(TransWordData('kabouter')),
  ),
  TransData(MdiIcons.accountGroup,
    TransLangData(TransWordData('Związek Harcerstwa Polskiego')),
    mug: TransLangData(TransWordData('Prawie najlepsza organizacja harcerska w Polsce i na świecie! c:')),
    eng: TransLangData(TransWordData('The Polish Scouting and Guiding Association')),
    ger: TransLangData(TransWordData('Polnischer Pfadfinder und Pfadfinderinnen Verband')),
    esp: TransLangData(TransWordData('Asociación Polaca de Escultismo y Guidismo')),
    ita: TransLangData(TransWordData('Associazione dello Scoutismo Polacco')),
    cze: TransLangData(TransWordData('Svaz Polských Junáků')),
    nor: TransLangData(TransWordData('Polske Speiderforbundet', prefix: 'det')),
    ned: TransLangData(TransWordData('de Pooles Scouts en Gidsen Vereniging ')),
  ),
];

class TransData{
  final IconData icon;
  final TransLangData pol, mug, eng, ger, esp, ita, cze, nor, ned;
  const TransData(this.icon, this.pol, {@required this.mug, @required this.eng, @required this.ger, @required this.esp, @required this.ita, @required this.cze, @required this.nor, @required this.ned});

  TransLangData get(Lang lang){
    switch(lang){
      case Lang.pol: return pol;
      case Lang.mug: return mug;
      case Lang.eng: return eng;
      case Lang.ger: return ger;
      case Lang.esp: return esp;
      case Lang.ita: return ita;
      case Lang.cze: return cze;
      case Lang.nor: return nor;
      case Lang.ned: return ned;
      default: return null;
    }
  }
}

class TransLangData{

  final TransWordData word;
  final List<TransWordData> alt;

  const TransLangData(this.word, {this.alt = const []});

}

class TransWordData{

  final String word;

  final String prefix;
  final String suff;
  final String example;
  final String explain;
  final String literalTrans;

  const TransWordData(this.word, {this.prefix, this.suff, this.example, this.explain, this.literalTrans});

}