import 'common.dart';
import 'okrzyk.dart';

const List<Okrzyk> OKRZYKI_OGOLNE = [
  Okrzyk('Ale do chó!', [
    SoundElement(0, 8, text: 'A'),
    SoundElement(0, 8, text: 'le', separator:' '),
    SoundElement(0, 8, text: 'do', separator:' '),
    SoundElement(0, 8, text: 'chó', separator:'...!\n'),
    SoundElement(0, 8),

    SoundElement(0, 8, text:'A'),
    SoundElement(0, 8, text:'le', separator:' '),
    SoundElement(0, 8, text:'do', separator:' '),
    SoundElement(0, 8, text:'chó', separator:'...!\n'),
    SoundElement(0, 8,),

    SoundElement(0, 8, text:'A'),
    SoundElement(0, 8, text:'le', separator:' '),
    SoundElement(0, 8, text:'do', separator:' '),
    SoundElement(0, 8, text:'chó'),
    SoundElement(0, 8, text:'ru', separator:' '),
    SoundElement(0, 8, text:'ich', separator:' '),
    SoundElement(0, 8, text:'za'),
    SoundElement(0, 8, text:'pi'),
    SoundElement(0, 8, text:'sać', separator:'!'),
  ]),
  Okrzyk('Ale do du!', [
    SoundElement(0, 8, text:'A'),
    SoundElement(0, 8, text:'le', separator:' '),
    SoundElement(0, 8, text:'do', separator:' '),
    SoundElement(0, 4, text:'du', separator:'...!\n'),
    SoundElement(0, 8),

    SoundElement(0, 8, text:'A'),
    SoundElement(0, 8, text:'le', separator:' '),
    SoundElement(0, 8, text:'do', separator:' '),
    SoundElement(0, 8, text:'du', separator:'...!\n'),
    SoundElement(0, 8),

    SoundElement(0, 8, text:'A'),
    SoundElement(0, 8, text:'le', separator:' '),
    SoundElement(0, 8, text:'do', separator:' '),
    SoundElement(0, 8, text:'du'),
    SoundElement(0, 8, text:'żej', separator:' '),
    SoundElement(0, 8, text:'do'),
    SoundElement(0, 8, text:'szli', separator:' '),
    SoundElement(0, 8, text:'wpra'),
    SoundElement(0, 8, text:'wy', separator:'!'),
  ]),
  Okrzyk('Brawo, brawissimo', [
    SoundElement(18, 8, text:'Bra'),
    SoundElement(23, 8, text:'aa'),
    SoundElement(22, 8, text:'wo', separator:', '),

    SoundElement(20, 8, text:'bra'),
    SoundElement(25, 8, text:'aa'),
    SoundElement(23, 8, text:'wo', separator:', '),

    SoundElement(22, 8, text:'bra'),
    SoundElement(20, 8, text:'wis'),
    SoundElement(22, 8, text:'si'),
    SoundElement(23, 4, text:'mo', separator:'!\n'),
    SoundElement(0, 8),

    SoundElement(18, 8, text:'Bra'),
    SoundElement(23, 8, text:'aa'),
    SoundElement(22, 8, text:'wo', separator:', '),

    SoundElement(20, 8, text:'bra'),
    SoundElement(25, 8, text:'aa'),
    SoundElement(23, 8, text:'wo', separator:', '),

    SoundElement(22, 8, text:'bra'),
    SoundElement(20, 8, text:'wis'),
    SoundElement(22, 8, text:'si'),
    SoundElement(23, 4, text:'mo', separator:'!\n'),
    SoundElement(0, 8),


    SoundElement(27, 8, text:'Bra'),
    SoundElement(27, 8, text:'wo', separator:', '),
    SoundElement(27, 8, text:'bra'),
    SoundElement(28, 8, text:'wis'),
    SoundElement(28, 8, text:'si'),
    SoundElement(28, 8, text:'mo', separator:', '),

    SoundElement(25, 8, text:'bra'),
    SoundElement(25, 8, text:'wo', separator:', '),
    SoundElement(25, 8, text:'bra'),
    SoundElement(27, 8, text:'wis'),
    SoundElement(27, 8, text:'si'),
    SoundElement(27, 8, text:'mo', separator:',\n'),


    SoundElement(18, 8, text:'bra'),
    SoundElement(23, 8, text:'aa'),
    SoundElement(22, 8, text:'wo', separator:', '),

    SoundElement(20, 8, text:'bra'),
    SoundElement(25, 8, text:'aa'),
    SoundElement(23, 8, text:'wo', separator:', '),

    SoundElement(22, 8, text:'bra'),
    SoundElement(20, 8, text:'wis'),
    SoundElement(22, 8, text:'si'),
    SoundElement(23, 4, text:'mo', separator:'!\n'),

    SoundElement(18, 8, text:'O'),
    SoundElement(23, 4, text:'oo', separator:'!'),
  ]),
  Okrzyk('B-R-A-W-O', [
    SoundElement(0, 4, text:'B', separator:'-'),
    SoundElement(0, 4, text:'R', separator:'-'),
    SoundElement(0, 4, text:'A', separator:'-'),
    SoundElement(0, 4, text:'W', separator:'-'),
    SoundElement(0, 4, text:'O', separator:' '),

    SoundElement(0, 8, text:'bra'),
    SoundElement(0, 8, text:'wo', separator:' '),
    SoundElement(0, 8, text:'bra'),
    SoundElement(0, 8, text:'wo', separator:' '),
    SoundElement(0, 8, text:'bra'),
    SoundElement(0, 8, text:'wo', separator:'\n'),

    SoundElement(0, 4, text:'B', separator:'-'),
    SoundElement(0, 4, text:'R', separator:'-'),
    SoundElement(0, 4, text:'A', separator:'-'),
    SoundElement(0, 4, text:'W', separator:'-'),
    SoundElement(0, 4, text:'O', separator:' '),

    SoundElement(0, 8, text:'bra'),
    SoundElement(0, 8, text:'wo', separator:' '),
    SoundElement(0, 8, text:'bra'),
    SoundElement(0, 8, text:'wo', separator:' '),
    SoundElement(0, 8, text:'bra'),
    SoundElement(0, 8, text:'wo', separator:' '),
  ]),
  Okrzyk('Harcerze nie klaszczą', [
    SoundElement(25, 8, text:'Har'),
    SoundElement(25, 8, text:'ce'),
    SoundElement(25, 8, text:'rze', separator:' '),
    SoundElement(22, 8, text:'nie', separator:' '),
    SoundElement(27, 4, text:'kla'),
    SoundElement(25, 4, text:'szczą', separator:'!\n'),

    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8),
    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8, text:'*klask*', separator:'\n'),
    SoundElement(0, 8),

    SoundElement(25, 8, text:'Tyl'),
    SoundElement(25, 8, text:'ko', separator:' '),
    SoundElement(25, 8, text:'bi'),
    SoundElement(22, 8, text:'ją', separator:' '),
    SoundElement(27, 4, text:'bra'),
    SoundElement(25, 4, text:'wo', separator:'!\n'),

    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8),
    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8, text:'*klask*', separator:' '),
    SoundElement(0, 8, text:'*klask*'),
  ]),
];

const List<Okrzyk> OKRZYKI_POSILKOWE = [
  Okrzyk('Hej dziękujemy! (śniadanie)', [
    SoundElement(25, 8, text:'Hej', separator:', '),
    SoundElement(25, 4, text:'dzię'),
    SoundElement(24, 8, text:'ku'),
    SoundElement(25, 4, text:'je'),
    SoundElement(22, 4, text:'my', separator:', '),

    SoundElement(25, 8, text:'hej', separator:', '),
    SoundElement(25, 4, text:'dzię'),
    SoundElement(24, 8, text:'ku'),
    SoundElement(25, 4, text:'je'),
    SoundElement(22, 4, text:'my', separator:', '),

    SoundElement(27, 8, text:'hej', separator:', '),
    SoundElement(27, 4, text:'za', separator:' '),
    SoundElement(25, 8, text:'śnia'),
    SoundElement(23, 4, text:'dan'),
    SoundElement(22, 4, text:'ko', separator:' '),
    SoundElement(20, 8, text:'dzię'),
    SoundElement(18, 8, text:'ku'),
    SoundElement(17, 4, text:'je'),
    SoundElement(18, 2, text:'my', separator:'! '),

    SoundElement(13, 8, text:'Hej', separator:', '),
    SoundElement(13, 4, text:'dzię'),
    SoundElement(15, 8, text:'ku'),
    SoundElement(16, 4, text:'je'),
    SoundElement(17, 4, text:'my', separator:', '),

    SoundElement(18, 8, text:'hej', separator:', '),
    SoundElement(18, 4, text:'dzię'),
    SoundElement(22, 8, text:'ku'),
    SoundElement(27, 4, text:'je'),
    SoundElement(25, 4, text:'my', separator:', '),

    SoundElement(27, 8, text:'hej', separator:', '),
    SoundElement(27, 4, text:'na', separator:' '),
    SoundElement(25, 8, text:'ob'),
    SoundElement(23, 4, text:'ia'),
    SoundElement(22, 4, text:'dek', separator:' '),

    SoundElement(20, 8, text:'też', separator:' '),
    SoundElement(18, 8, text:'przyj'),
    SoundElement(17, 4, text:'dzie'),
    SoundElement(18, 2, text:'my', separator:'!'),
  ]),
  Okrzyk('Hej dziękujemy! (obiad)', [
    SoundElement(25, 8, text:'Hej', separator:', '),
    SoundElement(25, 4, text:'dzię'),
    SoundElement(24, 8, text:'ku'),
    SoundElement(25, 4, text:'je'),
    SoundElement(22, 4, text:'my', separator:', '),

    SoundElement(25, 8, text:'hej', separator:', '),
    SoundElement(25, 4, text:'dzię'),
    SoundElement(24, 8, text:'ku'),
    SoundElement(25, 4, text:'je'),
    SoundElement(22, 4, text:'my', separator:', '),

    SoundElement(27, 8, text:'hej', separator:', '),
    SoundElement(27, 4, text:'za', separator:' '),
    SoundElement(25, 8, text:'o'),
    SoundElement(23, 4, text:'bia'),
    SoundElement(22, 4, text:'dek', separator:' '),
    SoundElement(20, 8, text:'dzię'),
    SoundElement(18, 8, text:'ku'),
    SoundElement(17, 4, text:'je'),
    SoundElement(18, 2, text:'my', separator:'! '),

    SoundElement(13, 8, text:'Hej', separator:', '),
    SoundElement(13, 4, text:'dzię'),
    SoundElement(15, 8, text:'ku'),
    SoundElement(16, 4, text:'je'),
    SoundElement(17, 4, text:'my', separator:', '),

    SoundElement(18, 8, text:'hej', separator:', '),
    SoundElement(18, 4, text:'dzię'),
    SoundElement(22, 8, text:'ku'),
    SoundElement(27, 4, text:'je'),
    SoundElement(25, 4, text:'my', separator:', '),

    SoundElement(27, 8, text:'hej', separator:', '),
    SoundElement(27, 4, text:'na', separator:' '),
    SoundElement(25, 8, text:'ko'),
    SoundElement(23, 4, text:'la'),
    SoundElement(22, 4, text:'cję', separator:' '),

    SoundElement(20, 8, text:'też', separator:' '),
    SoundElement(18, 8, text:'przyj'),
    SoundElement(17, 4, text:'dzie'),
    SoundElement(18, 2, text:'my', separator:'!'),
  ]),
  Okrzyk('Hej dziękujemy! (kolacja)', [
    SoundElement(25, 8, text:'Hej', separator:', '),
    SoundElement(25, 4, text:'dzię'),
    SoundElement(24, 8, text:'ku'),
    SoundElement(25, 4, text:'je'),
    SoundElement(22, 4, text:'my', separator:', '),

    SoundElement(25, 8, text:'hej', separator:', '),
    SoundElement(25, 4, text:'dzię'),
    SoundElement(24, 8, text:'ku'),
    SoundElement(25, 4, text:'je'),
    SoundElement(22, 4, text:'my', separator:', '),

    SoundElement(27, 8, text:'hej', separator:', '),
    SoundElement(27, 4, text:'za', separator:' '),
    SoundElement(25, 8, text:'ko'),
    SoundElement(23, 4, text:'la'),
    SoundElement(22, 4, text:'cję', separator:' '),
    SoundElement(20, 8, text:'dzię'),
    SoundElement(18, 8, text:'ku'),
    SoundElement(17, 4, text:'je'),
    SoundElement(18, 2, text:'my', separator:'! '),

    SoundElement(13, 8, text:'Hej', separator:', '),
    SoundElement(13, 4, text:'dzię'),
    SoundElement(15, 8, text:'ku'),
    SoundElement(16, 4, text:'je'),
    SoundElement(17, 4, text:'my', separator:', '),

    SoundElement(18, 8, text:'hej', separator:', '),
    SoundElement(18, 4, text:'dzię'),
    SoundElement(22, 8, text:'ku'),
    SoundElement(27, 4, text:'je'),
    SoundElement(25, 4, text:'my', separator:', '),

    SoundElement(27, 8, text:'hej', separator:', '),
    SoundElement(27, 4, text:'na', separator:' '),
    SoundElement(25, 8, text:'śnia'),
    SoundElement(23, 4, text:'dan'),
    SoundElement(22, 4, text:'ko', separator:' '),

    SoundElement(20, 8, text:'też', separator:' '),
    SoundElement(18, 8, text:'przyj'),
    SoundElement(17, 4, text:'dzie'),
    SoundElement(18, 2, text:'my', separator:'!'),
  ]),
  Okrzyk('Pobłogosław Panie!', [
    SoundElement(18, 8, text:'Po'),
    SoundElement(18, 8, text:'bło'),
    SoundElement(18, 8, text:'go'),
    SoundElement(18, 8, text:'sław', separator:' '),
    SoundElement(23, 6, text:'Pa'),
    SoundElement(27, 3, text:'nie', separator:', '),

    SoundElement(18, 8, text:'z wy'),
    SoundElement(18, 8, text:'so'),
    SoundElement(18, 8, text:'kie'),
    SoundElement(18, 8, text:'go', separator:' '),
    SoundElement(23, 6, text:'nie'),
    SoundElement(27, 3, text:'ba', separator:', '),

    SoundElement(27, 4, text:'hej', separator:', '),
    SoundElement(23, 8, text:'co'),
    SoundElement(23, 12, text:'by', separator:' '),
    SoundElement(28, 8, text:'na', separator:' '),
    SoundElement(27, 8, text:'tym', separator:' '),
    SoundElement(25, 8, text:'sto'),
    SoundElement(23, 8, text:'le', separator:' '),

    SoundElement(22, 8, text:'nie', separator:' '),
    SoundElement(23, 8, text:'za'),
    SoundElement(25, 8, text:'bra'),
    SoundElement(22, 8, text:'kło', separator:' '),
    SoundElement(23, 6, text:'chle'),
    SoundElement(27, 4, text:'ba', separator:' '),

    SoundElement(27, 4, text:'hej', separator:', '),
    SoundElement(23, 8, text:'co'),
    SoundElement(23, 12, text:'by', separator:' '),
    SoundElement(28, 8, text:'na', separator:' '),
    SoundElement(27, 8, text:'tym', separator:' '),
    SoundElement(25, 8, text:'sto'),
    SoundElement(23, 8, text:'le', separator:' '),

    SoundElement(22, 8, text:'nie', separator:' '),
    SoundElement(23, 8, text:'za'),
    SoundElement(25, 8, text:'bra'),
    SoundElement(22, 8, text:'kło', separator:' '),
    SoundElement(23, 6, text:'chle'),
    SoundElement(23, 4, text:'ba', separator:'!\n\n'),


    SoundElement(18, 8, text:'Nie', separator:' '),
    SoundElement(18, 8, text:'za'),
    SoundElement(18, 8, text:'bra'),
    SoundElement(18, 8, text:'kło', separator:' '),
    SoundElement(23, 6, text:'chle'),
    SoundElement(27, 3, text:'ba', separator:', '),

    SoundElement(18, 8, text:'nie', separator:' '),
    SoundElement(18, 8, text:'za'),
    SoundElement(18, 8, text:'bra'),
    SoundElement(18, 8, text:'kło', separator:' '),
    SoundElement(23, 6, text:'gru'),
    SoundElement(27, 3, text:'li', separator:', '),

    SoundElement(27, 4, text:'hej', separator:', '),
    SoundElement(23, 8, text:'a'),
    SoundElement(23, 12, text:'ni', separator:' '),
    SoundElement(28, 8, text:'tej', separator:' '),
    SoundElement(27, 8, text:'mi'),
    SoundElement(25, 8, text:'ło'),
    SoundElement(23, 8, text:'ści', separator:' '),

    SoundElement(22, 8, text:'od', separator:' '),
    SoundElement(23, 8, text:'na'),
    SoundElement(25, 8, text:'szej', separator:' '),
    SoundElement(22, 8, text:'Ma'),
    SoundElement(23, 6, text:'tu'),
    SoundElement(27, 4, text:'li', separator:', '),

    SoundElement(27, 4, text:'hej', separator:', '),
    SoundElement(23, 8, text:'a'),
    SoundElement(23, 12, text:'ni', separator:' '),
    SoundElement(28, 8, text:'tej', separator:' '),
    SoundElement(27, 8, text:'mi'),
    SoundElement(25, 8, text:'ło'),
    SoundElement(23, 8, text:'ści', separator:' '),

    SoundElement(22, 8, text:'od', separator:' '),
    SoundElement(23, 8, text:'na'),
    SoundElement(25, 8, text:'szej', separator:' '),
    SoundElement(22, 8, text:'Ma'),
    SoundElement(23, 6, text:'tu'),
    SoundElement(23, 4, text:'li', separator:'!'),
  ]),
  Okrzyk('Ściereczką myj gary gary', [
    SoundElement(25, 2, text:'Ście'),
    SoundElement(30, 4, text:'re'),
    SoundElement(25, 4, text:'czką', separator:' '),
    SoundElement(27, 4, text:'myj', separator:' '),
    SoundElement(27, 8, text:'ga'),
    SoundElement(25, 8, text:'ry', separator:' '),
    SoundElement(27, 8, text:'ga'),
    SoundElement(28, 8, text:'ry', separator:' '),
    SoundElement(0, 4),

    SoundElement(25, 4, text:'nie', separator:' '),
    SoundElement(25, 4, text:'o'),
    SoundElement(30, 4, text:'szczę'),
    SoundElement(25, 4, text:'dzaj', separator:' '),
    SoundElement(27, 4, text:'rąk', separator:'!\n'),
    SoundElement(0, 2),

    SoundElement(25, 2, text:'Z bru'),
    SoundElement(30, 4, text:'da'),
    SoundElement(25, 4, text:'mi', separator:' '),
    SoundElement(27, 4, text:'weź', separator:' '),
    SoundElement(27, 8, text:'się', separator:' '),
    SoundElement(25, 8, text:'za', separator:' '),
    SoundElement(27, 8, text:'ba'),
    SoundElement(28, 8, text:'ry', separator:' '),
    SoundElement(0, 4),

    SoundElement(25, 4, text:'z kuch'),
    SoundElement(25, 4, text:'ni', separator:' '),
    SoundElement(25, 4, text:'po'),
    SoundElement(27, 4, text:'wiedz', separator:' '),
    SoundElement(23, 4, text:'won', separator:'!'),
  ]),
];