import 'package:harcapp/_new/cat_page_guidebook_development/development/tropy/model/trop.dart';

import 'trop_idea.dart';

List<TropIdea> harcHSTropIdeas = const [

  TropIdea(
    name: 'Czas Bohaterów',
    category: TropCategory.harcInicjatywa,
    intro: 'To ostatni dzwonek i ostatnie możliwości spotkania z osobami, które są świadkami historii. Niewielu już pozostało żyjących uczestników Powstania Warszawskiego, bohaterów Szarych Szeregów, Armii Krajowej, żołnierzy Armii Andersa, uczestników tajnych organizacji harcerskich i wojskowych, którzy walczyli z okupantem. Warto poznać ich historie i szerzyć pamięć o nich.',
    plan: 'Poszukajcie w swoim regionie organizacji, które zajmują się kombatantami i działaniami na ich rzecz. Po konsultacji z drużynowym nawiążcie kontakt i współpracę, zbadajcie i określcie potrzeby tych organizacji i samych kombatantów. Spróbujcie na nie odpowiedzieć. Podzielcie wszystkie zadania między członków zastępu.',
    todo: 'Wykonując służbę na rzecz kombatantów, wspierając ich – rozmawiajcie z nimi. Może uda Wam się udokumentować coś, co będziecie w stanie przekazać innym jako świadectwo historii? Może po zrobieniu zakupów dla dawnej sanitariuszki wypijecie wspólnie herbatę, a ona opowie Wam o czasach swojej młodości? Może uda Wam się zrobić dokument, nakręcić relację, stworzyć audycję, gazetkę lub wystawę? Najważniejsze są: Wasz pomysł i realizacja.',
    summary: 'Po kilku zbiórkach, spotkaniach, po wyznaczonym przez Was okresie służby podsumujcie swoje działania. Jeśli udało Wam się zebrać relacje i stworzyć dokument, podzielcie się swoim dziełem z innymi w wybranej przez siebie formie. Niech jednak podsumowanie nie będzie finałem – może uda Wam się zarazić tą służbą innych harcerzy i inne środowiska?'
  ),

  TropIdea(
      name: 'Moje wsparcie się liczy',
      category: TropCategory.harcInicjatywa,
      intro: 'Każdy z nas dysponuje określonymi zasobami: czasem, zdolnościami, przedmiotami, które są naszą własnością. Sprawdźcie, jakie to uczucie, gdy te zasoby „pracują” dla dobra innych. Rozejrzyjcie się po okolicznych instytucjach i wykorzystajcie Wasze zdolności tam, gdzie są potrzebne.',
      plan: 'Zapoznajcie się z miejscami w Waszej okolicy, które wspierają drugiego człowieka lub naturę (schroniska dla zwierząt, jadłodajnie, domy dziecka, domy pomocy społecznej itp.). Odwiedźcie wybrane miejsce i porozmawiajcie z dyrekcją i pracownikami o tym, czym się zajmują, jak wygląda praca w takim miejscu i co daje. Dowiedzcie się, czy mają jakieś potrzeby, z którymi moglibyście im pomóc. Przemyślcie także dobrze, jakimi zasobami sami dysponujecie (jakie posiadacie umiejętności i możliwości działania).',
      todo: 'Spróbujcie pomóc. Zorganizujcie zbiórkę potrzebnych rzeczy dla tych miejsc po uprzednim sprawdzeniu, czego mogą potrzebować (warto poprosić drużynowego o pomoc przy tej części tropu). Poszukajcie u siebie, u swoich znajomych i rodziny najpotrzebniejszych rzeczy dla tego miejsca, spróbujcie przedstawić ten problem w szkole i tam też postarajcie się o wsparcie Waszego projektu, zorganizujcie akcję zarobkową na ten cel. Jeśli potrzeba jest inna (np. spacer z osobami starszymi), to na pewno jedynym problemem będzie znalezienie na to czasu. Być może trzeba będzie zorganizować dodatkowe zajęcia dla dzieci z domu dziecka? A kto zrobi lepsze zajęcia niż harcerze?',
      summary: 'W poprzednim kroku na pewno udowodniliście, że harcerze mają wielkie serca. Jeśli możecie podsumować działanie z pracownikami miejsca, któremu pomagaliście, zróbcie to. Podsumujcie trop także w swoim gronie, na zbiórce zastępu. Porozmawiajcie o tym, co czuliście, gdy oddawaliście Wasze rzeczy, i o tym, jak można pomagać takim miejscom częściej niż raz do roku.'
  ),

  TropIdea(
      name: 'Zmień swoje otoczenie',
      category: TropCategory.harcInicjatywa,
      intro: 'Nasze otoczenie to nasza wspólna odpowiedzialność. Czy wokół Was jest coś, co wymaga Waszej uwagi i działania? Jeśli nie wiecie, to na pewno odpowiedzi na to pytanie dostarczy Wam zwiad.',
      plan: 'Czy wiecie, co chcielibyście zmienić na lepsze w swojej okolicy? Czy macie na to jakieś pomysły? Jeżeli nie, nic nie szkodzi! Stwórzcie ankietę z pytaniami na ten temat i zorganizujcie zwiad w najbliższym otoczeniu. Spytajcie napotkane osoby, o co chciałyby wzbogacić swoje miejsce zamieszkania. Zbierzcie i opracujcie wnioski z tego ankietowania i przedstawcie je na forum Waszej drużyny. Na ich podstawie zastanówcie się w zastępie, czy możecie zorganizować coś, co zadowoli nie tylko Was, lecz także mieszkańców. Opracujcie plan tego działania.',
      todo: 'Sprawdźcie, czy Wasz lokalny urząd lub lokalne NGO nie planują w najbliższym roku akcji podobnej do Waszej. Może jesteście w stanie nawiązać współpracę z lokalnymi instytucjami publicznymi, stowarzyszeniami czy podmiotami gospodarczymi i działać w partnerstwie?'
          '\n\nPrzystąpcie do realizacji planu. Może warto zaangażować w Wasze działania również napotkanych w trakcie ankietowania mieszkańców okolicy, a także Waszych znajomych i rodzinę?'
          '\n\nMoże udokumentujecie akcję i przekażecie film/zdjęcia itp. lokalnym władzom, aby pomogły Wam w promocji? Może Wasza akcja przerodzi się w cykliczne i regularne działania? Najważniejsze są: Wasz pomysł i realizacja.',
      summary: 'Po kilku zbiórkach i spotkaniach, po wyznaczonym przez Was okresie służby podsumujcie swoje działania. Jeśli udało Wam się stworzyć relację (np. filmik lub serię zdjęć), podzielcie się swoim dziełem z pozostałymi członkami drużyny. A może istnieje szansa na włączenie ich w Wasze dalsze działania? Niech jednak podsumowanie nie będzie finałem – może uda Wam się zarazić tą służbą nie tylko innych harcerzy, lecz także okolicznych mieszkańców?'
  ),

  // # TODO: Eko-propaganda
  TropIdea(
      name: 'Harcerski punkt wymiany',
      category: TropCategory.harcZaradnosc,
      intro: 'A gdyby tak zamiast coś kupić po prostu to dostać? Albo wymienić na coś, czego obecnie nie potrzebujecie? Pomyślcie, ile pieniędzy moglibyście zaoszczędzić i jak wiele zasobów planety mogłoby zostać dla przyszłych pokoleń!',
      plan: 'Przeanalizujcie, jakie produkty posiadacie, ale ich nie używacie, w jakim są stanie, czy nadają się do dalszego użytku, a jakie chcielibyście mieć, ale nie macie? Stwórzcie indywidualne listy, a następnie porównajcie je. Czy jest na nich coś, czym moglibyście się wymieniać? A może gdyby zainteresować tym więcej osób, udałoby się zarówno znaleźć nowych użytkowników dla nieużywanych przez siebie produktów, jak i pozyskać produkty, których Wam brakuje?',
      todo: 'Załóżcie i prowadźcie przez określony przez siebie czas „harcerski punkt wymiany” (samodzielnie lub korzystając z pomocy sojuszników, np. szkoły, biblioteki, domu kultury itp.). Ustalcie zasady korzystania z punktu, rozpropagujcie jego działanie.',
      summary: 'Po upływie założonego czasu oceńcie, w jakim stopniu punkt umożliwił Wam pozyskanie pożądanych produktów i pozbycie się niechcianych, jakie było zainteresowanie punktem poza Waszym zastępem, jak oceniacie inicjatywę, co się udało, co trzeba poprawić i czy warto kontynuować działanie punktu.'
  ),

  TropIdea(
      name: 'Mały papier o dużej wartości – banknot',
      category: TropCategory.harcZaradnosc,
      intro: 'Jak dużo wiecie o banknotach? Czy bylibyście w stanie odróżnić podróbkę od prawdziwych pieniędzy? Czy podobną wiedzę mają wasi bliscy? Może warto pomóc im chronić się przed oszustwami?',
      plan: 'Niech każdy z was spróbuje opisać dowolny polski banknot. Jak dokładnie udało wam się to zrobić? Czy opisaliście obie strony banknotu (awers i rewers)? Zastanówcie się również, w jaki sposób zabezpieczone są poszczególne nominały polskich banknotów – ile sposobów zabezpieczeń udało wam się wymienić? Aby zweryfikować, czy o czymś nie zapomnieliście, warto odwiedzić stronę Narodowego Banku Polskiego i porównać wasze wiadomości z informacjami na niej zawartymi. Zwróćcie uwagę na różnice w wyglądzie wzorów banknotów obowiązujących w starej i nowej emisji.',
      todo: 'Podzielcie się zadaniami i przeprowadźcie wśród mieszkańców kampanię informacyjną dotyczącą zabezpieczeń i wyglądu polskich banknotów. Spróbujcie porozmawiać z uczestnikami kampanii na temat tego, czy preferują gotówkową czy bezgotówkową formę płatności i dlaczego. Przekażcie im informacje o tym, jak należy postąpić w przypadku otrzymania fałszywego banknotu. Na polu hufca lub szczepu zorganizujcie quiz zastępów o polskich banknotach. Pytania zadawane podczas kampanii możecie przeprowadzić w formie ankiety, której wyniki zaprezentujecie podczas podsumowania tropu.',
      summary: 'Zastanówcie się, czy przeprowadzona kampania była pożyteczna? Jak oceniacie stan wiedzy uczestników kampanii o polskich banknotach? Czy dzięki poszerzeniu wiedzy na temat banknotów zarówno wy, jak i uczestnicy będziecie korzystać z nich z większą świadomością i poczuciem bezpieczeństwa? Na forum drużyny opowiedzcie o waszym projekcie i przedstawcie wnioski, których dostarczył.'
  ),

  TropIdea(
      name: 'Minizakład produkcyjny – akcja zarobkowa',
      category: TropCategory.harcZaradnosc,
      intro: 'Wiedza na temat zasad działania przedsiębiorstwa, w tym zakładu produkcyjnego, to wartościowa umiejętność. Jak lepiej poznać te zasady, jeśli nie przez praktykę i wcielenie się w rolę przedsiębiorców?',
      plan: 'W ramach akcji zarobkowej stwórzcie miniprzedsiębiorstwo, działające przez czas trwania tropu (nie krócej niż miesiąc). Przeprowadźcie analizę rynku – jakie produkty możecie sprzedawać w ramach akcji zarobkowej. Napiszcie biznesplan swojej akcji zarobkowej (co będziecie produkować, jakich zasobów potrzebujecie, jakie koszty poniesiecie, jak będzie wyglądał cykl produkcji). Informacji na temat tworzenia dobrego biznesplanu poszukajcie w Internecie.'
          '\n\nPamiętajcie, by przy organizacji akcji zarobkowej stosować aktualne przepisy państwowe dotyczące przeprowadzania zbiórek publicznych, a w przypadku sprzedaży produktów – odpowiednich przepisów prawa podatkowego. O szczegóły spytajcie drużynowego albo skarbnika hufca.',
      todo: 'Rozdzielcie między siebie zadania swojego przedsiębiorstwa. W końcu nie każda osoba realizująca trop musi być bezpośrednio zaangażowana w produkcję! Przedsiębiorstwo to przecież wiele działów: logistyki, marketingu, księgowości, produkcji, sprzedaży, dystrybucji.  W ramach uproszczenia jedna osoba może zająć się kilkoma rzeczami. Po podziale zadań i dopełnieniu formalności związanych z organizacją akcji zarobkowej rozpocznijcie działanie waszego przedsiębiorstwa zgodnie z przyjętymi w biznesplanie zasadami.',
      summary: 'Po realizacji akcji w formie minizakładu produkcyjnego spiszcie rachunek zysków i strat, zaznaczcie, jakie koszty ponieśliście oraz jakie mieliście przychody. Podsumujcie, ile zarobiliście podczas akcji – jaki był wasz zysk. W ramach podsumowania omówicie również niefinansowe aspekty akcji zarobkowej, takie jak: atmosfera podczas akcji, sposób komunikacji, motywowanie, współpraca wewnątrz zespołu, skutki wizerunkowe itp. Na zakończenie spiszcie wnioski z przebiegu akcji – o czym należy pamiętać na przyszłość, co warto powtórzyć, a czego unikać.'
  ),

  TropIdea(
      name: 'Puszka szczęścia',
      category: TropCategory.harcZaradnosc,
      intro: 'Złom stalowy, aluminium, żeliwo, mosiądz, miedź, brązy, a także plastikowe zakrętki i stłuczka szklana to przykłady surowców, jakie można sprzedać w punkcie skupu. Czy myśleliście, ile nieużywanych skarbów tego typu można zamienić na gotówkę?',
      plan: 'Po pierwsze – trzeba poszukać okazji do zamiany zwykłej blachy w piękne złotówki. W Waszym otoczeniu na pewno jest wiele niepotrzebnych przedmiotów i zbędnych sprzętów. Przeanalizujcie, ile surowców się marnuje, a mogłoby być odzyskane z pożytkiem dla Was i dla świata. Odwiedźcie skup złomu i sprawdźcie, co jest najbardziej opłacalne do zbierania i oddawania. Przeanalizujcie swoje możliwości oraz możliwości osób Was wspierających.',
      todo: 'Zorganizujcie akcję zbiórki złomu lub innych surowców. Do akcji włączcie drużynę, rodziców, szkołę, osiedle, dzielnicę. Nagłośnijcie akcję i zadbajcie o kontakt, aby każdy mógł Was szybko znaleźć i przekazać surowce. Przy wsparciu kogoś dorosłego zorganizujcie miejsce lub pojemnik (kontener) do magazynowania zbieranych surowców oraz transport. Przeanalizujcie koszty, które musicie ponieść, i planowany zarobek. Zastanówcie się, na co chcielibyście przeznaczyć zarobione pieniądze.',
      summary: 'Najlepszym podsumowaniem Waszego działania będzie wspólna sprzedaż pozyskanych surowców. Zarobione w ten sposób pieniądze możecie wykorzystać na najbliższy wyjazd, zakup niezbędnego sprzętu turystycznego lub umundurowania. Możecie je także przeznaczyć na cele dobroczynne.'
  ),

  TropIdea(
      name: 'Ścieżki życia',
      category: TropCategory.harcZaradnosc,
      intro: 'Czy zdarzyło Wam się ostatnimi czasy myśleć o swojej zawodowej przyszłości? Czy te pomysły pokrywają się z Waszymi marzeniami z dziecięcych lat? Sprawdźcie, co może mieć wpływ na Wasz przyszły zawód.',
      plan: 'Dowiedzcie się, gdzie jest najbliższy doradca zawodowy w Waszej okolicy. Przeprowadźcie z nim wywiad, by zapoznać się z jego pracą, zwróćcie uwagę na to, w jaki sposób działa. Spróbujcie popatrzeć na Wasze możliwości z innej perspektywy, przeanalizować swoje zainteresowania, hobby, fascynacje przedmiotami szkolnymi, sztuką czy sportem. Poszukajcie własnych ścieżek rozwoju. Sprawdźcie, jakie role pełnicie w grupie i co dobrego możecie dać innym. Warto także przeanalizować możliwości, jakie dają Wam szkoły średnie w Waszej okolicy – może uczą ciekawego i przydatnego zawodu albo mają klasę o wyjątkowym profilu?',
      todo: 'Zaproście doradcę zawodowego do Waszej klasy, szkoły. Przekonajcie kolegów i koleżanki, by spróbowali rozwiązać testy predyspozycji zawodowych i sprawdzili swoje możliwości. Pamiętajcie, by taki test wykonać samemu. Wraz ze szkolnym pedagogiem zorganizujcie w Waszej szkole dzień rozwoju osobistego i przedstawcie ciekawe możliwości, jakie daje Wasza miejscowość.',
      summary: 'Niech każdy z Was wykona własną pracę dotyczącą dalszego rozwoju. Na podstawie informacji pozyskanych od doradcy zawodowego oraz ze szkół przeanalizujcie, w którą stronę chcielibyście w przyszłości podążyć. Zorganizujcie zbiórkę zastępu, na której każdy z Was przedstawi swój wybór z odpowiednim podsumowaniem i uzasadnieniem. Poszukajcie plusów i minusów swoich wyborów.'
  ),

  TropIdea(
      name: 'Waluty świata',
      category: TropCategory.harcZaradnosc,
      intro: 'Pieniądz stanowi jeden z najstarszych wynalazków ludzkości, jednak przez wieki historii nigdy na świecie nie istniała tylko jedna waluta. Trop „Waluty świata” pozwoli lepiej zrozumieć znaczenie pieniądza w dzisiejszej gospodarce światowej i poznać źródło zależności między walutami.',
      plan: 'Poszukajcie w na stronie internetowej Narodowego Banku Polskiego informacji dotyczących historii pieniądza. Dowiedzcie się, jakie dobra w przeszłości i dlaczego pełniły funkcję pieniądza oraz jakie formy przyjmował pieniądz. Dowiedzcie się, co to znaczy, że pieniądz jest środkiem tezauryzacji. Zwróćcie uwagę na pojęcie parytetu złota i dlaczego poszczególne kraje postanowiły od niego odejść. Do realizacji tego tropu niezbędne będzie zapoznanie się z pojęciami: PKB, PKB per capita, bank centralny, siła nabywcza pieniądza. Spróbujcie na podstawie waszej wiedzy stworzyć jak najdłuższą listę walut, a następnie dowiedzcie się, ile walut na świecie jest aktualnie w użyciu.',
      todo: 'W ramach tropu wybierzcie kilka walut, których historię chcielibyście poznać – mogą to być powszechnie znane waluty, takie jak: dolar amerykański, funt szterling, euro, frank szwajcarski, jen japoński lub historyczne, które miały bardziej dramatyczną historię, jak np. marki niemieckie lub dolar Zimbabwe. Zapoznajcie się z historią powstania każdej z wybranych walut oraz wyglądem ich monet i banknotów oraz sposobami ich ochrony przed fałszerstwem. Porównajcie siły nabywcze wybranych jednostek monetarnych w wybranych latach. W ciekawej formie przedstawcie, co w wybranych latach można było kupić za walutę o podobnej wartości w różnych krajach. Dowiedzcie się, co ma wpływ na kształtowanie kursów walut, czy działa w tym przypadku prawo popytu i podaży, jak działania państwa lub sytuacja na rynku wpływa na wartość danej waluty, a może sytuacje o znaczeniu globalnym mają na nie wpływ? Dowiedzcie się, czym są waluty prywatne/alternatywne i gdzie można je emitować. Wasze wnioski spróbujcie odnieść do tego, jak kształtował się wykres kursu danej waluty.',
      summary: 'Dokonajcie w zastępie podsumowania waszego tropu. Podsumujcie zebrane informacje o wybranych walutach w ciekawej formie np. ikonografiki i zamieście je na stronie waszego środowiska na portalu społecznościowym. Możecie przygotować również plakaty o wybranych walutach, które umieścicie w waszej szkole. Swoje spostrzeżenia i odkrycia zaprezentujcie na zbiórce drużyny, przeprowadzając quiz o walutach świata. Możecie też zaprojektować własną prywatną walutę – o co by się opierała? Jak by wyglądała? W jakim kraju byście ją wyemitowali i jakie obowiązywałyby Was prawa? Wyniki przedstawcie drużynie.'
  ),

  TropIdea(
      name: 'Magia nauki',
      category: TropCategory.harcOdkrywanie,
      intro: 'Czy pasjonują Was chemiczne lub fizyczne eksperymenty i chcielibyście poznać od kuchni przyczyny tych widowiskowych zjawisk? Część z nich można zrobić we własnym domu - spróbujcie!',
      plan: 'Przeszukajcie dostępne źródła (np. książki w bibliotece, Internet) lub skorzystajcie z porad specjalisty (np. nauczyciel chemii lub fizyki) i znajdźcie kilka mniej lub bardziej zaawansowanych doświadczeń fizycznych/chemicznych lub sztuczek magicznych wykorzystujących zjawiska fizyczne/chemiczne. Niech każda osoba z zastępu wybierze po kilka takich, które będzie w stanie wykonać samodzielnie w domowych warunkach, i postara się zrozumieć, jakie mechanizmy stoją za tą „magią”. Sprawdźcie, czy w Waszej szkole działa kółko zainteresowań chemicznych lub fizycznych, które mogłoby Wam pomóc w wymyślaniu eksperymentów. Pamiętajcie o tym, aby wszystko przygotowywać i realizować w bezpieczny sposób, a pierwsze próby wykonywać pod opieką kogoś dorosłego.',
      todo: 'Poszukajcie otwartych wykładów i pokazów fizycznych lub chemicznych realizowanych na uczelniach wyższych (czasem takie wykłady są realizowane dla osób spoza uczelni, aby zachęcić je do wybrania konkretnych kierunków studiów) lub weźcie udział w odwiedzinach w wybranym przez siebie centrum nauki (jak np. Centrum Nauki Kopernik). Możecie zorganizować wycieczkę do pobliskiej instytucji, ale także zorganizować wyjazd w bardziej odległy zakątek Polski. Wszystko to w porozumieniu z rodzicami i drużynowym. Dobrym tropem może być także szkolne kółko fizyczne lub chemiczne. Ważne, aby aktywnie wziąć udział w wybranej formie zdobywania wiedzy i wzbogacić swój zasób „magicznych sztuczek”. Zorganizujcie potem zbiórkę zastępu, na której wspólnie przeprowadzicie doświadczenia sprawdzone wcześniej samodzielnie w domu.',
      summary: 'Przygotujcie pokaz „magiczny” złożony z najlepszych Waszym zdaniem doświadczeń i zrealizujcie go w klasie (po ustaleniu z nauczycielami) lub w drużynie podczas specjalnej zbiórki. Pokaz musi być tak przygotowany, żeby zachęcić inne osoby do powtórzenia Waszej drogi, czyli nie tylko zachwytu, lecz także do zgłębienia prawideł nauki, którym towarzyszą tak atrakcyjne efekty. Możecie przygotować grę terenową lub fabularną na ten temat.'
  ),

  TropIdea(
      name: 'Nauka uczenia się',
      category: TropCategory.harcOdkrywanie,
      intro: 'Choć nie każdy o tym wie, uczenia się także trzeba się nauczyć. Istnieje wiele różnych sposobów efektywnego przyswajania wiedzy. Skorzystajcie z okazji, aby znaleźć najlepszy dla siebie.',
      plan: 'Istnieje wiele różnych sposobów efektywnego przyswajania wiedzy: od regularnych powtórek i wzajemnego odpytywania po systemy kolorowych notatek i mnemotechniki. A co mówi na ten temat świat nauki? Dowiedzcie się jak najwięcej o sposobach uczenia się i ich skuteczności. Zacznijcie od burzy mózgów, ale nie zapomnijcie poszukać dalszych informacji na ten temat, dbając o rzetelność źródeł wiedzy. Bogatym źródłem wiedzy o sposobach uczenia się jest książka Radosława Kotarskiego „Włam się do mózgu”.',
      todo: 'Niech każdy z Was wybierze optymalny dla siebie sposób uczenia się i stosuje go przynajmniej przez 2 tygodnie. Po tym czasie wymieńcie się spostrzeżeniami i wprowadźcie ewentualne modyfikacje. Spróbujcie porównać wybrane techniki – czy któraś z nich okazała się skuteczniejsza niż inne? Kolejnym krokiem będzie podzielenie się swoją wiedzą z innymi. Wybierzcie przedmiot szkolny, w którym odnosicie największe sukcesy, i zaproponujcie darmowe korepetycje innym uczniom. Mogą to być Wasi rówieśnicy lub młodsze dzieci uczęszczające do szkolnej świetlicy. Ważne jest, aby z Waszą pomocą przeszli przynajmniej jeden pełny cykl nauki: od rozpoczęcia działu po sprawdzian. Poza własną wiedzą z danego przedmiotu przekażcie także swoje nowe wiadomości o efektywnym uczeniu się.',
      summary: 'Sprawdźcie wokół siebie, czy ktoś nie prowadzi darmowych warsztatów z technik uczenia się, abyście mogli jeszcze bardziej poszerzyć swoją wiedzę. Podsumujcie swoje działanie na forum drużyny, przedstawiając zarówno osobiste osiągnięcia, jak i efekty Waszej pomocy innym. Może kolejni członkowie drużyny skorzystają z tego, czego się dowiedzieliście, a nawet przeprowadzą podobną akcję? Pokażcie im, dlaczego warto, np. organizując wszechnicę.'
  ),

  TropIdea(
      name: 'Naukowy zawrót głowy',
      category: TropCategory.harcOdkrywanie,
      intro: 'Dowiedzcie się, w jaki sposób przedstawiciele różnych nauk weryfikują swoje hipotezy oraz czym jest metodologia.',
      plan: 'Czy wiecie, czym różni się naukowiec od osób wykonujących inne zawody? Nie chodzi wcale o wyższy poziom inteligencji czy nawet o większą wiedzę specjalistyczną, ale o sposób pozyskiwania wiedzy o świecie. Odkryjcie trop „Naukowy zawrót głowy” i dajcie się zaskoczyć ciekawostkami naukowymi!',
      todo: 'Po zapoznaniu się z różnorodnością naukowych dociekań poszczególnych dyscyplin wybierzcie zagadnienie, na które chcecie spojrzeć z naukowej perspektywy. Może będzie to transplantologia, podbój kosmosu, problem zmian klimatu, a może zagrożenia związane z klonowaniem organizmów? Warto wybrać zagadnienie, wokół którego krąży w społeczeństwie wiele mitów. Dowiedzcie się o nim jak najwięcej, starannie wybierając źródła swojej wiedzy. Zorganizujcie w drużynie dyskusję lub sąd nad problemem na dany temat. Zadbajcie o rzetelne przygotowanie merytoryczne, korzystajcie z wiarygodnych źródeł. Zaproście do rozmowy eksperta w danej dziedzinie.',
      summary: 'Pozyskaną w naukowy sposób wiedzę wykorzystajcie do edukowania innych. Może zorganizujcie dla Waszych szkolnych kolegów spotkanie z naukowcem? Przygotujcie ulotkę cytującą zweryfikowane źródła? A może nagracie krótki film i rozpropagujecie go w Internecie lub przygotujecie audycję do szkolnego radia? Na każdym kroku podkreślajcie, jak ważne jest, aby budować swoją wizję świata w oparciu o rzetelną wiedzę.'
  ),

  TropIdea(
      name: 'Każdy inny, a jednak taki sam',
      category: TropCategory.harcBraterstwo,
      intro: 'Ludzie różnią się od siebie, ale każdy jest wartościowy i należy mu się szacunek. Niestety, niekiedy jest nam trudno zgodzić się z tym stwierdzeniem, a jeszcze trudniej samemu żyć miłując swoich bliźnich. Wykonajcie wysiłek w pracy nad sobą - jeśli Wy będziecie lepsi, świat będzie lepszy. Pociągnijcie swoim przykładem innych.',
      plan: 'Przeprowadźcie zbiórkę na temat konfliktów międzyludzkich i odtrącenia przez otoczenie. Skorzystajcie z pomocy i doświadczenia lokalnych instytucji, które zajmują się wspieraniu osób w potrzebie - zarówno materialnej jak i pozamaterialnej. Pomoże Wam to przygotować się do rozmowy we własnym gronie, a także do nawiązania kontaktu z osobami w potrzebie. Poszukajcie w swoim lokalnym środowisku osób, które mogą czuć się wykluczone przez środowisko (np. osoby z niepełnosprawnościami, chore, otyłe, ubogie, innego wyznania czy narodowości). Zaproście taką osobę na zbiórkę i dowiedzcie się więcej o jej życiu. Pokażcie jej, co Was interesuje i czym się zajmujecie. Następnie zastanówcie się, co możecie zrobić, by wesprzeć taką osobę.\n\nA może nie ma potrzeby szukać daleko, bo najbardziej potrzebujący są najbliżej Was?',
      todo: 'Aby pomóc takiej osobie (osobom), zorganizujcie dzień braterstwa w szkole, biwak dla Waszej drużyny, spotkanie lub inscenizację w Młodzieżowym Domu Kultury. Pokażcie, że mimo różnic między nami każdy jest wartościowy i należy mu się szacunek.'
          '\n\nW związku z delikatnym tematem tropu zastęp powinien być w stałym kontakcie z drużynowym oraz specjalistą, np. pedagogiem szkolnym. Dzięki temu działania nie zostaną spłycone.',
      summary: 'Na zbiórce podsumujcie Wasze działania i zastanówcie się, czy Waszym zdaniem to, co zrobiliście, jest wystarczające, by Wasze otoczenie spróbowało żyć w szacunku do wszystkich osób, nawet jeśli ich nie lubią. Czy udało Wam się zmienić także Wasze nastawienie (np. pokonać lęk przed podejmowaniem aktywności, które mogłyby być wyśmiane)? Pomyślcie, co jeszcze możecie zrobić, aby inność nie kojarzyła się Wam i Waszym rówieśnikom jedynie z czymś złym.'
  ),

  TropIdea(
      name: 'Świat z perspektywy niepełnosprawnych',
      category: TropCategory.harcBraterstwo,
      intro: 'Czy zastanawialiście się nad tym, jak wygląda zwykły dzień osób z trwałą lub okresową niesprawnością? Spróbujcie wejść w buty osób z niepełnosprawnościami i uwrażliwić innych na ich codzienne problemy.',
      plan: 'Czy znacie rodzaje niepełnosprawności? Warto dowiedzieć się więcej, szczególnie że nie każdy rodzaj niepełnosprawności widać gołym okiem, co nie znaczy, że życie z nią jest mniej dotkliwe. Sprawdźcie, czy w Waszej okolicy działa NGO zajmujące się osobami z niepełnosprawnościami – dzięki temu łatwiej Wam będzie nawiązać z nimi kontakt.',
      todo: 'Spotkajcie się z kimś, kto opowie Wam o tym, jak wygląda jego życie z niepełnosprawnością i jakie są jego największe bolączki. Postarajcie się doświadczyć choćby przez kilka godzin podobnych ograniczeń, np. odwiedzając tzw. niewidzialny dom lub poruszając się przy pomocy wózka inwalidzkiego czy o kulach do ośrodka zdrowia, urzędu miasta itp. Wspólnie zastanówcie się, czy jest coś, co możecie zrobić, aby ułatwić osobom z niepełnosprawnościami codzienne funkcjonowanie, a potem zabierzcie się do dzieła.',
      summary: 'Czego dowiedzieliście się podczas tego tropu? Czy lepiej rozumiecie warunki życia osób z niepełnosprawnościami? Czy udało Wam się zrobić coś pożytecznego? A może uważacie, że można zdziałać jeszcze więcej, i chcecie kontynuować swoje przedsięwzięcie? Zachęćcie do pomocy także inne osoby z Waszej drużyny. Możecie na przykład zorganizować zajęcia lub stoisko podczas harcerskiego festynu, gdzie inni również będą mogli doświadczyć danej niepełnosprawności, albo happening w swojej szkole lub parafii.'
  ),

  TropIdea(
      name: 'Zero zniewag',
      category: TropCategory.harcBraterstwo,
      intro: 'Niestety zniewagi są powielane zarówno przez dorosłych, jak i przez dzieci i młodzież. Spróbujcie zminimalizować te negatywne zjawiska.',
      plan: 'Dowiedzcie się, czym jest zniesławienie. Rozejrzyjcie się w swoim wirtualnym otoczeniu – poszukajcie miejsc, gdzie jest ono wszechobecne, i zobaczcie, jaki ma charakter. Pomyślcie, jak dużo osób go doświadcza i jak bardzo to może niszczyć czyjeś życie. Spotkajcie się z psychologiem lub pedagogiem z Waszej szkoły i porozmawiajcie o tym, jak radzić sobie z krzywdzącymi słowami i mówić o nich, a szczególnie w internecie. Sprawdźcie, jak ze zniesławieniem radzą sobie platformy, na których najczęściej on występuje. Podzielcie się swoimi obserwacjami podczas dyskusji w zastępie. Możecie stworzyć mapę myśli, aby zobrazować to, czego się dowiedzieliście.',
      todo: 'Zorganizujcie akcję „Zero zniewag”. Wymyślcie, w jaki sposób przekonacie młodych ludzi, by ograniczyli zniewagi w internecie. Stwórzcie motywatory (odwrotność demotywatorów), filmiki lub zdjęcia, które będą zachęcały do pozytywnego widzenia świata. Stwórzcie grupę, stronę, blog lub wydarzenie mające na celu pokazanie alternatyw dla zniewag. Zorganizujcie wydarzenie lub warsztaty uczące reagowania na zniewagi.',
      summary: 'Po skończeniu działań w ramach tropu przejrzyjcie miejsca, do których je kierowaliście, i zobaczcie, czy zmieniły się one dzięki Wam. Zorganizujcie zbiórkę podsumowującą Waszą akcję. Warto też przygotować prezentację pokazującą, co stworzyliście. Możecie też przygotować reportaż filmowy prezentujący całą akcję.'
  ),

  TropIdea(
      name: 'Lokalny przewodnik po Małej Ojczyźnie',
      category: TropCategory.harcOjczyzna,
      intro: 'Czy w Waszym mieście/gminie mieszkał ktoś sławny? A może w pobliżu znajduje się miejsce ważnej bitwy albo innych ciekawych wydarzeń historycznych? Może macie jakieś budynki wpisane do rejestru zabytków albo ciekawe legendy? Na pewno warto się tym zainteresować i podzielić z innymi zdobytą wiedzą.',
      plan: 'Po konsultacji z drużynowym przeprowadźcie zwiad terenowy: popytajcie miejscowych nauczycieli lub pasjonatów historii, odwiedźcie bibliotekę, dom sołtysa czy urząd miasta/gminy. Poszukajcie ciekawostek związanych z Waszym miejscem zamieszkania.',
      todo: 'Wybierzcie najbardziej ciekawiące Was rzeczy i dowiedzcie się o nich jak najwięcej. Nawiążcie współpracę z historykiem i lokalnymi mediami – regionalną stacją TV, radiową, gazetą, stroną internetową, fanpage’em miejscowości. Jeżeli mieszkacie w dużym mieście, pamiętajcie, że mogą to być media związane z dzielnicą, a nawet osiedlem. Zaplanujcie i zorganizujcie akcję popularyzacyjną – grę miejską, wystawę tematyczną, spotkanie z ważną osobistością. Niech te propozycje będą otwarte dla społeczności lokalnej. A może macie w swojej okolicy jakieś szlaki turystyczne wymagające odświeżenia oznaczeń albo właśnie takich szlaków brakuje? Może znajdziecie szczególnie atrakcyjne walory przyrodnicze, które potrzebują oczyszczenia z zalegających śmieci?',
      summary: 'Omówcie wnioski z drużyną. Stwórzcie i prześlijcie do lokalnej gazety lub mediów społecznościowych materiał podsumowujący wasze działania, np. fotoreportaż, filmik, komiks. Możecie też zrobić makietę, którą później sfotografujecie.'
  ),

  TropIdea(
      name: 'Piękne polskie miasta',
      category: TropCategory.harcOjczyzna,
      intro: 'Czy spacerowaliście Aleją Sław w Kielcach, zastanawiając się nad waszymi autorytetami? A może wiecie, jak powstawały animacje w SE-Ma-Forze w Łodzi? W waszej okolicy zapewne także znajduje się miasto z ciekawą, lecz mało znaną atrakcją/historią - wyruszcie na poszukiwania!',
      plan: 'Czy słyszeliście kiedyś jak trykają koziołki w Poznaniu? Wiecie, ile jest krasnali we Wrocławiu? Czy kosztowaliście kiedyś cebularza w Lublinie? Próbowaliście nauczyć się kilku słów w języku esperanto w Białymstoku? Próbowaliście kiedyś zrobić samodzielnie piernika w Toruniu? Zastanówcie się, tajemnice którego z polskich miast chcielibyście zgłębić, które z nich obejrzeć? Podzielcie się zadaniami podczas przygotowywania wycieczki: organizacji transportu, wyżywienia, trasy zwiedzania, atrakcji. Oczywiście na wycieczkę należy wybrać się z pełnoletnim opiekunem.',
      todo: 'Razem z pełnoletnim opiekunem pojedźcie do wybranego przez was miejsca. Zróbcie tam zwiad, poznajcie historię, znaczenie nazwy, lokalne legendy. Odwiedźcie najciekawsze atrakcje, poszukajcie budynków wpisanych do rejestru zabytków. Koniecznie znajdźcie drużynę działającą na tym terenie i zaaranżujcie wspólną zbiórkę, na której wymienicie się doświadczeniami!',
      summary: 'Pochwalcie się w mediach społecznościowych, czym zachwyciło was dane miasto, czemu jesteście dumni z piękna naszej Ojczyzny. Zaprezentujcie odkryte miejsce w swoim otoczeniu! Możecie zrobić to w formie makiety wyeksponowanej w szkole, wystawy fotografii, projekcji nakręconego przez was reportażu. Niech Wasza relacja będzie jak najbardziej wyjątkowa, rozpowszechnijcie ją w drużynie, wśród znajomych, rodziców. Podsumujcie kwestie organizacyjne i wyciągnijcie wnioski. Czy historia miejsca, które odwiedziliście, wzbudziła w was jakieś refleksje? Czy zapoznani harcerze nauczyli was czegoś nowego? '
  ),

  TropIdea(
      name: 'Piknik o harcerskim zdrowym stylu życia',
      category: TropCategory.harcCzlowiek,
      intro: 'Człowiek jest tym, co je. Jeśli zgadzacie się z tym zdaniem, to może będziecie chcieli zainwestować swój czas i zdolności, aby przekonać do tego sposobu myślenia innych.',
      plan: 'Człowiek jest tym co je – czy zgadzacie się z tym zdaniem? Aby odpowiedzieć sobie na to pytanie, zorganizujcie spotkanie z dietetykiem w formie warsztatów na temat zdrowego odżywiania (jeśli w waszej miejscowości trudno o takiego specjalistę skorzystajcie z możliwości wideokonferencji przez telefon lub komputer). Poznajcie konsekwencje niezdrowego trybu życia dla organizmu i przeanalizujcie własne nawyki żywieniowe (np. przez prowadzenie dzienniczka).',
      todo: 'Przygotujcie harcerski piknik o zdrowym stylu życia, propagujący prawidłowe żywienie i aktywność fizyczną. Na pikniku możecie wykorzystać takie atrakcje jak zdrowe przekąski z ogniska wymyślone przez każdego członka zastępu czy turniej sportów dawnych (np. zawody w palanta). Możecie też przygotować stanowiska na temat niezdrowej żywności, wykorzystując ciekawostki znalezione w internecie, jak na przykład: co dzieje się z zupką chińską w moim brzuchu, ile cukru zawierają popularne napoje, jak nadmiar cukru wpływa na moje ciało. Pamiętajcie, by wcześniej przeanalizować znalezione informacje pod kątem ich wiarygodności - internet jest nie tylko kopalnią wiedzy, ale i manipulacji.',
      summary: 'Podsumujcie waszą pracę na forum drużyny oraz pozostawcie stworzone materiały i plansze w ramach wystawy w harcówce czy w gablocie szkolnej lub świetlicowej. Zastanówcie się, czy zdobywanie tego tropu spowodowało zmiany w waszym sposobie odżywiania.'
  ),

  TropIdea(
      name: 'Przez żołądek do zdrowia',
      category: TropCategory.harcCzlowiek,
      intro: 'Spróbujcie odpowiedzieć sobie na pytanie, co jada się na biwakach i wyjazdach. Czy jecie zdrowo, czy – korzystając z okazji – opychacie się chipsami i chińskimi zupkami? A jak wygląda wasza codzienna dieta? Może czas coś zmienić?',
      plan: 'Poszukajcie pośród rodziców, instruktorów i znajomych dietetyka lub innej osoby zajmującej się tematem żywienia np. pediatry, który pomoże wam w kolejnych krokach. Jeśli nie macie nikogo takiego w swoim otoczeniu, pamiętajcie, że Internet może wam pomóc w kontakcie ze specjalistą z innej miejscowości, a nawet państwa.',
      todo: 'Niech każdy z was przeanalizuje swoją codzienną dietę. Przez dwa tygodnie zapisujcie co, w jakiej ilości i kiedy jecie. Po konsultacji z drużynowym, spotkajcie się z dietetykiem lub innym specjalistą, z którym podzielicie się swoimi spostrzeżeniami i doświadczeniami (warto przy okazji przeanalizować też wyjazdowe nawyki żywieniowe). Znajdźcie dania, które będą jednocześnie szybkie do przygotowania, niewymagające wiele czasu i trudnych do zdobycia produktów. Pod okiem specjalisty wypróbujcie kilka z tych przepisów. Weźcie pod uwagę także osoby ze specjalnymi potrzebami (np. nietolerancją laktozy czy glutenu, wegetarian lub wegan) i dopilnujcie, aby i dla nich mieć przećwiczone propozycje.'
          '\n\nPodczas organizacji najbliższego biwaku lub wypadu drużyny zadbajcie o wspólne posiłki w duchu sprawdzonych przez Was przepisów. Zadbajcie nie tylko o jedzenie (w tym przyjazne środowisku zakupy), ale także sposób podania, pamiętajcie o wszystkich zasadach higieny. Jeśli w najbliższym czasie nie będzie organizowany żaden wypad – zaproponujcie zbiórkę kulinarną, na której wspólnie z drużyną przygotujecie wyśmienitą kolację.',
      summary: 'Przekażcie zdobytą wiedzą reszcie drużyny podczas zbiórki. Możecie przygotować drużynowe książki z przepisami do realizacji na biwakach. Ważne informacje na temat żywienia możecie przedstawić w formie plakatu, komiksu lub infografiki, która zawiśnie w harcówce.'
  ),

  TropIdea(
      name: 'Skrzydlaty umysł',
      category: TropCategory.harcCzlowiek,
      intro: 'Odpoczywaj mądrze - nie oznacza leżenia i odkładania książek na półkę. Stwórzcie skrzydła, by wasze umysły też mogły odpocząć.',
      plan: 'Poobserwujcie, jak ludzie odpoczywają, a jak wy lubicie odpoczywać i porozmawiajcie o tym. Zaplanujcie strefę odpoczynku i koncentracji w harcówce/na biwaku/obozie – uwzględniając wasze potrzeby.',
      todo: 'Proponowany podział zadań w zastępie:'
          '\n\n• Obejrzyj filmiki o tym, jak ludzie odpoczywają – czym/kim się otaczają. Co jest dla nich ważne. Porozmawiaj z zastępem o zauważonych prawidłowościach – jakie najczęściej się powtarzały i dlaczego. Zorganizuj burzę mózgów: Czym jest dla was odpoczynek? Jakie warunki muszą zostać spełnione, abyście czuli się wypoczęci? Zastanówcie się, czym może być skrzydlaty umysł?'
          '\n\n• Zapoznaj się z materiałami popularno-naukowymi dotyczącymi form relaksacji, tego jak odpoczywa mózg, a jak ciało, czym jest floating, jak zmysły człowieka wpływają na koncentrację i odpoczynek itp. Zebrane informacje wykorzystaj podczas tworzenia strefy odpoczynku i koncentracji w harcówce/na biwaku/obozie.'
          '\n\n• Stwórz samodzielnie nowe narzędzia: jedno do relaksacji i jedno do koncentracji a następnie wykorzystaj je w strefie wypoczynku. Sprawdź w praktyce, czy będą przynosiły zamierzony efekt.'
          '\n\n• Poznaj po 3 różne techniki relaksacji ciała i umysłu. Przeprowadź je w ramach spotkań w strefie wypoczynku.'
          '\n\n• Przeprowadź zbiórkę dotyczącą potrzeby odpoczynku i problemu koncentracji wśród młodych osób. Zaprezentuj różne podejścia kulturowe do tematu odpoczynku, np. w Japonii, Norwegii i Polsce np. w formie quizu.',
      summary: 'Zastanówcie się, który zmysł jest dla was kluczowy podczas relaksacji, a który podczas koncentracji? Czy udało Wam się stworzyć nową przestrzeń, w której wszyscy w drużynie są wstanie odpoczywać i czuć się dobrze? Nagrajcie filmik, który przedstawi waszą strefę odpoczynku i koncentracji – jak ona powstawała, jak wyglądają nowe narzędzia/przedmioty, jakie macie zdanie na temat potrzeby odpoczynku? Filmik udostępnijcie drużynie z innego hufca/chorągwi – w ramach inspiracji bądź wymiany na temat stworzenia oraz potrzeby strefy odpoczynku i relaksacji w środowisku harcerskim. O pomoc w kontakcie z inną jednostką poproście drużynowego.'
  ),

  TropIdea(
      name: 'Sportowy przegląd',
      category: TropCategory.harcCzlowiek,
      intro: 'Czy zastanawialiście się kiedyś, na czym polega curling? Czy mieliście ochotę wziąć udział w treningu karate? Czy informacja o biegach ekstremalnych przyśpiesza obieg krwi w Waszych żyłach? Czy chcielibyście wyskoczyć w powietrze niczym Małysz? Czy uważacie swoje marzenia za nierealne? Zobaczcie, że przy odrobinie wysiłku są w zasięgu ręki!',
      plan: 'Zbadajcie swoje własne sportowe marzenia, opowiedzcie sobie wzajemnie o waszych planach, zamiarach i chęciach. Podejmijcie wyzwanie kilku zbiórek przeglądu sportowego, w ramach którego poznacie kilka dyscyplin sportowych (warto spróbować także tych mniej popularnych jak: rugby w wersji soft, nożna siatkówka, bike polo, waterpolo czy nawet wersja quidditcha dla mugoli).',
      todo: 'Weźcie udział w wybranych treningach, poszukajcie szerokich możliwości nawiązania współpracy z klubami sportowymi lub indywidualnymi sportowcami, nauczycielami WF, trenerami lub lokalnymi pasjonatami (poszukajcie także wśród swoich rodziców). Pamiętajcie, by podczas treningu był z wami pełnoletni opiekun. Skorzystajcie z każdej możliwości, a każde działanie uwiecznijcie w wybranej przez siebie formie.',
      summary: 'Zbierzcie wszystkie swoje wrażenia, podzielcie się nimi na forum drużyny i rodziców. Wykorzystajcie do tego różne formy: film, wystawę fotografii, a także bardziej angażujące takie jak olimpiada sportowa. Pokażcie, z czym mieliście największe problemy, co Wam dało najwięcej radości, co byście chcieli kontynuować indywidualnie lub grupowo. Może któryś sport tak was zainteresował, że chcielibyście zorganizować trening dla kolegów i koleżanek ze szkoły? Oceńcie udział w projekcie całego zastępu i poszczególnych członków.'
  ),

  TropIdea(
      name: 'Trop dobrze być sobą – nie dla sztucznego ideału (dla chłopców)',
      category: TropCategory.harcCzlowiek,
      intro: 'tereotyp piękna promowany przez media jest niemożliwy do osiągnięcia. Młodzi ludzie krzywdzą się by osiągnąć rezultaty widziane w telewizji i Internecie. Sztuczny świat mody jest retuszowany, obrabiany w programach graficznych i filmowych. Pokażmy prawdziwe piękno!',
      plan: 'Zobaczcie, jak zmieniał się wzór idealnego mężczyzny na przestrzeni wieków zarówno pod względem wyglądu, jak i innych przymiotów. Obejrzyjcie kilka zdjęć bez retuszu i po nim, które możecie znaleźć, np. w Internecie. Spróbujcie wspólnie ustalić, czym różnią się one od siebie. Pomocne będzie ćwiczenie z propozycji WAGGGS „Dobrze być sobą” dla grupy wiekowej 11-14 lat, str. 18. Dowiedzcie się, jakie problemy mają chłopcy, którzy chcą być idealni. Poszukajcie sojuszników (szkoły, fundacji, domu kultury), aby dowiedzieć się, co na ten temat wiedzą specjaliści i jakie działania podejmują w celu pomocy w samoakceptacji.',
      todo: 'Pokażcie, że dobrze jest być sobą! Poszukajcie w Waszym środowisku lokalnym osób, które potrzebują pomocy w samoakceptacji. Zorganizujcie kampanię na temat dobrego i zdrowego wyglądu.'
          '\n\nPokażcie konsekwencje złego odżywiania, nadmiernych ćwiczeń (często wspomaganych anabolikami). Zaproponujcie możliwości dbania o siebie, które nie wywołują negatywnych skutków. Zadbajcie o szeroką reklamę Waszych działań i pokażcie w Internecie, jak bardzo Wam zależy na dobrym, zdrowym wyglądzie. Oszacujcie we współpracy z instytucjami publicznymi koszty, które ponoszą osoby, dążące do ideału piękna.',
      summary: 'Podsumujcie Wasze działania. Zobaczcie, jak Wasza akcja wpłynęła na społeczność lokalną i jakie dała ona efekty. Opracujcie materiał, będący podsumowaniem działań,  a który może później służyć kolejnym grupom walczącym z tym problemem. Jeżeli jesteście zainteresowani tym tematem, zajrzyjcie do Centralnego Banku Pomysłów, gdzie znajdziecie propozycję WAGGGS „Dobrze być sobą” dla grupy wiekowej 11-14 lat.'
  ),

  TropIdea(
      name: 'Trop dobrze być sobą – prawdziwe piękno (dla dziewcząt)',
      category: TropCategory.harcCzlowiek,
      intro: 'Stereotyp piękna promowany przez media jest niemożliwy do osiągnięcia. Młodzi ludzie krzywdzą się by osiągnąć rezultaty widziane w telewizji i Internecie. Sztuczny świat mody jest retuszowany, obrabiany w programach graficznych i filmowych. Pokażmy prawdziwe piękno!',
      plan: 'Zobaczcie, jak zmieniał się kanon kobiecego piękna na przestrzeni wieków. Obejrzyjcie kilka zdjęć bez retuszu i po nim, które możecie znaleźć, np. w Internecie. Spróbujcie wspólnie ustalić, czym różnią się one od siebie. Pomocne będzie ćwiczenie z propozycji WAGGGS „Dobrze być sobą” dla grupy wiekowej 11-14 lat, str. 18. Dowiedzcie się, jakie problemy zdrowotne mają dziewczęta, które chcą mieć idealne wymiary. Poszukajcie sojuszników (szkoły, fundacji, domu kultury), aby dowiedzieć się, co na ten temat wiedzą specjaliści i jakie działania podejmują w celu pomocy w samoakceptacji.',
      todo: 'Pokażcie, że dobrze jest być sobą! Zorganizujcie kampanię w szkole, w domu kultury lub w Waszym harcerskim środowisku na temat zdrowego żywienia i walki z presją otoczenia wobec stereotypu piękna. Możecie też przygotować i poprowadzić warsztaty o akceptowaniu swojego ciała dla wybranej placówki w miejscowości Waszego działania, np. świetlicy środowiskowej.'
          '\n\nPoszukajcie w klasie, szkole lub na osiedlu dziewczyn, które się głodzą, mają niską samoocenę oraz rozchwiany system wartości z powodu dążenia do sztucznego piękna. Napiszcie do nich listy, stwórzcie grupę wsparcia.'
          '\n\nRozpocznijcie w Internecie akcję wsparcia dla osób, które tego potrzebują. Postarajcie się stworzyć stałe pole działania, aby móc być dla nich wsparciem. Akcja powinna być uniwersalna, nie personalna. Dobrym pomysłem dla dziewczyn będzie, np. naturalny pokaz mody albo naturalna sesja zdjęciowa, której efekty pokażecie na wystawie PURE BEAUTY.',
      summary: 'Zastanówcie się, czy dotarłyście do dużej grupy odbiorców. Pomyślcie, jak przebiegała pomoc dziewczynom. Opracujcie materiał, będący podsumowaniem akcji, a który może później służyć kolejnym grupom walczącym z tym problemem. Jeśli jesteście zainteresowane tym tematem, zajrzyjcie do Centralnego Banku Pomysłów, gdzie znajdziecie propozycję WAGGGS „Dobrze być sobą” dla grupy wiekowej 11-14 lat.'
  ),

  TropIdea(
      name: 'Zielnik harcerski',
      category: TropCategory.harcCzlowiek,
      intro: 'Czy wiecie, że zioła mogą leczyć? Znacie jakieś przykłady roślin wykorzystywanych w medycynie? Jeśli interesuje was ziołolecznictwo, ten trop jest dla was.',
      plan: 'Bardzo wiele pospolicie występujących ziół można z powodzeniem wykorzystywać jako wsparcie leczenia drobnych schorzeń takich jak problemy gastryczne, wzmacnianie odporności czy nawet leczenie trądziku! Gatunkami bardzo łatwymi do rozpoznania i bezpiecznymi w użyciu są np. wierzbówka kiprzyca (herbata), mięta pieprzowa, kwiaty mniszka czy pędy sosny (syrop), owoce jałowca (przyprawa), dzika róża/głóg (dżemy, dodatek do herbat), itp. Są też takie, których nie powinno się przyjmować bez konsultacji z lekarzem. Poszukajcie w dostępnych źródłach informacji o ziołach naszych łąk i lasów: jak wyglądają, kiedy się je zbiera, jak przygotowuje się je do użytku i do czego można je wykorzystać. Możecie też nawiązać kontakt ze specjalistą np. fitoterapeutą.'
          '\n\nPrzydatnymi merytorycznie materiałami są strona oraz książka Łukasza Łuczaja (np. Dzika Kuchnia).',
      todo: 'Po konsultacji z drużynowym wybierzcie się na zwiad w poszukiwaniu ziół w waszej okolicy lub załóżcie swój własny ogród zielarski. Zorganizujcie zajęcia/grę nt. zielarstwa na biwaku drużyny. Jeżeli znalezione w trakcie planowania informacje okażą się niewystarczające, znajdźcie w swoim środowisku zaprzyjaźnionego farmaceutę specjalizującego się w ziołolecznictwie lub zielarza, który wam pomoże. Możecie wybrać się z przygotowanymi zajęciami do Uniwersytetu Trzeciego Wieku lub Domu Pomocy Społecznej, jeżeli wasze środowisko współpracuje z takimi instytucjami.',
      summary: 'Zastanówcie się, czy zioła mogą zastąpić leki syntetyczne? Skąd czerpać wiarygodną wiedzę na temat ziołolecznictwa? Czy wszystkie zioła są w pełni bezpieczne i można je bez przeszkód łączyć np. z lekami? Omówcie wnioski na forum drużyny - możecie przygotować infografikę lub gazetkę, która wam w tym pomoże.'
  ),

  TropIdea(
      name: 'Drzewo życzeń',
      category: TropCategory.harcNatura,
      intro: 'Czy zastanawialiście się kiedyś, jakie kryteria musi spełnić drzewo, aby zostać pomnikiem przyrody? Wiedzieliście, że takie miano mogą uzyskać także aleje, głazy, skałki czy wodospady? Czujecie się zaintrygowani? Jeśli tak – to trop dla was.',
      plan: 'Dowiedzcie się, jak wygląda ustanawianie pomników przyrody w Polsce i jakie formalności muszą być spełnione (warto pamiętać, że pomnikami przyrody mogą być nie tylko drzewa, ale także np. aleje, głazy, skałki, wodospady). Po konsultacji z drużynowym zajrzyjcie do zaprzyjaźnionej leśniczówki lub umówcie się na wizytę w nadleśnictwie. Odwiedźcie również gminne i miejskie urzędy i ich komórki zajmujące się ochroną przyrody. Nawiążcie kontakt z Ligą Ochrony Przyrody lub lokalnymi naukowcami prowadzącymi badania na tych terenach (pierwszym punktem szukania kontaktu może być strona społeczności naukowej „Nauka dla przyrody").',
      todo: 'Wykonajcie zwiad po waszej okolicy. Według wcześniej pozyskanych wskazówek poszukajcie drzew, które są już pomnikami przyrody i są odpowiednio oznaczone, a także drzew, które według Was powinny stać się takimi pomnikami. Wykonajcie pomiary (przy użyciu odpowiednich narzędzi i technik, które możecie poznać z pomocą leśnika, specjalnej aplikacji lub programu komputerowego np. Globe Observer), a następnie stwórzceie rysopisy oraz mapy położenia.'
          '\n\nSwoje wnioski w zakresie pomysłów na nowy pomnik (jeśli takie macie) przekażcie odpowiednim służbom. Być może uda Wam się otoczyć taką opieką konkretne, wybrane przez siebie drzewo. Jeśli zauważyliście, że jakiś pomnik przyrody jest zaniedbany – poinformujcie odpowiednie jednostki, aby mogły temu zaradzić.',
      summary: 'Podsumujcie w zastępie wykonane zadania. Podzielcie się zdobytą wiedzą i osiągnięciami ze swoją drużyną, szczepem, hufcem – zróbcie to w ciekawej formie. Może zorganizujecie dla harcerzy grę, która pokaże im pomniki przyrody w waszym mieście? Może chcecie napisać artykuł do hufcowej gazety, stworzyć wystawę fotografii lub makietę, którą ustawicie w budynku użyteczności publicznej? Dajcie się ponieść wyobraźni!'
  ),

  TropIdea(
      name: 'Przyjaciel ptaków',
      category: TropCategory.harcNatura,
      intro: 'Nie trzeba być ornitologiem, aby być przyjacielem ptaków. Sprawdźcie, co dobrego możecie zrobić na ich rzecz w swoim środowisku działania.',
      plan: 'Dowiedzcie się, jakie ptaki żyją w Waszej okolicy. Po konsultacji z drużynowym wybierzcie się na zwiad do lasu, parku. Obserwujcie ptaki, rozpoznajcie je. Zastanówcie się, w jaki sposób możecie im pomóc? Może któremuś z gatunków grozi wyginięcie? A może zaobserwujecie domowego pupila, który uciekł właścicielowi? Może znajdziecie pisklę, które wypadło z gniazda? Zastanówcie się, w jaki sposób możecie im pomóc (dla przykładu w przeważającej ilości wypadków podlotów nie należy dotykać, ani na siłę „ratować"). Dowiedzcie się, czym żywią się ptaki w naturalnym środowisku, a czym te hodowlane. Zastanawialiście się, dlaczego niektóre ptaki są obrączkowane?',
      todo: 'Znajdźcie instytucję zajmującą się dzikim ptactwem (np. Liga Ochrony Przyrody, Towarzystwo Ochrony Ptaków), nawiążcie z nimi współpracę i pomóżcie na tyle, na ile jest to możliwe. Włączcie się w akcję liczenia ptaków migrujących lub obrączkowania. Nagrajcie spotkane ptaki, ich odgłosy i zmontujcie z tego materiał edukacyjny (skorzystajcie przy tym z fachowej wiedzy np. wielkiego atlasu ptaków lub aplikacji do rozpoznawania głosów BirdNet).'
          '\n\nZbierzcie potrzebny materiał do stworzenia budek lęgowych (zadbajcie o zbadanie potrzeb i montaż budek odpowiednich rozmiarów dla konkretnych gatunków ptaków) lub poideł. W porozumieniu z nadleśnictwem umieśćcie je w miejscach, które zostaną wam wskazane. Zwróćcie uwagę na problem wycinki drzew dziuplastych i zgłoście ten proceder do odpowiednich służb (zgłoszenie przestępstwa na policję oraz skarga na działania nadleśnictwa do Regionalnej Dyrekcji Ochrony Środowiska). Ważne są także działania w przestrzeni miejskiej lub wiejskiej, w sąsiedztwie siedzib ludzkich (np. problemem jest niszczenie miejsc lęgowych ptaków w miastach).',
      summary: 'Pokażcie innym, jak można pomagać ptakom. Zaprezentujcie młodszym kolegom materiał edukacyjny, zorganizujcie grę terenową lub imprezę na orientację, podczas której pokażecie, gdzie są budki lęgowe. Zorganizujcie w drużynie kominek tematyczny poświęcony temu zagadnieniu. Zachęćcie innych do działań na rzecz ptaków w waszej okolicy. Zastanówcie się, czy takie działania przyniosły wam satysfakcję; może zachęci to was do pomocy innym zwierzętom?'
  ),

  TropIdea(
      name: 'Zaopiekuj się mną',
      category: TropCategory.harcNatura,
      intro: 'Podobno charakter człowieka można poznać po tym, jak traktuje zwierzęta. Harcerzy zaś dodatkowo po tym, że w obliczu ważnych kwestii podejmują aktywne działania. Weźcie zwierzęta waszej lokalnej społeczności w skrojoną dla nich na miarę opiekę.',
      plan: 'W Waszym otoczeniu na pewno działa jakieś schronisko dla zwierząt, dla psów, dla kotów, dla królików. Zajrzyjcie do niego i popytajcie, jakiej pomocy potrzebują.',
      todo: 'Na podstawie zasygnalizowanych potrzeb – zorganizujcie swoje działanie. Jeśli potrzebą jest brak karmy czy innych materiałów – możecie zorganizować akcję zarobkową lub zbiórkę niezbędnych przedmiotów. Jeśli potrzebą jest przyjaźń ze zwierzakami i wyprowadzanie ich na spacer – być może uda Wam się zaangażować lub też zrobić akcję nagłaśniającą i zachęcającą do zostania wolontariuszem schroniska? A może wspólnie z pracownikami ośrodka uznacie, że najpotrzebniejsze byłoby uświadomienie społeczności lokalnej problemu porzucania zwierząt i przeprowadzenie kampanii informacyjnej pod hasłem „Zwierzę to nie zabawka"?'
          '\n\nWykorzystajcie swoje działanie także po to, aby więcej dowiedzieć się o właściwych formach opieki nad poszczególnymi zwierzętami.',
      summary: 'Zorganizujcie dla drużyny zbiórkę o potrzebach zwierząt w schroniskach, przekażcie zdobytą wiedzę i opiszcie, jak przebiegała wasza akcja. Możecie ubarwić waszą opowieść filmem lub fotografiami.'
  ),

  TropIdea(
      name: 'Zielony raj',
      category: TropCategory.harcNatura,
      intro: 'Jeśli radość sprawiają wam prace manualne, a w dodatku lubicie spędzać czas razem na świeżym powietrzu ten trop jest przeznaczony właśnie dla was.',
      plan: 'Poszukajcie skrawka wolnej ziemi, który będziecie mogli zagospodarować. Może to być kawałek ogródka działkowego któregoś z rodziców. Może to być kawałek nieużytku przy bloku – za zgodą właściciela terenu. Może to być także fragment dawnego klombu przy szkole – za zgodą dyrekcji. To jaką ziemią będziecie dysponować i w jakim miejscu na pewno wskaże Wam dalszy kierunek działań.',
      todo: 'Przygotujcie koncepcję zagospodarowania dla wybranego fragmentu ziemi. Możecie stworzyć efektowny skalniak z wykorzystaniem nietypowych roślin, oczek wodnych czy miniwodospadów. Być może uda Wam się tam stworzyć coś na wzór drzewek bonsai. Możecie stworzyć zielnik, po który sięgniecie w czasie potrzeby (mięta przyda się nie tylko na problemy żołądkowe, ale również do napojów na ciepłe dni; oregano czy majeranek - będą świetnymi przyprawami do dań). Możecie również pokusić się o stworzenie łąki kwietnej (wymaga zdecydowanie mniej podlewania niż trawnik), która przyciągnie pszczoły (można dla nich i innych owadów zbudować hotele, a dla ptaków i jeży poidła) albo posadzić kilka drzewek owocowych, których będziecie doglądać. Jeśli połączycie łąkę kwietną z miniogródkiem warzywnym przekonacie się przy okazji, że nawet w mieście można hodować własne jedzenie.'
          '\n\nPrzez okres próby zrealizujcie swój pomysł i doglądajcie go codziennie (pamiętajcie, aby podlewać go po zmroku, świetnym pomysłem na zaradzenie problemowi z niedoborem wody pitnej w Polsce jest także gromadzenie deszczówki). Reagujcie na zmieniające się warunki środowiska i pogodę. Wasz „ogródek” będzie wymagać takiej opieki, a po jakimś czasie odpłaci Wam wyglądem lub dobrami. Po jakimś czasie będziecie mogli pochwalić się swoimi owocami lub warzywami, zebranymi przyprawami lub pięknym widokiem skalniaka czy łąki.',
      summary: 'Podsumujcie swoje działania w zastępie i zdecydujcie, w jakiej formie chcecie zaprezentować je drużynie. Może stworzycie fotorelację lub film poklatkowy, aby pokazać, jak zmienił się zagospodarowany teren? Może podczas biwaku zorganizujecie poczęstunek, do którego wykorzystacie wyhodowane przez siebie warzywa i zioła? Możecie też zainspirować do podobnych działań swoich kolegów i koleżanki ze szkoły i zorganizować warsztaty, podczas których opowiecie, jak dbać o ogródek i co warto w nim zasiać.'
          '\n\nTrop nie powinien trwać dłużej niż 1,5 miesiąca. Po tym okresie należy go podsumować. Natomiast nic nie stoi na przeszkodzie, aby harcerze już po zdobyciu tropu mogli dalej opiekować się swoim miejscem.'
  ),
];